function tests = test_stage0_stage1
tests = functiontests(localfunctions);
end

function setupOnce(test_case)
test_dir = fileparts(mfilename('fullpath'));
project_dir = fileparts(test_dir);
test_case.TestData.project_dir = project_dir;
addpath(fullfile(project_dir, 'src'));
addpath(fullfile(project_dir, 'src', 'params'));
addpath(fullfile(project_dir, 'src', 'results'));
addpath(fullfile(project_dir, 'src', 'protocol'));
end

function testStage0FreezeCheckPassesWithoutRunningNestedTests(test_case)
report = stage0_freeze_check(struct('run_tests', false));

verifyTrue(test_case, report.passed);
verifyTrue(test_case, report.protocol_valid);
verifyTrue(test_case, report.manifest_valid);
verifyEmpty(test_case, report.forbidden_hits);
verifyEqual(test_case, report.required_files_missing, strings(0, 1));
verifyEqual(test_case, report.forbidden_files_present, strings(0, 1));
end

function testStage1DryRunPreparesAnnualZhouS2Inputs(test_case)
[result, run_info] = stage1_run_zhou_s2_baseline( ...
    struct('dry_run', true, 'save_output', false));

verifyEmpty(test_case, result);
verifyEqual(test_case, run_info.status, "ready");
verifyEqual(test_case, run_info.scenario_id, "s2");
verifyEqual(test_case, run_info.data_year, 2022);
verifyEqual(test_case, run_info.renewable_time_count, 8760);
verifyEqual(test_case, run_info.params.AEL.common.max_power, 130e3);
verifyTrue(test_case, run_info.params.AEL.common.startup);
verifyTrue(test_case, run_info.protocol_valid);
verifyTrue(test_case, run_info.manifest_valid);
verifyEqual(test_case, run_info.output_path, "");
end

function testStage1RejectsSevenDayDebugOptions(test_case)
config = struct();
config.dry_run = true;
config.data = struct('day_count', 7);

verifyError(test_case, @() stage1_run_zhou_s2_baseline(config), ...
    'load_res_year:removed_debug_option');
end

function testStage3DryRunBuildsExistingAssetContractCapacityPlan(test_case)
mat_path = [tempname, '.mat'];
cleanup = onCleanup(@() delete_if_file(mat_path));

params = my_system('s2');
params.AEL.common.startup = true;
renewable_data = struct();
renewable_data.time_count = params.time.hour_year;
renewable_data.pv_power_kw = zeros(params.time.hour_year, 1);
renewable_data.pw_power_kw = zeros(params.time.hour_year, 1);

result = struct();
result.summary = struct('NH3_prod_t_y', 123.456, ...
    'lcoa', 1, 'net_profit', 2);
result.dispatch = struct('NH3_prod', ...
    123.456 * 1000 / params.time.hour_year ...
    * ones(params.time.hour_year, 1));
result.sol = synthetic_stage1_solution(params.time.hour_year);
run_info = struct('status', "solved", ...
    'model_variant', "synthetic_stage1", ...
    'data_year', 2099);
save(mat_path, 'result', 'run_info', 'params', 'renewable_data');

[stage3_result, stage3_run_info, metrics] = ...
    stage3_run_v51_contract_closed_loop(struct( ...
    'dry_run', true, ...
    'save_output', false, ...
    'candidate_annual_t', 120, ...
    'max_time_seconds', 11, ...
    'stage1_mat_path', mat_path));

verifyEmpty(test_case, stage3_result);
verifyEmpty(test_case, metrics);
verifyEqual(test_case, stage3_run_info.status, "ready");
verifyEqual(test_case, stage3_run_info.model_variant, ...
    "Zhou_S2_v51_fixed_contract_search");
verifyEqual(test_case, stage3_run_info.contract.reference_annual_t, ...
    123.456, 'AbsTol', 1e-12);
verifyEqual(test_case, stage3_run_info.contract.quantity_source, ...
    "fixed_outer_search_candidate");
verifyEqual(test_case, stage3_run_info.contract.candidate_annual_t, 120, ...
    'AbsTol', 1e-12);
verifyEqual(test_case, stage3_run_info.contract.candidate_daily_kg, ...
    120 * 1000 / 365, 'AbsTol', 1e-9);
verifyEqual(test_case, stage3_run_info.contract.objective_method, ...
    "fixed_contract_feasibility_with_economic_inner_objective");
verifyEqual(test_case, ...
    stage3_run_info.contract.search.candidates_annual_t, ...
    [70e3; 73e3; 123.456]);
verifyEqual(test_case, stage3_run_info.contract.max_delay_days, 7);
verifyTrue(test_case, stage3_run_info.contract.no_early_delivery_credit);
verifyEqual(test_case, stage3_run_info.contract.lcoa_cap_usd_per_t, 1.02, ...
    'AbsTol', 1e-12);
verifyTrue(test_case, stage3_run_info.contract.warm_start.available);
verifyEqual(test_case, ...
    stage3_run_info.contract.warm_start.daily_quantity_kg, ...
    120 * 1000 / 365, 'AbsTol', 1e-6);
verifyTrue(test_case, ...
    stage3_run_info.contract.warm_start.is_contract_feasible);
verifyEqual(test_case, ...
    stage3_run_info.contract.economic_relative_gap_tolerance, 1e-4);
verifyEqual(test_case, stage3_run_info.solver_max_time_seconds, 11);
verifyEqual(test_case, stage3_run_info.solver_phase_count, 1);
verifyEqual(test_case, stage3_run_info.output_path, "");
end

function testStage4H2ReserveGridDryRunBuildsCandidateTable(test_case)
[grid_table, run_info] = stage4_run_v51_h2_reserve_grid(struct( ...
    'dry_run', true, ...
    'save_output', false, ...
    'include_baseline', false, ...
    'reserve_quantiles', [0.50, 0.75], ...
    'reserve_lookahead_days', [1, 3]));

verifyEqual(test_case, height(grid_table), 4);
verifyEqual(test_case, run_info.status, "completed");
verifyEqual(test_case, unique(grid_table.status), "planned");
verifyEqual(test_case, grid_table.case_id, ...
    ["h2q050_l1"; "h2q050_l3"; "h2q075_l1"; "h2q075_l3"]);
verifyEqual(test_case, grid_table.h2_reserve_quantile, ...
    [0.50; 0.50; 0.75; 0.75], 'AbsTol', 1e-12);
verifyEqual(test_case, grid_table.h2_reserve_lookahead_days, ...
    [1; 3; 1; 3]);
end

function testStage5JointGridDryRunBuildsCandidateTable(test_case)
[grid_table, run_info] = stage5_run_v51_joint_grid(struct( ...
    'dry_run', true, ...
    'save_output', false, ...
    'include_baseline', false, ...
    'reserve_quantiles', [0, 0.75], ...
    'reserve_lookahead_days', [1, 3], ...
    'contract_pacing_aggressiveness', [0, 0.50], ...
    'hb_smoothing_reduction_fraction', [0, 0.10]));

verifyEqual(test_case, height(grid_table), 12);
verifyEqual(test_case, run_info.status, "completed");
verifyEqual(test_case, unique(grid_table.status), "planned");
verifyEqual(test_case, grid_table.case_id(1), ...
    "joint_h2q000_l0_cp000_hb000");
verifyEqual(test_case, grid_table.case_id(end), ...
    "joint_h2q075_l3_cp050_hb010");
verifyEqual(test_case, grid_table.contract_pacing_aggressiveness( ...
    [1, 2, 11, 12]), [0; 0; 0.50; 0.50], 'AbsTol', 1e-12);
verifyEqual(test_case, grid_table.hb_smoothing_reduction_fraction( ...
    [1, 2, 11, 12]), [0; 0.10; 0; 0.10], 'AbsTol', 1e-12);
verifyEqual(test_case, run_info.h2_reserve_gate_mode, ...
    "contract_carbon_state_gate");
verifyTrue(test_case, run_info.h2_reserve_soft);
verifyTrue(test_case, run_info.allow_infeasible_continuation);
verifyTrue(test_case, all(grid_table.h2_reserve_soft));
end

function testRollingDispatchDryRunBuildsJointSettings(test_case)
mat_path = [tempname, '.mat'];
cleanup = onCleanup(@() delete_if_file(mat_path));

params = my_system('s2');
hour_count = 72;
renewable_data = struct( ...
    'time', datetime(2022, 1, 1, 0, 0, 0) ...
        + hours((0:hour_count - 1)'), ...
    'time_count', hour_count, ...
    'pv_power_kw', zeros(hour_count, 1), ...
    'pw_power_kw', zeros(hour_count, 1));
run_info = struct('status', "synthetic", 'data_year', 2022);
save(mat_path, 'params', 'renewable_data', 'run_info');

[result, dry_info, metrics] = rolling_dispatch(struct( ...
    'source_mat_path', mat_path, ...
    'scheme', "contract_plan_and_hb_smoothing", ...
    'forecast_mode', "observed_oracle", ...
    'h2_reserve_quantile', 0.75, ...
    'h2_reserve_lookahead_days', 3, ...
    'h2_reserve_soft', true, ...
    'h2_reserve_gate_mode', "contract_carbon_state_gate", ...
    'contract_pacing_aggressiveness', 0.50, ...
    'hb_smoothing_reduction_fraction', 0.10, ...
    'dry_run', true, ...
    'save_output', false));

verifyEmpty(test_case, result);
verifyEmpty(test_case, metrics);
verifyEqual(test_case, dry_info.status, "ready");
verifyEqual(test_case, dry_info.joint.contract_pacing_aggressiveness, ...
    0.50, 'AbsTol', 1e-12);
verifyEqual(test_case, dry_info.joint.hb_smoothing_reduction_fraction, ...
    0.10, 'AbsTol', 1e-12);
verifyEqual(test_case, dry_info.joint.effective_hb_ramp_rate, ...
    params.HB.ramp_rate * 0.90, 'AbsTol', 1e-12);
verifyEqual(test_case, dry_info.first_production.pacing_aggressiveness, ...
    0.50, 'AbsTol', 1e-12);
verifyEqual(test_case, dry_info.first_h2_reserve_gate.mode, ...
    "contract_carbon_state_gate");
verifyTrue(test_case, dry_info.first_h2_reserve.soft);
end

function testStage5JointGridDryRunCanDisableContinuation(test_case)
[~, run_info] = stage5_run_v51_joint_grid(struct( ...
    'dry_run', true, ...
    'save_output', false, ...
    'include_baseline', false, ...
    'candidate_limit', 1, ...
    'allow_infeasible_continuation', false));

verifyFalse(test_case, run_info.allow_infeasible_continuation);
end

function testBaselineFixedContractModeUsesNoNewEquipment(test_case)
params = my_system('s2');
params.AEL.common.startup = false;
params.environment.co2_enabled = false;

hour_count = 48;
hourly_h2_use_kg = params.HB.max_load * params.HB.nh3_output ...
    * params.HB.lit_h2;
steady_ael_kw = hourly_h2_use_kg * params.AEL.common.spec_energy ...
    / params.unit.h2_density;
steady_hb_kw = params.HB.max_load * params.HB.nom_power * 1000;
renewable_data = struct();
renewable_data.time_count = hour_count;
renewable_data.pv_power_kw = ...
    (steady_ael_kw + steady_hb_kw) / params.renewable.input_scale ...
    * ones(hour_count, 1);
renewable_data.pw_power_kw = zeros(hour_count, 1);

daily_upper_kg = params.HB.max_load * params.HB.nh3_output * 24;
options = struct();
options.verbose = false;
options.solver_display = 'none';
options.max_time_seconds = 30;
options.relative_gap_tolerance = 1e-8;
initial_solution = synthetic_stage1_solution(hour_count);
initial_solution = rmfield(initial_solution, 'P_AEL_start');
online_modules = ceil(steady_ael_kw / params.AEL.common.module_power);
initial_solution.HB_load(:) = params.HB.max_load;
initial_solution.P_AEL(:) = steady_ael_kw;
initial_solution.n_ael(:) = online_modules;
initial_solution.SU_AEL(1) = online_modules;
initial_solution.I_AEL_up(:) = 1;
storage_limits = h2_storage_limits( ...
    params.h2_storage, params.unit.h2_density);
initial_solution.storage_H2(:) = storage_limits.initial_mass;
initial_solution.contract_backlog = zeros(hour_count / 24 + 1, 1);
options.initial_solution = initial_solution;
options.contract = struct( ...
    'enabled', true, ...
    'max_delay_days', 7, ...
    'fixed_daily_quantity_kg', daily_upper_kg, ...
    'daily_quantity_upper_kg', daily_upper_kg, ...
    'lcoa_cap_usd_per_t', []);

result = baseline(params, renewable_data, options);

verifyEqual(test_case, result.contract.daily_quantity_kg, ...
    daily_upper_kg, 'AbsTol', 0.1);
verifyLessThanOrEqual(test_case, result.contract.maximum_backlog_kg, ...
    7 * result.contract.daily_quantity_kg + 1e-3);
verifyEqual(test_case, result.contract.terminal_backlog_kg, 0, ...
    'AbsTol', 1e-3);
verifyTrue(test_case, result.contract.no_early_delivery_credit);
verifyEqual(test_case, params.h2_storage.capacity, 11e4);
verifyEqual(test_case, result.contract.quantity_source, ...
    "fixed_outer_search_candidate");
verifyEqual(test_case, result.optimization.mode, ...
    'fixed_contract_economic_feasibility');
verifyTrue(test_case, result.optimization.initial_solution_supplied);
verifyTrue(test_case, result.optimization.capacity_feasible);
verifyTrue(test_case, result.optimization.economic_objective_converged);
end

function testDispatchModelBuildsReusableAnnualProblem(test_case)
params = my_system('s2');
params.AEL.common.startup = false;
params.environment.co2_enabled = false;

renewable_data = struct();
renewable_data.time_count = 48;
renewable_data.pv_power_kw = 50e3 * ones(48, 1);
renewable_data.pw_power_kw = 25e3 * ones(48, 1);

model = dispatch_model(params, renewable_data, struct());

verifyClass(test_case, model.problem, 'optim.problemdef.OptimizationProblem');
verifyEqual(test_case, model.mode, "annual");
verifyEqual(test_case, model.context.T, 48);
verifyEqual(test_case, model.context.dt, params.time.step);
verifyTrue(test_case, isfield(model.variables, 'P_AEL'));
verifyTrue(test_case, isfield(model.variables, 'HB_load'));
verifyTrue(test_case, isfield(model.variables, 'storage_H2'));
verifyFalse(test_case, model.contract.enabled);
verifyEqual(test_case, model.initial_state.ael_online_modules, 0);
end

function testDispatchModelKeepsAnnualCarbonLimit(test_case)
params = my_system('s2');
params.AEL.common.startup = false;
renewable_data = struct( ...
    'time_count', 24, ...
    'pv_power_kw', 50e3 * ones(24, 1), ...
    'pw_power_kw', 25e3 * ones(24, 1));

model = dispatch_model(params, renewable_data, struct());

verifyEqual(test_case, model.carbon.accounting, "annual_horizon");
verifyTrue(test_case, isfield(model.problem.Constraints, 'co2_limit'));
verifyFalse(test_case, isfield(model.problem.Constraints, ...
    'co2_annual_reachability'));
end

function testDispatchModelRequiresRollingCarbonState(test_case)
params = my_system('s2');
params.AEL.common.startup = false;
renewable_data = struct( ...
    'time_count', 24, ...
    'pv_power_kw', 50e3 * ones(24, 1), ...
    'pw_power_kw', 25e3 * ones(24, 1));
options = struct( ...
    'mode', "realtime", ...
    'terminal', struct('h2_equal_kg', [], 'h2_min_kg', []));

verifyError(test_case, @() dispatch_model( ...
    params, renewable_data, options), ...
    'dispatch_model:missing_carbon_state');
end

function testDispatchModelBuildsCumulativeCarbonReachability(test_case)
params = my_system('s2');
params.AEL.common.startup = false;
renewable_data = struct( ...
    'time_count', 48, ...
    'pv_power_kw', 50e3 * ones(48, 1), ...
    'pw_power_kw', 25e3 * ones(48, 1));
options = struct( ...
    'mode', "day_ahead", ...
    'terminal', struct('h2_equal_kg', [], 'h2_min_kg', []), ...
    'carbon', struct( ...
        'accounting', "annual_cumulative_reachability", ...
        'initial_emissions_kg', 120e3, ...
        'initial_nh3_kg', 200e3, ...
        'remaining_reference_nh3_kg', 300e3, ...
        'reference_nh3_per_step_kg', 10e3, ...
        'checkpoint_interval_steps', 24, ...
        'commit_reserve_kg', 100e3, ...
        'commit_steps', 24), ...
    'grid_budget', struct( ...
        'accounting', "annual_cumulative_reachability", ...
        'initial_sell_kwh', 20e3, ...
        'initial_curtail_kwh', 10e3, ...
        'initial_renewable_kwh', 100e3, ...
        'remaining_max_renewable_kwh', 400e3, ...
        'max_renewable_per_step_kwh', 200e3, ...
        'checkpoint_interval_steps', 24));

model = dispatch_model(params, renewable_data, options);

verifyEqual(test_case, model.carbon.accounting, ...
    "annual_cumulative_reachability");
verifyEqual(test_case, model.carbon.initial_emissions_kg, 120e3);
verifyEqual(test_case, model.carbon.initial_nh3_kg, 200e3);
verifyEqual(test_case, model.carbon.remaining_reference_nh3_kg, 300e3);
verifyEqual(test_case, model.carbon.commit_reserve_kg, 100e3);
verifyEqual(test_case, model.carbon.commit_steps, 24);
verifyFalse(test_case, model.carbon.is_year_end);
verifyTrue(test_case, isfield(model.problem.Constraints, ...
    'co2_annual_reachability'));
verifyTrue(test_case, isfield(model.problem.Constraints, ...
    'co2_annual_checkpoints'));
verifyTrue(test_case, isfield(model.problem.Constraints, ...
    'sell_annual_checkpoints'));
verifyTrue(test_case, isfield(model.problem.Constraints, ...
    'curtail_annual_checkpoints'));
verifyFalse(test_case, isfield(model.problem.Constraints, 'co2_limit'));
verifyTrue(test_case, isfield(model.expressions, ...
    'carbon_debt_after_horizon_kg'));

options.carbon.remaining_reference_nh3_kg = 0;
terminal_model = dispatch_model(params, renewable_data, options);
verifyTrue(test_case, terminal_model.carbon.is_year_end);
end

function testDispatchModelBuildsCommitProductionFloor(test_case)
params = my_system('s2');
params.AEL.common.startup = false;
params.environment.co2_enabled = false;
renewable_data = struct( ...
    'time_count', 48, ...
    'pv_power_kw', 50e3 * ones(48, 1), ...
    'pw_power_kw', 25e3 * ones(48, 1));
options = struct( ...
    'mode', "day_ahead", ...
    'terminal', struct('h2_equal_kg', [], 'h2_min_kg', []), ...
    'production', struct( ...
        'commit_steps', 24, ...
        'commit_min_nh3_kg', 200e3));

model = dispatch_model(params, renewable_data, options);

verifyEqual(test_case, model.production.commit_steps, 24);
verifyEqual(test_case, model.production.commit_min_nh3_kg, 200e3);
verifyTrue(test_case, isfield(model.problem.Constraints, ...
    'production_commit_min'));
verifyTrue(test_case, isfield(model.expressions, ...
    'commit_nh3_kg'));
end

function testDispatchModelBuildsCommitHydrogenFloor(test_case)
params = my_system('s2');
params.AEL.common.startup = false;
params.environment.co2_enabled = false;
storage_limits = h2_storage_limits( ...
    params.h2_storage, params.unit.h2_density);
renewable_data = struct( ...
    'time_count', 48, ...
    'pv_power_kw', 50e3 * ones(48, 1), ...
    'pw_power_kw', 25e3 * ones(48, 1));
options = struct( ...
    'mode', "day_ahead", ...
    'terminal', struct( ...
        'h2_equal_kg', [], ...
        'h2_min_kg', [], ...
        'commit_steps', 24, ...
        'h2_commit_min_kg', storage_limits.initial_mass));

model = dispatch_model(params, renewable_data, options);

verifyEqual(test_case, model.terminal.commit_steps, 24);
verifyEqual(test_case, model.terminal.h2_commit_min_kg, ...
    storage_limits.initial_mass, 'AbsTol', 1e-9);
verifyTrue(test_case, isfield(model.problem.Constraints, ...
    'H2_commit_min'));
end

function testDispatchModelBuildsHourlyHydrogenReserveFloor(test_case)
params = my_system('s2');
params.AEL.common.startup = false;
params.environment.co2_enabled = false;
storage_limits = h2_storage_limits( ...
    params.h2_storage, params.unit.h2_density);
renewable_data = struct( ...
    'time_count', 48, ...
    'pv_power_kw', 50e3 * ones(48, 1), ...
    'pw_power_kw', 25e3 * ones(48, 1));
reserve_floor_kg = storage_limits.min_mass ...
    + 0.10 * storage_limits.work_mass * ones(48, 1);
options = struct( ...
    'mode', "day_ahead", ...
    'terminal', struct('h2_equal_kg', [], 'h2_min_kg', []), ...
    'hydrogen', struct( ...
        'min_storage_kg_by_step', reserve_floor_kg));

model = dispatch_model(params, renewable_data, options);

verifyEqual(test_case, model.hydrogen.min_storage_kg_by_step, ...
    reserve_floor_kg, 'AbsTol', 1e-9);
verifyTrue(test_case, isfield(model.problem.Constraints, ...
    'H2_reserve_floor'));
end

function testDispatchModelBuildsSoftHydrogenReserveFloor(test_case)
params = my_system('s2');
params.AEL.common.startup = false;
params.environment.co2_enabled = false;
storage_limits = h2_storage_limits( ...
    params.h2_storage, params.unit.h2_density);
renewable_data = struct( ...
    'time_count', 48, ...
    'pv_power_kw', zeros(48, 1), ...
    'pw_power_kw', zeros(48, 1));
reserve_floor_kg = storage_limits.min_mass ...
    + 0.50 * storage_limits.work_mass * ones(48, 1);
options = struct( ...
    'mode', "day_ahead", ...
    'terminal', struct('h2_equal_kg', [], 'h2_min_kg', []), ...
    'hydrogen', struct( ...
        'min_storage_kg_by_step', reserve_floor_kg, ...
        'reserve_floor_soft', true, ...
        'reserve_slack_penalty_usd_per_kg', 100));

model = dispatch_model(params, renewable_data, options);

verifyTrue(test_case, model.hydrogen.reserve_floor_soft);
verifyEqual(test_case, model.hydrogen.reserve_slack_penalty_usd_per_kg, ...
    100, 'AbsTol', 1e-12);
verifyTrue(test_case, isfield(model.variables, 'H2_reserve_slack'));
verifyTrue(test_case, isfield(model.expressions, 'h2_reserve_slack_kg'));
end

function testDispatchModelBuildsFeasibilityRestorationSlacks(test_case)
params = my_system('s2');
params.AEL.common.startup = false;
storage_limits = h2_storage_limits( ...
    params.h2_storage, params.unit.h2_density);
renewable_data = struct( ...
    'time_count', 24, ...
    'pv_power_kw', zeros(24, 1), ...
    'pw_power_kw', zeros(24, 1));
options = struct( ...
    'mode', "day_ahead", ...
    'terminal', struct( ...
        'h2_equal_kg', storage_limits.initial_mass, ...
        'h2_min_kg', [], ...
        'commit_steps', 24, ...
        'h2_commit_min_kg', storage_limits.initial_mass), ...
    'carbon', struct( ...
        'accounting', "annual_cumulative_reachability", ...
        'initial_emissions_kg', 0, ...
        'initial_nh3_kg', 0, ...
        'remaining_reference_nh3_kg', 0, ...
        'reference_nh3_per_step_kg', 0, ...
        'checkpoint_interval_steps', 24, ...
        'commit_reserve_kg', 0, ...
        'commit_steps', 24), ...
    'production', struct( ...
        'commit_steps', 24, ...
        'commit_min_nh3_kg', 1e6), ...
    'restoration', struct('enabled', true));

model = dispatch_model(params, renewable_data, options);

verifyTrue(test_case, model.restoration.enabled);
verifyTrue(test_case, isfield(model.variables, ...
    'production_commit_slack_kg'));
verifyTrue(test_case, isfield(model.variables, 'carbon_slack_kg'));
verifyTrue(test_case, isfield(model.variables, ...
    'H2_terminal_shortfall_kg'));
verifyTrue(test_case, isfield(model.variables, ...
    'H2_terminal_surplus_kg'));
verifyTrue(test_case, isfield(model.variables, 'H2_commit_slack_kg'));
verifyTrue(test_case, isfield(model.expressions, ...
    'restoration_slack_kg'));
end

function testDispatchModelBuildsStrictContractCohorts(test_case)
params = my_system('s2');
params.AEL.common.startup = false;
params.environment.co2_enabled = false;
storage_limits = h2_storage_limits( ...
    params.h2_storage, params.unit.h2_density);

renewable_data = struct();
renewable_data.time_count = 72;
renewable_data.pv_power_kw = 50e3 * ones(72, 1);
renewable_data.pw_power_kw = 25e3 * ones(72, 1);

daily_contract_kg = 100e3;
options = struct( ...
    'mode', "day_ahead", ...
    'include_annual_fixed_cost', false, ...
    'terminal', struct('h2_equal_kg', [], ...
        'h2_min_kg', storage_limits.initial_mass), ...
    'contract', struct( ...
        'enabled', true, ...
        'strict_delivery', true, ...
        'terminal_clear', false, ...
        'max_delay_days', 7, ...
        'fixed_daily_quantity_kg', daily_contract_kg, ...
        'initial_cohorts_kg', [zeros(6, 1); daily_contract_kg], ...
        'lcoa_cap_usd_per_t', []));

model = dispatch_model(params, renewable_data, options);

verifyTrue(test_case, model.contract.strict_delivery);
verifyFalse(test_case, model.contract.terminal_clear);
verifyEqual(test_case, model.contract.initial_cohorts_kg, ...
    [zeros(6, 1); daily_contract_kg]);
verifyTrue(test_case, isfield(model.variables, 'contract_delivery'));
verifyFalse(test_case, isfield(model.variables, 'contract_backlog'));
verifyEqual(test_case, size(model.variables.contract_delivery), [10, 8]);
verifyEqual(test_case, model.contract.obligation_due_day(7), -6);
verifyEqual(test_case, model.contract.delivery_day(7, 8), 1);
verifyTrue(test_case, model.contract.must_clear_in_horizon(7));
verifyFalse(test_case, model.contract.must_clear_in_horizon(end));
verifyTrue(test_case, isfield(model.problem.Constraints, 'H2_terminal_min'));
verifyFalse(test_case, isfield(model.problem.Constraints, 'H2_terminal'));
end

function testRollingDispatchClosesThreeDaySyntheticLoop(test_case)
mat_path = [tempname, '.mat'];
cleanup = onCleanup(@() delete_if_file(mat_path));

params = my_system('s2');
params.AEL.common.startup = false;
params.environment.co2_enabled = true;
subprotocol = protocol_v5('v5_1');
daily_contract_kg = subprotocol.Contract.DailyQuantityKG;
hb_load = daily_contract_kg / (params.HB.nh3_output * 24);
hourly_h2_use_kg = hb_load * params.HB.nh3_output * params.HB.lit_h2;
steady_ael_kw = hourly_h2_use_kg * params.AEL.common.spec_energy ...
    / params.unit.h2_density;
steady_hb_kw = hb_load * params.HB.nom_power * 1000;
raw_renewable_kw = (steady_ael_kw + steady_hb_kw) ...
    / params.renewable.input_scale;

hour_count = 72;
renewable_data = struct();
renewable_data.time = datetime(2099, 1, 1, 0, 0, 0) ...
    + hours((0:hour_count - 1)');
renewable_data.time_count = hour_count;
renewable_data.pv_power_kw = ...
    0.5 * raw_renewable_kw * ones(hour_count, 1);
renewable_data.pw_power_kw = ...
    0.5 * raw_renewable_kw * ones(hour_count, 1);
run_info = struct('status', "synthetic", 'data_year', 2099);
save(mat_path, 'params', 'renewable_data', 'run_info');

[fallback_pv, fallback_pw] = deal( ...
    renewable_data.pv_power_kw(1:24), ...
    renewable_data.pw_power_kw(1:24));
[result, closed_loop_info, metrics] = rolling_dispatch(struct( ...
    'source_mat_path', mat_path, ...
    'scheme', "contract_plan_and_hb_smoothing", ...
    'forecast_mode', "simulated_persistence", ...
    'forecast_fallback', struct( ...
        'source_years', [2022, 2023], ...
        'pv_power_kw', fallback_pv, ...
        'pw_power_kw', fallback_pw), ...
    'save_output', false, ...
    'verbose', false, ...
    'solver_display', 'none', ...
    'max_time_seconds_per_solve', 30, ...
    'relative_gap_tolerance', 1e-6));

verifyEqual(test_case, closed_loop_info.status, "completed");
verifyEqual(test_case, closed_loop_info.protocol_version, "5.1.37");
verifyEqual(test_case, closed_loop_info.protocol_seal, "000CDCA8");
verifyEqual(test_case, closed_loop_info.day_count, 3);
verifyEqual(test_case, numel(result.dispatch.HB_load), hour_count);
verifyEqual(test_case, numel(result.day_ahead.HB_load), hour_count);
verifyEqual(test_case, result.storage.H2(end), result.storage.H2(1), ...
    'AbsTol', 1e-3);
verifyLessThanOrEqual(test_case, ...
    result.check.max_power_residual_kw, 1e-5);
verifyLessThanOrEqual(test_case, ...
    result.check.max_storage_residual_kg, 1e-5);
verifyEqual(test_case, metrics.Contract.late_cohort_count, 0);
verifyEqual(test_case, metrics.Contract.unserved_cohort_count, 0);
verifyTrue(test_case, metrics.Feasibility.strict_delivery_ok);
verifyTrue(test_case, metrics.Feasibility.annual_co2_ok);
verifyTrue(test_case, metrics.Feasibility.annual_sell_ok);
verifyTrue(test_case, metrics.Feasibility.annual_curtail_ok);
verifyEqual(test_case, closed_loop_info.carbon_accounting, ...
    "annual_cumulative_reachability");
verifyEqual(test_case, closed_loop_info.grid_accounting, ...
    "annual_cumulative_observed_budget");
verifyEqual(test_case, closed_loop_info.final_carbon_emissions_kg, ...
    params.environment.grid_co2 * result.summary.purchase_kwh, ...
    'AbsTol', 1e-6);
verifyEqual(test_case, closed_loop_info.final_nh3_kg, ...
    result.summary.NH3_prod_kg, 'AbsTol', 1e-6);
verifyLessThanOrEqual(test_case, ...
    closed_loop_info.final_carbon_debt_kg, 1e-3);
verifyEqual(test_case, closed_loop_info.output_path, "");
end

function testRollingDispatchAcceptsFrozenForecastTableSchema(test_case)
mat_path = [tempname, '.mat'];
cleanup = onCleanup(@() delete_if_file(mat_path));

params = my_system('s2');
hour_count = 72;
start_time = datetime(2099, 1, 1, 0, 0, 0, 'TimeZone', 'UTC');
renewable_data = struct( ...
    'time', start_time + hours((0:hour_count - 1)'), ...
    'time_count', hour_count, ...
    'pv_power_kw', zeros(hour_count, 1), ...
    'pw_power_kw', zeros(hour_count, 1));
run_info = struct('status', "synthetic", 'data_year', 2099);
save(mat_path, 'params', 'renewable_data', 'run_info');

issue_time_utc = repmat(start_time, hour_count, 1);
target_time_utc = start_time + hours((1:hour_count)');
horizon_hour = (1:hour_count)';
pv_power_kw = zeros(hour_count, 1);
pw_power_kw = zeros(hour_count, 1);
pv_capacity_kw = 200e3 * ones(hour_count, 1);
pw_capacity_kw = 200e3 * ones(hour_count, 1);
source_id = repmat("synthetic_schema", hour_count, 1);
forecast_table = table(issue_time_utc, target_time_utc, horizon_hour, ...
    pv_power_kw, pw_power_kw, pv_capacity_kw, pw_capacity_kw, source_id);

[result, dry_info, metrics] = rolling_dispatch(struct( ...
    'source_mat_path', mat_path, ...
    'forecast_mode', "table", ...
    'forecast_table', forecast_table, ...
    'dry_run', true, ...
    'save_output', false));

verifyEmpty(test_case, result);
verifyEmpty(test_case, metrics);
verifyEqual(test_case, dry_info.status, "ready");
verifyEqual(test_case, dry_info.first_forecast_hour_count, 72);
verifyEqual(test_case, dry_info.output_path, "");
end

function testRollingDispatchDryRunBuildsH2ReserveFloor(test_case)
mat_path = [tempname, '.mat'];
cleanup = onCleanup(@() delete_if_file(mat_path));

params = my_system('s2');
hour_count = 72;
renewable_data = struct( ...
    'time', datetime(2022, 1, 1, 0, 0, 0) ...
        + hours((0:hour_count - 1)'), ...
    'time_count', hour_count, ...
    'pv_power_kw', zeros(hour_count, 1), ...
    'pw_power_kw', zeros(hour_count, 1));
run_info = struct('status', "synthetic", 'data_year', 2022);
save(mat_path, 'params', 'renewable_data', 'run_info');

[result, dry_info, metrics] = rolling_dispatch(struct( ...
    'source_mat_path', mat_path, ...
    'scheme', "contract_plan_and_hb_smoothing", ...
    'forecast_mode', "observed_oracle", ...
    'h2_reserve_quantile', 0.95, ...
    'h2_reserve_lookahead_days', 2, ...
    'dry_run', true, ...
    'save_output', false));

storage_limits = h2_storage_limits( ...
    params.h2_storage, params.unit.h2_density);
verifyEmpty(test_case, result);
verifyEmpty(test_case, metrics);
verifyEqual(test_case, dry_info.status, "ready");
verifyTrue(test_case, dry_info.h2_reserve.active);
verifyEqual(test_case, dry_info.h2_reserve.quantile, 0.95);
verifyEqual(test_case, dry_info.h2_reserve.lookahead_days, 2);
verifyEqual(test_case, dry_info.first_h2_reserve.target_min_kg, ...
    storage_limits.initial_mass, 'AbsTol', 1e-9);
verifyEqual(test_case, ...
    dry_info.first_h2_reserve.surplus_charge_cap_kg, 0, ...
    'AbsTol', 1e-9);
verifyTrue(test_case, dry_info.first_h2_reserve.renewable_capped);
verifyGreaterThan(test_case, ...
    dry_info.first_h2_reserve.deficit_quantile_kg, ...
    storage_limits.work_mass);
end

function testRollingDispatchRejectsTargetYearFallbackFitting(test_case)
mat_path = [tempname, '.mat'];
cleanup = onCleanup(@() delete_if_file(mat_path));

params = my_system('s2');
hour_count = 72;
renewable_data = struct( ...
    'time', datetime(2024, 1, 1, 0, 0, 0) + hours((0:hour_count - 1)'), ...
    'time_count', hour_count, ...
    'pv_power_kw', zeros(hour_count, 1), ...
    'pw_power_kw', zeros(hour_count, 1));
run_info = struct('status', "synthetic", 'data_year', 2024);
save(mat_path, 'params', 'renewable_data', 'run_info');

base_config = struct( ...
    'source_mat_path', mat_path, ...
    'forecast_mode', "simulated_persistence", ...
    'dry_run', true, ...
    'save_output', false);
verifyError(test_case, @() rolling_dispatch(base_config), ...
    'rolling_dispatch:missing_development_fallback');

base_config.forecast_fallback = struct( ...
    'source_years', [2023, 2024], ...
    'pv_power_kw', zeros(24, 1), ...
    'pw_power_kw', zeros(24, 1));
verifyError(test_case, @() rolling_dispatch(base_config), ...
    'rolling_dispatch:bad_forecast_fallback');

base_config.forecast_fallback = struct( ...
    'source_years', [2022, 2023], ...
    'pv_power_kw', zeros(24, 1), ...
    'pw_power_kw', zeros(24, 1));
[~, dry_info] = rolling_dispatch(base_config);
verifyEqual(test_case, dry_info.status, "ready");
verifyEqual(test_case, dry_info.forecast_fallback_source, ...
    "external_development_years_2022_2023");
end

function sol = synthetic_stage1_solution(hour_count)
sol = struct( ...
    'HB_load', zeros(hour_count, 1), ...
    'I_AEL_up', zeros(hour_count, 1), ...
    'P_AEL', zeros(hour_count, 1), ...
    'SD_AEL', zeros(hour_count, 1), ...
    'SU_AEL', zeros(hour_count, 1), ...
    'n_ael', zeros(hour_count, 1), ...
    'p_curt', zeros(hour_count, 1), ...
    'p_purchase', zeros(hour_count, 1), ...
    'p_sell', zeros(hour_count, 1), ...
    'storage_H2', zeros(hour_count + 1, 1), ...
    'u_purchase', zeros(hour_count, 1), ...
    'P_AEL_start', zeros(hour_count, 1));
end

function delete_if_file(file_path)
if isfile(file_path)
    delete(file_path);
end
end
