function tests = test_protocol_v5
tests = functiontests(localfunctions);
end

function setupOnce(test_case)
test_dir = fileparts(mfilename('fullpath'));
project_dir = fileparts(test_dir);
test_case.TestData.project_dir = project_dir;
addpath(fullfile(project_dir, 'src', 'utils'), '-begin');
setup_project_paths(project_dir);
end

function testProtocolStatesItsResultInformedTiming(test_case)
protocol = protocol_v5();

verifyEqual(test_case, protocol.ProtocolVersion, "5.0.0");
verifyEqual(test_case, protocol.FreezeStage, ...
    "research_boundary_and_s2_baseline");
verifyEqual(test_case, protocol.Classification, ...
    "result_informed_prospective_boundary_protocol");
verifyTrue(test_case, protocol.EvidenceAudit.V4SelectionResultsInspected);
verifyTrue(test_case, protocol.EvidenceAudit.S2Dispatch2022Inspected);
verifyFalse(test_case, protocol.EvidenceAudit.NewForecastResultsInspected);
verifyFalse(test_case, protocol.EvidenceAudit.NewSchedulingResultsInspected);
verifyFalse(test_case, protocol.EvidenceAudit.IsFullyOutcomeBlind);
verifyTrue(test_case, protocol.EvidenceAudit.IsProspectiveForNewContribution);
end

function testHoldoutLimitationsAreDisclosed(test_case)
protocol = protocol_v5();

verifyEqual(test_case, protocol.Data.HoldoutYear, 2025);
verifyEqual(test_case, protocol.Data.HoldoutStatus, ...
    "analysis_locked_not_strictly_blind");
verifyFalse(test_case, protocol.Data.StrictHoldoutBlinding);
verifyTrue(test_case, protocol.Data.LimitedRawHoldoutExposureDisclosed);
verifyFalse(test_case, protocol.Data.HoldoutUsedForMetricSelection);
verifyTrue(test_case, protocol.Data.ExternalConfirmationRequired);
end

function testMetricOriginsAndRolesAreFrozen(test_case)
protocol = protocol_v5();
registry = protocol.OutcomeRegistry;

contract_row = registry([registry.Name] == "contract_shortfall_p95");
verifyEqual(test_case, contract_row.Role, "primary_outcome");
verifyEqual(test_case, contract_row.Origin, ...
    "mechanism_defined_after_baseline_diagnosis");

mar_row = registry([registry.Name] == "mar");
verifyEqual(test_case, mar_row.Role, "primary_outcome");
verifyEqual(test_case, mar_row.Origin, ...
    "v4_data_selected_result_informed");

legacy_row = registry([registry.Name] == "daily_shortfall_p95");
verifyEqual(test_case, legacy_row.Role, "legacy_descriptive_outcome");
verifyEqual(test_case, legacy_row.Interpretation, ...
    "lower_tail_balance_not_contract_violation");

switch_row = registry([registry.Name] == "switch_count");
verifyEqual(test_case, switch_row.Role, "excluded_for_s2");
verifyEqual(test_case, switch_row.Interpretation, ...
    "structurally_non_identifiable_hb_always_online");
end

function testKnownBaselineResultsCannotBecomeAcceptanceThresholds(test_case)
protocol = protocol_v5();
observation = protocol.KnownS2Observation2022;

verifyEqual(test_case, observation.Status, ...
    "descriptive_known_before_v5_freeze");
verifyFalse(test_case, observation.UseAsAcceptanceThreshold);
verifyFalse(test_case, observation.UseForParameterTuningAfterFreeze);
verifyEqual(test_case, observation.NH3ProductionTPerYear, 7.602e4, ...
    'RelTol', 1e-12);
verifyEqual(test_case, observation.LCOAUsdPerT, 465.18, 'AbsTol', 1e-12);
verifyEqual(test_case, observation.ObjectiveCostMinusRevenueUsd, ...
    -6980408.184133, 'AbsTol', 1e-6);
verifyEqual(test_case, observation.SolverRelativeGap, 9.9881e-5, ...
    'AbsTol', 1e-10);
verifyTrue(test_case, observation.ReproducedAfterParameterExternalization);
end

function testProtocolIsNotMisrepresentedAsFinalAnalysisPlan(test_case)
protocol = protocol_v5();

verifyEqual(test_case, protocol.RegistrationStatus, ...
    "boundary_frozen_confirmatory_analysis_not_yet_complete");
verifyNotEmpty(test_case, protocol.PendingSubprotocols);
verifyEqual(test_case, protocol.ChangeControl, ...
    "append_only_v5_1_before_new_model_or_2025_outcomes");
end

function testS2ManifestMatchesCurrentPhysicalBaseline(test_case)
manifest = s2_baseline_manifest();

verifyEqual(test_case, manifest.ModelVariant, ...
    "Zhou_S2_capacity_with_S3_startup_electricity");
verifyEqual(test_case, manifest.Renewable.PVCapacityKW, 200e3);
verifyEqual(test_case, manifest.Renewable.PWCapacityKW, 200e3);
verifyEqual(test_case, manifest.Renewable.InputScale, 0.8623, ...
    'AbsTol', 1e-12);
verifyEqual(test_case, manifest.AEL.CapacityKW, 130e3);
verifyEqual(test_case, manifest.AEL.ModuleCount, 26);
verifyEqual(test_case, manifest.AEL.ModulePowerKW, 5e3);
verifyTrue(test_case, manifest.AEL.StartupElectricityEnabled);
verifyEqual(test_case, manifest.HB.MinimumLoad, 0.30);
verifyEqual(test_case, manifest.HB.RampRatePerHour, 0.20);
verifyEqual(test_case, manifest.H2Storage.MinimumMassKG, 3295.6, ...
    'AbsTol', 1e-8);
verifyEqual(test_case, manifest.H2Storage.MaximumMassKG, 9886.8, ...
    'AbsTol', 1e-8);
verifyEqual(test_case, manifest.H2Storage.InitialMassKG, 6591.2, ...
    'AbsTol', 1e-8);
verifyEqual(test_case, manifest.Grid.ContractKW, 30e3);
verifyEqual(test_case, manifest.Economics.LoanRatio, 0.80);
verifyEqual(test_case, manifest.Economics.LoanInterestRate, 0.046);
verifyEqual(test_case, manifest.Economics.LoanTermYears, 20);
verifyEqual(test_case, manifest.Economics.ConverterCapexUsdPerKW, 43);
verifyEqual(test_case, manifest.Economics.TransformerCapexUsdPerKW, 51);
verifyEqual(test_case, manifest.Economics.WindOMRate, 0.02);
verifyEqual(test_case, manifest.Economics.PVOMRate, 0.01);
verifyEqual(test_case, manifest.VariableInputs.AELWaterTPerTH2, 28);
verifyEqual(test_case, manifest.VariableInputs.HBWaterTPerTNH3, 2.70);
verifyGreaterThan(test_case, manifest.AnnualFixedCost.TotalUsdPerYear, 0);
verifyEqual(test_case, manifest.AnnualFixedCost.LaborUsdPerYear, 3e6);
end

function testCalibrationAssumptionsAreNotLabeledAsZhouData(test_case)
manifest = s2_baseline_manifest();

verifyEqual(test_case, manifest.SourceClassification.RenewableCapacityMix, ...
    "current_200PV_200PW_design_not_Zhou_100PV_300PW_reference");
verifyEqual(test_case, manifest.SourceClassification.RenewableInputScale, ...
    "unresolved_calibration_factor");
verifyEqual(test_case, manifest.SourceClassification.GridContract, ...
    "s2_cost_closing_calibration_assumption");
verifyEqual(test_case, manifest.SourceClassification.Labor, ...
    "s2_cost_closing_calibration_assumption");
verifyEqual(test_case, manifest.SourceClassification.PressureBasis, ...
    "modeling_assumption_requires_sensitivity");
verifyEqual(test_case, manifest.SourceClassification.StartupElectricity, ...
    "s3_parameter_applied_as_s2_study_override");
verifyEqual(test_case, manifest.SourceClassification.WaterAndCatalystCosts, ...
    "supplemental_cost_assumptions");
verifyEqual(test_case, manifest.SourceClassification.GridCapacityFee, ...
    "supplemental_cost_assumption");
end

function testDirectionalHypothesesAreFrozenWithoutInventedThresholds(test_case)
protocol = protocol_v5();

verifyTrue(test_case, protocol.Hypotheses.DirectionsFrozen);
verifyEqual(test_case, numel(protocol.Hypotheses.Statements), 3);
verifyFalse(test_case, protocol.Hypotheses.NumericSuperiorityThresholdsFrozen);
verifyEqual(test_case, protocol.Hypotheses.ThresholdStatus, ...
    "must_be_frozen_in_v5_1_before_new_results");
end

function testBaselineReadsFrozenRenewableScaleFromParameters(test_case)
params = my_system('s2');
verifyEqual(test_case, params.renewable.input_scale, 0.8623, ...
    'AbsTol', 1e-12);

baseline_source = fileread(fullfile(test_case.TestData.project_dir, ...
    'src', 'baseline.m'));
model_source = fileread(fullfile(test_case.TestData.project_dir, ...
    'src', 'dispatch_model.m'));
verifyNotEmpty(test_case, regexp(baseline_source, ...
    'model\s*=\s*dispatch_model\(params,\s*renewable_data,\s*run_options\)', ...
    'once'));
verifyNotEmpty(test_case, regexp(model_source, ...
    'params\.renewable\.input_scale', 'once'));
verifyEmpty(test_case, regexp(model_source, ...
    'renewable_data\.(pv|pw)_power_kw\s*\*\s*0\.8623', 'once'));

verifyNotEmpty(test_case, regexp(baseline_source, ...
    '''ConstraintTolerance'',\s*1e-5', 'once'));
verifyNotEmpty(test_case, regexp(baseline_source, ...
    '''RelativeGapTolerance'',\s*1e-4', 'once'));
verifyNotEmpty(test_case, regexp(baseline_source, ...
    'economic_objective_converged\s*=\s*exitflag\s*==\s*1', 'once'));
verifyEmpty(test_case, regexp(baseline_source, ...
    'economic_objective_converged\s*=\s*exitflag\s*>\s*0', 'once'));

main_source = fileread(fullfile(test_case.TestData.project_dir, ...
    'src', 'main.m'));
verifyNotEmpty(test_case, regexp(main_source, ...
    'renewable_data\s*=\s*load_res_year\(data_cfg\)', 'once'));
verifyNotEmpty(test_case, regexp(main_source, ...
    'params\s*=\s*my_system\(''s2''\)', 'once'));
verifyNotEmpty(test_case, regexp(main_source, ...
    'params\.AEL\.common\.startup\s*=\s*true', 'once'));
verifyNotEmpty(test_case, regexp(main_source, ...
    'results\s*=\s*baseline\(params,\s*renewable_data\)', 'once'));
verifyEmpty(test_case, regexp(main_source, ...
    'stage\d+_run_', 'once'));

stage1_source = fileread(fullfile(test_case.TestData.project_dir, ...
    'src', 'stages', 'stage1_run_zhou_s2_baseline.m'));
verifyNotEmpty(test_case, regexp(stage1_source, ...
    'data_year\s*=\s*option_value\(config,\s*''data_year'',\s*2022\)', ...
    'once'));
verifyNotEmpty(test_case, regexp(stage1_source, ...
    'params\.AEL\.common\.startup\s*=\s*true', 'once'));
end

function testProtocolAndManifestSealsVerify(test_case)
protocol = protocol_v5();
manifest = s2_baseline_manifest();

verifyTrue(test_case, protocol_v5('verify', protocol));
verifyTrue(test_case, s2_baseline_manifest('verify', manifest));
verifyEqual(test_case, protocol.Seal, "6B71CCF0");
verifyEqual(test_case, manifest.Seal, "9FE68D80");
verifyEqual(test_case, protocol_v5('checksum', protocol), protocol.Seal);
end

function testProtocolV51FreezesForecastAndContractRules(test_case)
subprotocol = protocol_v5('v5_1');

verifyEqual(test_case, subprotocol.ProtocolVersion, "5.1.37");
verifyEqual(test_case, subprotocol.ParentProtocolVersion, "5.0.0");
verifyEqual(test_case, subprotocol.ParentProtocolSeal, "6B71CCF0");
verifyTrue(test_case, subprotocol.ConfirmedUserDecisions.NoSeparateTestFile);
verifyTrue(test_case, ...
    subprotocol.ConfirmedUserDecisions.UseRealForecastThroughSameInterface);
verifyTrue(test_case, ...
    subprotocol.ConfirmedUserDecisions.ExcludeBiasedSimulationFromConfirmatoryClaims);
verifyEqual(test_case, subprotocol.ConfirmedUserDecisions.ContractDelayDays, 7);
verifyTrue(test_case, subprotocol.ConfirmedUserDecisions.NoEarlyDeliveryCredit);
verifyTrue(test_case, subprotocol.ConfirmedUserDecisions.ExistingAssetsOnly);
verifyTrue(test_case, subprotocol.ConfirmedUserDecisions.NoAmmoniaStorage);
verifyTrue(test_case, ...
    subprotocol.ConfirmedUserDecisions.FreezeStage1MatOutputAsContract);
verifyTrue(test_case, ...
    subprotocol.ConfirmedUserDecisions.StopCapacitySearchAtFrozenContract);
verifyTrue(test_case, ...
    subprotocol.ConfirmedUserDecisions.AnnualCumulativeCarbonBudget);
verifyTrue(test_case, ...
    subprotocol.ConfirmedUserDecisions.NoIndependentDailyCarbonCap);
verifyTrue(test_case, ...
    subprotocol.ConfirmedUserDecisions.DailyReachabilityCheckpoints);
verifyTrue(test_case, ...
    subprotocol.ConfirmedUserDecisions.AdaptiveCarbonReserve);
verifyTrue(test_case, ...
    subprotocol.ConfirmedUserDecisions.RecoursePurchaseExposureReserve);
verifyTrue(test_case, ...
    subprotocol.ConfirmedUserDecisions.LexicographicHBDownwardRecourse);
verifyTrue(test_case, ...
    subprotocol.ConfirmedUserDecisions.CarbonStateConsistentRecourse);
verifyTrue(test_case, ...
    subprotocol.ConfirmedUserDecisions.OneStepCarbonViabilityBuffer);
verifyTrue(test_case, ...
    subprotocol.ConfirmedUserDecisions.FeasibleCarbonBufferProjection);
verifyTrue(test_case, ...
    subprotocol.ConfirmedUserDecisions.DownwardAELCommitmentRecourse);
verifyTrue(test_case, ...
    subprotocol.ConfirmedUserDecisions.SchemeConsistentCarbonReference);
verifyTrue(test_case, ...
    subprotocol.ConfirmedUserDecisions.DayAheadReserveFeasibleProjection);
verifyTrue(test_case, ...
    subprotocol.ConfirmedUserDecisions.RealtimeInheritsAppliedDayAheadReserve);
verifyTrue(test_case, ...
    subprotocol.ConfirmedUserDecisions.AbsoluteAnnualEmissionsBudgetForEconomicOnly);
verifyTrue(test_case, ...
    subprotocol.ConfirmedUserDecisions.BankableCarbonBudgetWithBoundedBorrowing);
verifyTrue(test_case, ...
    subprotocol.ConfirmedUserDecisions.FourteenDayCarbonBorrowingAfterDiagnostic);
verifyTrue(test_case, ...
    subprotocol.ConfirmedUserDecisions.RejectBiasedPersistenceForClosure);
verifyTrue(test_case, ...
    subprotocol.ConfirmedUserDecisions.DevelopmentOracleNotForecastClaim);
verifyTrue(test_case, ...
    subprotocol.ConfirmedUserDecisions.AnnualProductionPacing);
verifyTrue(test_case, ...
    subprotocol.ConfirmedUserDecisions.ProductionReferenceGovernor);
verifyTrue(test_case, ...
    subprotocol.ConfirmedUserDecisions.HydrogenNeutralReserveWithinBankedBudget);
verifyTrue(test_case, ...
    subprotocol.ConfirmedUserDecisions.PlanningHorizonPhysicalCarbonReserve);
verifyTrue(test_case, ...
    subprotocol.ConfirmedUserDecisions.RestartViableHydrogenHandoff);
verifyTrue(test_case, ...
    subprotocol.ConfirmedUserDecisions.DisableDefaultStatisticalCarbonReserve);
verifyTrue(test_case, ...
    subprotocol.ConfirmedUserDecisions.ObservedRenewableGridBudgets);
verifyEqual(test_case, subprotocol.Contract.AnnualQuantitySource, ...
    "stage1_2022_mat_actual_NH3_output_rounded_6dp_verified_feasible");
verifyEqual(test_case, subprotocol.Contract.ReferenceAnnualQuantitySource, ...
    "stage1_2022_mat_baseline_actual_NH3_output");
verifyEqual(test_case, subprotocol.Contract.ReferenceAnnualQuantityT, ...
    76022.9642746094, 'AbsTol', 1e-9);
verifyEqual(test_case, subprotocol.Contract.AnnualQuantityT, ...
    76022.964275, 'AbsTol', 1e-9);
verifyEqual(test_case, subprotocol.Contract.AnnualQuantityRoundingDecimals, 6);
verifyEqual(test_case, subprotocol.Contract.DailyQuantityKG, ...
    76022.964275 * 1000 / 365, 'AbsTol', 1e-9);
verifyEqual(test_case, subprotocol.Contract.CapacitySearchRole, ...
    "diagnostic_only_not_contract_selection");
verifyEqual(test_case, subprotocol.Contract.MaxDelayDays, 7);
verifyEqual(test_case, subprotocol.Contract.MaxBacklogFormula, ...
    "max_delay_days*daily_contract_kg");
verifyEqual(test_case, subprotocol.Contract.TerminalBacklogKG, 0);
verifyTrue(test_case, subprotocol.Contract.NoEarlyDeliveryCredit);
verifyTrue(test_case, subprotocol.Contract.ContractIsExogenousNotDispatchDecision);
verifyEqual(test_case, ...
    subprotocol.ContractCapacityOptimization.MaxLCOAIncreaseFraction, 0.02);
verifyEqual(test_case, ...
    subprotocol.ContractCapacityOptimization.ContractBracketRelativeTolerance, ...
    0.005);
verifyEqual(test_case, ...
    subprotocol.ContractCapacityOptimization.EconomicRelativeGapTolerance, ...
    1e-4);
verifyEqual(test_case, ...
    subprotocol.ContractCapacityOptimization.WarmStartSource, ...
    "stage1_or_prior_feasible_candidate_dispatch");
verifyEqual(test_case, ...
    subprotocol.ContractCapacityOptimization.ObjectiveMethod, ...
    "fixed_contract_economic_feasibility_certificate");
verifyEqual(test_case, ...
    subprotocol.ContractCapacityOptimization.PrimaryObjective, ...
    "verify_frozen_stage1_mat_contract_feasibility");
verifyEqual(test_case, ...
    subprotocol.ContractCapacityOptimization.Status, ...
    "stopped_after_frozen_contract_verified");
verifyEqual(test_case, ...
    subprotocol.ContractCapacityOptimization.Role, ...
    "diagnostic_only_not_contract_selection");
verifyEqual(test_case, ...
    subprotocol.ContractCapacityOptimization.FrozenAnnualQuantityT, ...
    76022.964275, 'AbsTol', 1e-9);
verifyEqual(test_case, ...
    subprotocol.ContractCapacityOptimization.InitialCandidatesAnnualT, ...
    [70e3; 73e3; 76022.964275], 'AbsTol', 1e-9);
verifyTrue(test_case, ...
    subprotocol.ContractCapacityOptimization.TimeoutWithIncumbentProvesFeasibilityOnly);
certificate = subprotocol.ContractFeasibilityCertificate;
verifyEqual(test_case, certificate.SourceProtocolVersion, "5.1.3");
verifyEqual(test_case, certificate.SourceProtocolSeal, "98AB91E8");
verifyEqual(test_case, certificate.AnnualContractT, ...
    76022.964275, 'AbsTol', 1e-9);
verifyEqual(test_case, certificate.ActualAnnualProductionT, ...
    78194.835018008060, 'AbsTol', 1e-9);
verifyEqual(test_case, certificate.LCOAUSDPerT, ...
    469.052358681166, 'AbsTol', 1e-9);
verifyEqual(test_case, certificate.LCOAIncreaseFraction, ...
    0.00832384919049711, 'AbsTol', 1e-12);
verifyTrue(test_case, certificate.MaximumBacklogEqualsSevenDayLimit);
verifyTrue(test_case, certificate.NoMaximumCapacityClaim);
end

function testProtocolV51DefinesReplaceableForecastInterface(test_case)
subprotocol = protocol_v5('v5_1');
forecast = subprotocol.Forecast;

verifyEqual(test_case, forecast.Mode, ...
    "simulated_day_ahead_with_real_forecast_schema");
verifyTrue(test_case, forecast.RealForecastInterface.NoObservedTargetPowerInForecastFields);
verifyEqual(test_case, forecast.RealForecastInterface.RequiredHorizons, 1:72);
verifyTrue(test_case, ismember("issue_time_utc", ...
    forecast.RealForecastInterface.RequiredFields));
verifyTrue(test_case, ismember("target_time_utc", ...
    forecast.RealForecastInterface.RequiredFields));
verifyTrue(test_case, ismember("pv_power_kw", ...
    forecast.RealForecastInterface.RequiredFields));
verifyTrue(test_case, ismember("pw_power_kw", ...
    forecast.RealForecastInterface.RequiredFields));
verifyEqual(test_case, forecast.SimulatedGenerator.DeterministicCore, ...
    "day_ahead_persistence_no_future_leakage");
verifyEqual(test_case, forecast.SimulatedGenerator.ResidualLibraryYears, ...
    [2022, 2023]);
verifyTrue(test_case, forecast.SimulatedGenerator.NoHoldoutFitting);
verifyEqual(test_case, forecast.DevelopmentOracle.Mode, "observed_oracle");
verifyEqual(test_case, forecast.DevelopmentOracle.AllowedYears, [2022, 2023]);
verifyFalse(test_case, forecast.DevelopmentOracle.OperationalForecastClaim);
verifyTrue(test_case, forecast.DevelopmentOracle.HoldoutUseForbidden);
verifyEqual(test_case, forecast.BiasGuard.SimulationClaimLimit, ...
    "simulation_environment_only");
verifyTrue(test_case, ...
    forecast.BiasGuard.ExcludeIfSimulationChangesFeasibilityOrMaterialRanking);
verifyEqual(test_case, subprotocol.RollingDispatch.PlanningHours, 72);
verifyEqual(test_case, subprotocol.RollingDispatch.CommitHours, 24);
verifyEqual(test_case, subprotocol.RollingDispatch.ReplanIntervalHours, 24);
verifyEqual(test_case, subprotocol.RollingDispatch.MaxTimeSecondsPerSolve, 180);
verifyEqual(test_case, subprotocol.RollingDispatch.RelativeGapTolerance, 1e-3);
verifyEqual(test_case, subprotocol.RollingDispatch.ConstraintTolerance, 1e-5);
verifyEqual(test_case, ...
    subprotocol.RollingDispatch.ReachabilityCheckpoints.IntervalHours, 24);
verifyEqual(test_case, ...
    subprotocol.RollingDispatch.ReachabilityCheckpoints.AppliesTo, ...
    ["carbon"; "sell"; "curtail"]);
verifyEqual(test_case, ...
    subprotocol.RollingDispatch.CarbonReserve.DefaultQuantileByScheme.economic_only, ...
    0);
verifyEqual(test_case, ...
    subprotocol.RollingDispatch.CarbonReserve.DefaultQuantileByScheme.contract_plan_and_hb_smoothing, ...
    0);
verifyEqual(test_case, ...
    subprotocol.RollingDispatch.CarbonReserve.Method, ...
    "expanding_recourse_purchase_exposure_quantile");
verifyTrue(test_case, ...
    subprotocol.RollingDispatch.CarbonReserve.NoFutureLeakage);
verifyFalse(test_case, ...
    subprotocol.RollingDispatch.CarbonReserve.RealtimeReserve);
verifyTrue(test_case, ...
    subprotocol.RollingDispatch.CarbonReserve.MinimumPhysicalReserve.Active);
verifyEqual(test_case, ...
    subprotocol.RollingDispatch.CarbonReserve.MinimumPhysicalReserve.CO2KG, ...
    1541687.462187024, 'AbsTol', 1e-6);
verifyEqual(test_case, ...
    subprotocol.RollingDispatch.CarbonReserve.MinimumPhysicalReserve.HorizonHours, ...
    72);
verifyEqual(test_case, subprotocol.RollingDispatch.TerminalH2Rule, ...
    "nonfinal_handoff_preserves_window_initial_and_one_step_HB_hydrogen");
verifyTrue(test_case, subprotocol.RollingDispatch.StrictContractCohorts);
verifyEqual(test_case, subprotocol.RollingDispatch.RealtimeRecourse.FixedPlan, ...
    ["HB_load"; "AEL_commitment"]);
verifyEqual(test_case, ...
    subprotocol.RollingDispatch.RealtimeRecourse.CarbonStateRule, ...
    "inherit_applied_day_ahead_reserve_then_project_to_realtime_feasible_set");
verifyEqual(test_case, ...
    subprotocol.RollingDispatch.RealtimeRecourse.AdjustableControls, ...
    ["HB_downward_on_hard_infeasibility"; ...
     "AEL_commitment_downward_on_hard_infeasibility"; "AEL_power"; ...
     "grid_purchase"; "grid_sale"; "curtailment"]);
verifyTrue(test_case, ...
    subprotocol.RollingDispatch.RealtimeRecourse.RejectEmergencySlack);
carbon = subprotocol.RollingDispatch.CarbonAccounting;
verifyEqual(test_case, carbon.Accounting, ...
    "scheme_specific_annual_cumulative");
verifyEqual(test_case, carbon.StateVariables, ...
    ["cumulative_grid_emissions_kg"; "cumulative_nh3_kg"]);
verifyEqual(test_case, carbon.IntermediateRule, ...
    "economic_scheduled_emissions_and_cumulative_output_pacing_or_contract_carbon_debt");
verifyEqual(test_case, carbon.RemainingNH3Reference, ...
    "economic_uses_cumulative_common_output_schedule_and_contract_uses_frozen_quantity");
verifyEqual(test_case, carbon.ReachabilityMeaning, ...
    "economic_cumulative_output_pacing_with_14_day_emissions_borrowing_and_contract_declining_reachability");
verifyEqual(test_case, carbon.EconomicBudgetSchedule.AnnualBudgetKG, ...
    0.3 * 76022.964275e3, 'AbsTol', 1e-6);
verifyTrue(test_case, carbon.EconomicBudgetSchedule.UnusedBudgetBankable);
verifyEqual(test_case, ...
    carbon.EconomicBudgetSchedule.MaximumBorrowingDays, 14);
verifyEqual(test_case, ...
    carbon.EconomicBudgetSchedule.DiagnosticMinimumBorrowingDays, ...
    12.600081137, 'AbsTol', 1e-9);
verifyEqual(test_case, ...
    carbon.EconomicBudgetSchedule.DefaultStatisticalReserveQuantile, 0);
verifyFalse(test_case, carbon.EconomicBudgetSchedule.IndependentDailyCap);
verifyEqual(test_case, carbon.PhysicalRecoveryFactorStatus, ...
    "superseded_by_cumulative_annual_output_pacing");
verifyEqual(test_case, carbon.AnnualProductionSchedule.StartupGraceDays, 7);
verifyEqual(test_case, carbon.AnnualProductionSchedule.ScheduledDays, 358);
verifyTrue(test_case, carbon.AnnualProductionSchedule.EarlyProductionBankable);
verifyFalse(test_case, carbon.AnnualProductionSchedule.IndependentDailyTarget);
verifyEqual(test_case, ...
    carbon.AnnualProductionSchedule.EnforcementBoundaryHours, 24);
verifyFalse(test_case, carbon.AnnualProductionSchedule.PlanningTailTarget);
verifyEqual(test_case, ...
    carbon.AnnualProductionSchedule.IntermediateProjection, ...
    "maximum_feasible_commitment_output");
verifyTrue(test_case, ...
    carbon.AnnualProductionSchedule.UnmetProgressCarriesForward);
verifyFalse(test_case, carbon.AnnualProductionSchedule.YearEndProjection);
verifyEqual(test_case, carbon.YearEndRule, ...
    "cumulative_emissions_not_above_limit_times_cumulative_nh3");
verifyFalse(test_case, carbon.IndependentDailyIntensityCap);
verifyTrue(test_case, carbon.RejectCarbonSlack);
end

function testProtocolV51FreezesCalibrationAndSuperiorityRules(test_case)
subprotocol = protocol_v5('v5_1');

verifyEqual(test_case, subprotocol.DataSplit.DevelopmentYears, [2022, 2023]);
verifyEqual(test_case, subprotocol.DataSplit.CalibrationYear, 2024);
verifyEqual(test_case, subprotocol.DataSplit.HoldoutYear, 2025);
verifyTrue(test_case, subprotocol.DataSplit.NoHoldoutTuning);
verifyEqual(test_case, subprotocol.Calibration.CandidateGrid.ReserveQuantile, ...
    [0.50, 0.75, 0.90, 0.95]);
verifyEqual(test_case, ...
    subprotocol.Calibration.CandidateGrid.ReserveLookaheadDays, [1, 2, 3]);
verifyEqual(test_case, ...
    subprotocol.Calibration.CandidateGrid.LCOAEpsilonFraction, ...
    [0, 0.005, 0.01, 0.02]);
verifyEqual(test_case, ...
    subprotocol.SuperiorityRules.MaterialRiskImprovementFraction, 0.10);
verifyEqual(test_case, ...
    subprotocol.SuperiorityRules.MaxLCOAIncreaseFraction, 0.02);
verifyEqual(test_case, subprotocol.FailureRules.SimulationBiasDetected, ...
    "label_as_simulation_only_and_exclude_from_confirmatory_claims");
end

function testV51MetricsUseFrozenAnnualContract(test_case)
mat_path = [tempname, '.mat'];
cleanup = onCleanup(@() delete_if_file(mat_path));

subprotocol = protocol_v5('v5_1');
daily_contract_kg = subprotocol.Contract.DailyQuantityKG;
hourly_contract_kg = daily_contract_kg / 24;

params = struct();
params.time = struct('step', 1);
params.HB = struct( ...
    'max_load', 1, ...
    'ramp_rate', 1, ...
    'nh3_output', 1, ...
    'lit_h2', 0.18);
params.AEL = struct('common', struct('max_power', 10));
params.transformer = struct('max_load', 1, 'capacity', 1);
params.unit = struct('h2_density', 0.09);
params.h2_storage = struct('work_mass', 100, 'mass', 150);

result = struct();
result.dispatch = struct( ...
    'NH3_prod', hourly_contract_kg * ones(8760, 1), ...
    'HB_load', ones(8760, 1), ...
    'P_AEL', ones(8760, 1), ...
    'P_sell', zeros(8760, 1), ...
    'P_purchase', zeros(8760, 1), ...
    'P_curt', zeros(8760, 1));
result.storage = struct('soc_work', 0.5 * ones(8760, 1));
result.summary = struct( ...
    'NH3_prod_t_y', 1, ...
    'lcoa', 1, ...
    'net_profit', 2);
result.fval = -2;
result.exitflag = 1;
result.check = struct( ...
    'max_power_residual_kw', 0, ...
    'max_storage_residual_kg', 0);

run_info = struct( ...
    'status', "solved", ...
    'model_variant', "synthetic_contract_quantity_source", ...
    'data_year', 2099);
save(mat_path, 'result', 'params', 'run_info');

metrics = evaluate_protocol_v51_metrics(mat_path);

verifyEqual(test_case, metrics.Contract.annual_contract_t, ...
    76022.964275, 'AbsTol', 1e-9);
verifyEqual(test_case, metrics.Contract.daily_contract_kg, ...
    daily_contract_kg, 'AbsTol', 1e-9);
verifyEqual(test_case, metrics.Feasibility.maximum_contract_backlog_kg, 0, ...
    'AbsTol', 1e-6);
verifyEqual(test_case, metrics.Contract.annual_surplus_t, 0, ...
    'AbsTol', 1e-6);
verifyEqual(test_case, metrics.Contract.maximum_delivery_delay_days, 0);
verifyEqual(test_case, metrics.Contract.late_cohort_count, 0);
verifyEqual(test_case, metrics.Contract.unserved_cohort_count, 0);
verifyEqual(test_case, metrics.Diagnostics.Summary.delay_violation_day_count, 0);
verifyEqual(test_case, metrics.Diagnostics.Summary.dominant_bottleneck, ...
    "no_contract_breach");
verifyEqual(test_case, metrics.Diagnostics.Daily.day_index, (1:365)');
verifyEqual(test_case, metrics.Diagnostics.Daily.h2_min_work_soc, ...
    0.5 * ones(365, 1));
verifyEqual(test_case, ...
    metrics.Diagnostics.ReserveScreen.h2_for_delay_cap_kg, 0, ...
    'AbsTol', 1e-12);
verifyEqual(test_case, metrics.Diagnostics.ReserveScreen.decision, ...
    "no_extra_reserve_required_for_delay_cap");
verifyEqual(test_case, ...
    metrics.Diagnostics.ReserveScreen.WindowSensitivity.delay_days, ...
    [3; 7; 14]);
verifyEqual(test_case, ...
    metrics.Diagnostics.ReserveScreen.WindowSensitivity.h2_for_delay_cap_kg, ...
    zeros(3, 1), 'AbsTol', 1e-12);
verifyTrue(test_case, all( ...
    metrics.Diagnostics.ReserveScreen.WindowSensitivity.decision == ...
    "no_extra_reserve_required_for_delay_cap"));
end

function testV51MetricsDetectStrictSevenDayDeliveryViolation(test_case)
mat_path = [tempname, '.mat'];
cleanup = onCleanup(@() delete_if_file(mat_path));

subprotocol = protocol_v5('v5_1');
daily_contract_kg = subprotocol.Contract.DailyQuantityKG;
daily_nh3_kg = daily_contract_kg * ones(365, 1);
daily_nh3_kg(1:8) = 0;
daily_nh3_kg(9) = 9 * daily_contract_kg;

params = struct();
params.time = struct('step', 1);
params.HB = struct('max_load', 1, 'ramp_rate', 1, ...
    'nh3_output', 1, 'lit_h2', 0.18);
params.AEL = struct('common', struct('max_power', 10));
params.transformer = struct('max_load', 1, 'capacity', 1);
params.unit = struct('h2_density', 0.09);
params.h2_storage = struct('work_mass', 100, 'mass', 150);

result = struct();
result.dispatch = struct( ...
    'NH3_prod', repelem(daily_nh3_kg / 24, 24), ...
    'HB_load', ones(8760, 1), ...
    'P_AEL', ones(8760, 1), ...
    'P_sell', zeros(8760, 1), ...
    'P_purchase', zeros(8760, 1), ...
    'P_curt', zeros(8760, 1));
result.storage = struct('soc_work', 0.5 * ones(8760, 1));
result.summary = struct('NH3_prod_t_y', 1, 'lcoa', 1, 'net_profit', 2);
result.fval = -2;
result.exitflag = 1;
result.check = struct('max_power_residual_kw', 0, ...
    'max_storage_residual_kg', 0);
run_info = struct('status', "solved", ...
    'model_variant', "synthetic_late_contract", 'data_year', 2099);
save(mat_path, 'result', 'params', 'run_info');

metrics = evaluate_protocol_v51_metrics(mat_path);

verifyEqual(test_case, metrics.Contract.maximum_delivery_delay_days, 8);
verifyEqual(test_case, metrics.Contract.late_cohort_count, 1);
verifyEqual(test_case, metrics.Contract.unserved_cohort_count, 0);
verifyFalse(test_case, metrics.Feasibility.strict_delivery_ok);
end

function testProtocolV51SealVerifies(test_case)
subprotocol = protocol_v5('v5_1');

verifyTrue(test_case, protocol_v5('verify_v5_1', subprotocol));
verifyEqual(test_case, subprotocol.Seal, "000CDCA8");
verifyEqual(test_case, protocol_v5('checksum', subprotocol), ...
    subprotocol.Seal);
end

function testProtocolV52FreezesClaimAndHoldoutBoundary(test_case)
protocol = protocol_v5('v5_2');

verifyEqual(test_case, protocol.ProtocolVersion, "5.2.0");
verifyEqual(test_case, protocol.ParentProtocolVersion, "5.1.37");
verifyEqual(test_case, protocol.ParentProtocolSeal, "000CDCA8");
verifyEqual(test_case, protocol.FreezeStage, ...
    "claim_selection_and_holdout_boundary");
verifyEqual(test_case, protocol.MainClaim.ClaimType, ...
    "cost_bounded_stability_noninferiority");
verifyFalse(test_case, protocol.MainClaim.AllowsUniversalStabilityIndexClaim);
verifyTrue(test_case, protocol_v5('verify_v5_2', protocol));
verifyEqual(test_case, protocol.Seal, "D18BB5A0");

verifyEqual(test_case, protocol.DataSplit.SelectionYear, 2024);
verifyEqual(test_case, protocol.DataSplit.HoldoutYear, 2025);
verifyFalse(test_case, protocol.DataSplit.HoldoutUsedForSelection);
verifyEqual(test_case, protocol.DataSplit.HoldoutOpeningRule, ...
    "open_once_after_v5_2_protocol_tests_and_quality_gate_pass");
end

function testProtocolV52FreezesPrimaryMetricsAndThresholds(test_case)
protocol = protocol_v5('v5_2');
primary_names = [protocol.PrimaryOutcomes.Name];
primary_roles = [protocol.PrimaryOutcomes.Role];
primary_directions = [protocol.PrimaryOutcomes.Direction];

verifyEqual(test_case, primary_names, ...
    ["contract_shortfall_p95", "mar", "h2_soc_p05", "lcoa"]);
verifyTrue(test_case, all(primary_roles == "primary"));
verifyEqual(test_case, primary_directions, ...
    ["smaller_is_better", "smaller_is_better", ...
     "larger_is_better", "smaller_is_better"]);
verifyEqual(test_case, protocol.SuccessCriteria.MaxLCOAIncreaseFraction, ...
    0.02, 'AbsTol', 1e-12);
verifyEqual(test_case, ...
    protocol.SuccessCriteria.ContractShortfallP95RelativeNoninferiorityMargin, ...
    0.01, 'AbsTol', 1e-12);
verifyEqual(test_case, ...
    protocol.SuccessCriteria.MinimumMaterialImprovementFraction, ...
    0.10, 'AbsTol', 1e-12);
verifyEqual(test_case, protocol.SuccessCriteria.H2SOCP05MinimumAbsoluteGain, ...
    0, 'AbsTol', 1e-12);
end

function testProtocolV52ExcludesOracleFromConfirmatorySelection(test_case)
protocol = protocol_v5('v5_2');
scheme_names = [protocol.Schemes.Name];
is_oracle = [protocol.Schemes.DiagnosticOracleOnly];
eligible = [protocol.Schemes.EligibleForConfirmatorySelection];

verifyTrue(test_case, any(scheme_names == ...
    "perfect_information_oracle_diagnostic"));
verifyFalse(test_case, any(is_oracle & eligible));
verifyTrue(test_case, all(eligible(~is_oracle)));
verifyEqual(test_case, protocol.SelectionRule.Method, ...
    "filter_then_lexicographic_sort");
verifyEqual(test_case, protocol.SelectionRule.SortOrder, ...
    ["contract_shortfall_p95"; "mar"; "h2_soc_p05_desc"; "lcoa"]);
verifyEqual(test_case, protocol.FailureInterpretation.NoCandidatePasses, ...
    "report_no_confirmatory_superiority_and_present_best_tradeoff");
end

function testProtocolV52SelectionRejectsHoldoutYear(test_case)
grid_table = synthetic_v52_selection_grid();
run_info = struct('data_year', 2025);

verifyError(test_case, @() select_protocol_v52_candidate( ...
    grid_table, run_info), ...
    'select_protocol_v52_candidate:bad_data_year');
end

function testProtocolV52SelectionRetainsAuditAndRanksCandidates(test_case)
grid_table = synthetic_v52_selection_grid();
run_info = struct('data_year', 2024);

[selected, audit_table, selection_info] = ...
    select_protocol_v52_candidate(grid_table, run_info);

verifyEqual(test_case, height(audit_table), height(grid_table));
verifyEqual(test_case, selected.case_id, "candidate_c");
verifyEqual(test_case, selected.selection_rank, 1);
verifyEqual(test_case, selection_info.status, "selected");
verifyEqual(test_case, selection_info.selected_case_id, "candidate_c");
verifyEqual(test_case, selection_info.eligible_candidate_count, 3);
verifyFalse(test_case, selection_info.holdout_used_for_selection);

oracle_row = audit_table(audit_table.case_id == ...
    "oracle_best_diagnostic", :);
verifyFalse(test_case, oracle_row.eligible_for_selection);
verifyTrue(test_case, contains(oracle_row.exclusion_reason, ...
    "oracle_diagnostic"));

failed_row = audit_table(audit_table.case_id == "failed_candidate", :);
verifyFalse(test_case, failed_row.eligible_for_selection);
verifyTrue(test_case, contains(failed_row.exclusion_reason, ...
    "status_not_completed"));
end

function testProtocolV52SelectionRejectsRestorationContinuation(test_case)
grid_table = synthetic_v52_selection_grid();
grid_table.restoration_day_count = zeros(height(grid_table), 1);
grid_table.restoration_day_count(grid_table.case_id == "candidate_c") = 2;
run_info = struct('data_year', 2024);

[selected, audit_table, selection_info] = ...
    select_protocol_v52_candidate(grid_table, run_info);

restored_row = audit_table(audit_table.case_id == "candidate_c", :);
verifyFalse(test_case, restored_row.eligible_for_selection);
verifyTrue(test_case, restored_row.restoration_continuation_used_v52);
verifyTrue(test_case, contains(restored_row.exclusion_reason, ...
    "restoration_continuation_diagnostic"));
verifyEqual(test_case, selected.case_id, "candidate_b");
verifyEqual(test_case, selection_info.eligible_candidate_count, 2);
end

function testCampaignUsesValidatedCompletionAndBlocksMissingSelection(test_case)
source_text = fileread(fullfile(project_root_for_tests(), ...
    'src', 'pipeline', 'run_full_campaign.m'));

verifyNotEmpty(test_case, regexp(source_text, ...
    'validate_completed_mat\([^)]*scheme', 'once'));
verifyNotEmpty(test_case, regexp(source_text, ...
    'string\(selection_info\.status\)\s*~=\s*"selected"', 'once'));
verifyNotEmpty(test_case, regexp(source_text, ...
    'run_full_campaign:no_selected_candidate', 'once'));
end

function testParallelStage5ResumeUsesSourceYear(test_case)
source_text = fileread(fullfile(project_root_for_tests(), ...
    'src', 'stages', 'run_stage5_parallel.m'));

verifyNotEmpty(test_case, regexp(source_text, ...
    'specs\s*=\s*attach_candidate_year\(specs,\s*source_year_value\)', ...
    'once'));
verifyEmpty(test_case, regexp(source_text, ...
    'candidate_rolling_path\(\s*\.\.\.\s*rolling_output_dir,\s*spec\.year', ...
    'once'));
end

function testFeasibilityBoundaryDryRunPlansStrictLayers(test_case)
report = run_feasibility_boundary(struct( ...
    'years', 2022, ...
    'execute', false, ...
    'save_output', false));

verifyTrue(test_case, isfield(report, 'Cases'));
verifyEqual(test_case, height(report.Cases), 4);
verifyEqual(test_case, report.Cases.year, [2022; 2022; 2022; 2022]);
verifyEqual(test_case, report.Cases.layer, [ ...
    "annual_oracle"; ...
    "rolling_oracle_strict"; ...
    "rolling_persistence_strict"; ...
    "rolling_residual_strict"]);
verifyTrue(test_case, all(~report.Cases.allow_infeasible_continuation));
verifyTrue(test_case, all(report.Cases.status == "planned"));
verifyTrue(test_case, all(report.Cases.confirmatory_role == ...
    "feasibility_boundary_not_optimization"));
end

function testFeasibilityBoundaryCanSelectResidualLayerOnly(test_case)
report = run_feasibility_boundary(struct( ...
    'years', [2024, 2025], ...
    'layers', "rolling_residual_strict", ...
    'forecast_seed', 42, ...
    'execute', false, ...
    'save_output', false));

verifyEqual(test_case, height(report.Cases), 2);
verifyEqual(test_case, report.Cases.year, [2024; 2025]);
verifyTrue(test_case, all(report.Cases.layer == ...
    "rolling_residual_strict"));
verifyTrue(test_case, all(report.Cases.forecast_mode == ...
    "simulated_residual_scenario"));
verifyEqual(test_case, report.Cases.forecast_seed, [42; 42]);
verifyTrue(test_case, all(report.Cases.status == "planned"));
end

function testFeasibilityBoundarySummarizesExistingFailureEvidence(test_case)
boundary_dir = tempname;
rolling_dir = fullfile(boundary_dir, 'rolling', ...
    'rolling_residual_strict');
mkdir(rolling_dir);
cleanup = onCleanup(@() delete_dir_if_exists(boundary_dir));

params = my_system('s2');
run_info = struct( ...
    'status', "requires_slack_diagnosis", ...
    'data_year', 2024, ...
    'scheme', "contract_plan_and_hb_smoothing", ...
    'forecast_mode', "simulated_residual_scenario", ...
    'failed_day', 139, ...
    'error_id', "rolling_dispatch:solve_failed", ...
    'error_message', ...
        "day_ahead_carbon_projection solve failed or did not converge.", ...
    'carbon_state', struct('debt_kg', -12), ...
    'production_pacing_history', struct( ...
        'day_ahead_restored', false(3, 1)));
failure_context = struct();
failure_context.day_index = 139;
failure_context.state = struct( ...
    'h2_kg', 3912.038, ...
    'contract_cohorts_kg', [1000; 2000]);
failure_context.carbon_reserve_kg = 10;
failure_context.base_carbon_reserve_kg = 8;
failure_context.h2_carbon_guard_kg = 10;
failure_context.plan_options = struct( ...
    'production', struct( ...
        'commit_min_nh3_kg', 500, ...
        'due_at_commit_kg', 3000, ...
        'allowable_backlog_after_commit_kg', 1000), ...
    'carbon', struct( ...
        'initial_emissions_kg', 100, ...
        'initial_nh3_kg', 1000, ...
        'remaining_reference_nh3_kg', 2000, ...
        'reference_nh3_per_step_kg', 3, ...
        'commit_reserve_kg', 10));
diagnosis = classify_infeasibility(struct( ...
    'run_info', run_info, ...
    'failure_context', failure_context, ...
    'params', params));
save(fullfile(rolling_dir, ...
    'v51_contract_plan_and_hb_smoothing_2024_latest.mat'), ...
    'run_info', 'failure_context', 'diagnosis', 'params');

report = run_feasibility_boundary(struct( ...
    'years', 2024, ...
    'execute', false, ...
    'save_output', false, ...
    'boundary_dir', boundary_dir, ...
    'summarize_existing', true));

verifyTrue(test_case, isfield(report, 'FailureSummary'));
verifyEqual(test_case, height(report.FailureSummary), 1);
summary = report.FailureSummary(1, :);
verifyEqual(test_case, summary.year, 2024);
verifyEqual(test_case, summary.layer, "rolling_residual_strict");
verifyEqual(test_case, summary.failed_day, 139);
verifyEqual(test_case, summary.primary_category, ...
    "carbon_reachability_projection_binding");
verifyEqual(test_case, summary.carbon_debt_kg, -12);
verifyEqual(test_case, summary.contract_backlog_kg, 3000);
verifyTrue(test_case, ismember("horizon_reserve_kg", ...
    string(report.FailureSummary.Properties.VariableNames)));
verifyEqual(test_case, summary.restoration_day_count, 0);
end

function testContractCarbonReserveIsAppliedToDryRunCarbonOptions(test_case)
mat_path = [tempname, '.mat'];
cleanup = onCleanup(@() delete_if_file(mat_path));

params = my_system('s2');
renewable_data = synthetic_renewable_data(2022, 96);
run_info = struct('data_year', 2022);
save(mat_path, 'params', 'renewable_data', 'run_info');

[~, dry_info] = rolling_dispatch(struct( ...
    'source_mat_path', mat_path, ...
    'scheme', "contract_plan_and_hb_smoothing", ...
    'forecast_mode', "observed_oracle", ...
    'contract_pacing_aggressiveness', 0.5, ...
    'contract_carbon_reserve_days', 3, ...
    'dry_run', true, ...
    'save_output', false, ...
    'verbose', false));

protocol = protocol_v5('v5_1');
expected_reserve_kg = params.environment.co2_limit ...
    * protocol.Contract.DailyQuantityKG * 3;
verifyEqual(test_case, dry_info.joint.contract_carbon_reserve_days, 3);
verifyEqual(test_case, dry_info.first_carbon.commit_reserve_kg, ...
    expected_reserve_kg, 'AbsTol', 1e-9);
verifyEqual(test_case, dry_info.first_carbon.horizon_reserve_kg, ...
    expected_reserve_kg, 'AbsTol', 1e-9);
end

function testContractCarbonReserveRejectsOutOfRangeDays(test_case)
mat_path = [tempname, '.mat'];
cleanup = onCleanup(@() delete_if_file(mat_path));

params = my_system('s2');
renewable_data = synthetic_renewable_data(2022, 96);
run_info = struct('data_year', 2022);
save(mat_path, 'params', 'renewable_data', 'run_info');

verifyError(test_case, @() rolling_dispatch(struct( ...
    'source_mat_path', mat_path, ...
    'scheme', "contract_plan_and_hb_smoothing", ...
    'forecast_mode', "observed_oracle", ...
    'contract_carbon_reserve_days', 15, ...
    'dry_run', true, ...
    'save_output', false, ...
    'verbose', false)), ...
    'rolling_dispatch:bad_contract_carbon_reserve');
end

function testContractTerminalClearanceWindowForcesZeroBacklog(test_case)
mat_path = [tempname, '.mat'];
cleanup = onCleanup(@() delete_if_file(mat_path));

params = my_system('s2');
renewable_data = synthetic_renewable_data(2022, 96);
run_info = struct('data_year', 2022);
save(mat_path, 'params', 'renewable_data', 'run_info');

[~, dry_info] = rolling_dispatch(struct( ...
    'source_mat_path', mat_path, ...
    'scheme', "contract_plan_and_hb_smoothing", ...
    'forecast_mode', "observed_oracle", ...
    'contract_terminal_clearance_days', 3, ...
    'dry_run', true, ...
    'save_output', false, ...
    'verbose', false));

protocol = protocol_v5('v5_1');
verifyEqual(test_case, dry_info.joint.contract_terminal_clearance_days, 3);
verifyEqual(test_case, ...
    dry_info.first_production.allowable_backlog_after_commit_kg, 0);
verifyEqual(test_case, dry_info.first_production.commit_min_nh3_kg, ...
    protocol.Contract.DailyQuantityKG, 'AbsTol', 1e-9);
end

function testContractTerminalBacklogCapAllowsSmallPreclearanceBuffer(test_case)
mat_path = [tempname, '.mat'];
cleanup = onCleanup(@() delete_if_file(mat_path));

params = my_system('s2');
renewable_data = synthetic_renewable_data(2022, 120);
run_info = struct('data_year', 2022);
save(mat_path, 'params', 'renewable_data', 'run_info');

[~, dry_info] = rolling_dispatch(struct( ...
    'source_mat_path', mat_path, ...
    'scheme', "contract_plan_and_hb_smoothing", ...
    'forecast_mode', "observed_oracle", ...
    'contract_terminal_clearance_days', 3, ...
    'contract_terminal_backlog_cap_fraction', 0.1, ...
    'dry_run', true, ...
    'save_output', false, ...
    'verbose', false));

protocol = protocol_v5('v5_1');
expected_backlog_kg = 0.1 * protocol.Contract.DailyQuantityKG;
verifyEqual(test_case, ...
    dry_info.joint.contract_terminal_backlog_cap_fraction, 0.1);
verifyEqual(test_case, ...
    dry_info.first_production.allowable_backlog_after_commit_kg, ...
    expected_backlog_kg, 'AbsTol', 1e-9);
verifyEqual(test_case, dry_info.first_production.commit_min_nh3_kg, ...
    0.9 * protocol.Contract.DailyQuantityKG, 'AbsTol', 1e-9);
end

function testContractTerminalClearanceRejectsOutOfRangeDays(test_case)
mat_path = [tempname, '.mat'];
cleanup = onCleanup(@() delete_if_file(mat_path));

params = my_system('s2');
renewable_data = synthetic_renewable_data(2022, 96);
run_info = struct('data_year', 2022);
save(mat_path, 'params', 'renewable_data', 'run_info');

verifyError(test_case, @() rolling_dispatch(struct( ...
    'source_mat_path', mat_path, ...
    'scheme', "contract_plan_and_hb_smoothing", ...
    'forecast_mode', "observed_oracle", ...
    'contract_terminal_clearance_days', 15, ...
    'dry_run', true, ...
    'save_output', false, ...
    'verbose', false)), ...
    'rolling_dispatch:bad_contract_terminal_clearance');

verifyError(test_case, @() rolling_dispatch(struct( ...
    'source_mat_path', mat_path, ...
    'scheme', "contract_plan_and_hb_smoothing", ...
    'forecast_mode', "observed_oracle", ...
    'contract_terminal_backlog_cap_fraction', -0.1, ...
    'dry_run', true, ...
    'save_output', false, ...
    'verbose', false)), ...
    'rolling_dispatch:bad_contract_terminal_backlog_cap');
end

function testDevelopmentFallbackIncludesResidualScenarioLibrary(test_case)
fallback = build_development_forecast_fallback();

verifyEqual(test_case, fallback.source_years, [2022, 2023]);
verifyTrue(test_case, isfield(fallback, 'residual_library'));
verifyTrue(test_case, istable(fallback.residual_library));
verifyTrue(test_case, all(ismember( ...
    {'resource', 'month', 'hour', 'residual_kw'}, ...
    fallback.residual_library.Properties.VariableNames)));
verifyEqual(test_case, unique(fallback.residual_library.resource), ...
    ["pv"; "pw"]);
verifyTrue(test_case, all(ismember( ...
    unique(fallback.residual_library.month), (1:12)')));
verifyTrue(test_case, all(ismember( ...
    unique(fallback.residual_library.hour), (1:24)')));
verifyGreaterThan(test_case, height(fallback.residual_library), 10000);
end

function testResidualScenarioForecastDryRunIsSeededAndAudited(test_case)
mat_path = [tempname, '.mat'];
cleanup = onCleanup(@() delete_if_file(mat_path));

params = my_system('s2');
params.AEL.common.startup = true;
renewable_data = synthetic_renewable_data(2024, 96);
run_info = struct('data_year', 2024);
save(mat_path, 'params', 'renewable_data', 'run_info');

fallback = synthetic_residual_fallback();
config = struct( ...
    'source_mat_path', mat_path, ...
    'forecast_mode', "simulated_residual_scenario", ...
    'forecast_fallback', fallback, ...
    'forecast_seed', 1234, ...
    'dry_run', true, ...
    'save_output', false, ...
    'verbose', false);

[~, first_run_info] = rolling_dispatch(config);
[~, second_run_info] = rolling_dispatch(config);

verifyEqual(test_case, first_run_info.status, "ready");
verifyEqual(test_case, first_run_info.forecast_mode, ...
    "simulated_residual_scenario");
verifyEqual(test_case, first_run_info.forecast_fallback_source, ...
    "external_development_years_2022_2023_residual_scenario");
verifyEqual(test_case, first_run_info.forecast.seed, 1234);
verifyEqual(test_case, first_run_info.forecast.residual_source_years, ...
    [2022, 2023]);
verifyEqual(test_case, first_run_info.first_forecast_pv_power_kw, ...
    second_run_info.first_forecast_pv_power_kw);
verifyEqual(test_case, first_run_info.first_forecast_pw_power_kw, ...
    second_run_info.first_forecast_pw_power_kw);
verifyGreaterThanOrEqual(test_case, ...
    min(first_run_info.first_forecast_pv_power_kw), 0);
verifyLessThanOrEqual(test_case, ...
    max(first_run_info.first_forecast_pv_power_kw), ...
    params.renewable.PV_capacity);
end

function testInfeasibilityClassifierIdentifiesRealtimeProjectionFailure(test_case)
record = struct();
record.run_info = struct( ...
    'status', "requires_slack_diagnosis", ...
    'failed_day', 2, ...
    'scheme', "economic_only", ...
    'forecast_mode', "simulated_persistence", ...
    'grid_accounting', "annual_cumulative_observed_budget", ...
    'error_id', "rolling_dispatch:solve_failed", ...
    'error_message', ...
        "realtime_production_projection solve failed or did not converge.");
record.failure_context = struct();
record.failure_context.day_index = 2;
record.failure_context.state = struct( ...
    'h2_kg', 3912.038, ...
    'ael_online_modules', 16, ...
    'hb_load', 0.8);
record.failure_context.actual_data = struct( ...
    'pv_power_kw', zeros(24, 1), ...
    'pw_power_kw', zeros(24, 1));

diagnosis = classify_infeasibility(record);

verifyEqual(test_case, diagnosis.status, "diagnosed");
verifyEqual(test_case, diagnosis.failure_day, 2);
verifyEqual(test_case, diagnosis.method, "rule_based_v1");
verifyTrue(test_case, any(diagnosis.categories == ...
    "renewable_absorption_recourse_binding"));
verifyTrue(test_case, any(diagnosis.categories == ...
    "ael_commitment_recourse_binding"));
verifyEqual(test_case, diagnosis.primary_category, ...
    "renewable_absorption_recourse_binding");
end

function testInfeasibilityClassifierSeparatesCarbonProjectionFromDebt(test_case)
record = struct();
record.run_info = struct( ...
    'status', "requires_slack_diagnosis", ...
    'failed_day', 354, ...
    'scheme', "contract_plan_and_hb_smoothing", ...
    'forecast_mode', "observed_oracle", ...
    'error_id', "rolling_dispatch:solve_failed", ...
    'error_message', ...
        "day_ahead_carbon_projection solve failed or did not converge.", ...
    'carbon_state', struct('debt_kg', -2.4e6));
record.failure_context = struct( ...
    'day_index', 354, ...
    'state', struct('h2_kg', 3912.038));

diagnosis = classify_infeasibility(record);

verifyEqual(test_case, diagnosis.primary_category, ...
    "carbon_reachability_projection_binding");
verifyTrue(test_case, any(diagnosis.categories == ...
    "carbon_reachability_projection_binding"));
verifyFalse(test_case, any(diagnosis.categories == ...
    "carbon_budget_binding"));
end

function delete_if_file(file_path)
if isfile(file_path)
    delete(file_path);
end
end

function delete_dir_if_exists(dir_path)
if isfolder(dir_path)
    rmdir(dir_path, 's');
end
end

function grid_table = synthetic_v52_selection_grid()
case_id = [ ...
    "baseline_joint_reference"; ...
    "oracle_best_diagnostic"; ...
    "failed_candidate"; ...
    "lcoa_fail"; ...
    "shortfall_fail"; ...
    "candidate_a"; ...
    "candidate_b"; ...
    "candidate_c"];
status = [ ...
    "completed"; ...
    "completed"; ...
    "failed"; ...
    "completed"; ...
    "completed"; ...
    "completed"; ...
    "completed"; ...
    "completed"];
is_baseline = [true; false; false; false; false; false; false; false];
scheme_name = [ ...
    "contract_plan_and_hb_smoothing"; ...
    "perfect_information_oracle_diagnostic"; ...
    "joint_contract_h2_trajectory_coordination"; ...
    "joint_contract_h2_trajectory_coordination"; ...
    "joint_contract_h2_trajectory_coordination"; ...
    "joint_contract_h2_trajectory_coordination"; ...
    "joint_contract_h2_trajectory_coordination"; ...
    "joint_contract_h2_trajectory_coordination"];
h2_reserve_quantile = [0; 0.95; 0.50; 0.75; 0.90; 0.50; 0.50; 0.50];
h2_reserve_lookahead_days = [0; 3; 1; 2; 3; 1; 1; 1];
contract_pacing_aggressiveness = [0; 0.50; 0.25; 0.25; 0.25; 0.25; 0.25; 0.25];
hb_smoothing_reduction_fraction = [0; 0.20; 0.05; 0.05; 0.05; 0.05; 0.05; 0.05];
contract_shortfall_p95_kg = [100; 1; 80; 80; 102; 90; 90; 90];
MAR = [0.20; 0.01; 0.18; 0.18; 0.18; 0.19; 0.18; 0.18];
h2_soc_p05 = [0.30; 0.80; 0.40; 0.40; 0.40; 0.40; 0.35; 0.45];
LCOA_USD_t = [1000; 1010; 1005; 1021; 1005; 1010; 1018; 1019];
strict_delivery_ok = [true; true; true; true; true; true; true; true];
terminal_contract_ok = [true; true; true; true; true; true; true; true];
annual_output_ok = [true; true; true; true; true; true; true; true];
terminal_h2_ok = [true; true; true; true; true; true; true; true];
annual_co2_ok = [true; true; true; true; true; true; true; true];
annual_sell_ok = [true; true; true; true; true; true; true; true];
annual_curtail_ok = [true; true; true; true; true; true; true; true];
lcoa_cap_ok = [true; true; true; true; true; true; true; true];

grid_table = table(case_id, status, is_baseline, scheme_name, ...
    h2_reserve_quantile, h2_reserve_lookahead_days, ...
    contract_pacing_aggressiveness, hb_smoothing_reduction_fraction, ...
    contract_shortfall_p95_kg, MAR, h2_soc_p05, LCOA_USD_t, ...
    strict_delivery_ok, terminal_contract_ok, annual_output_ok, ...
    terminal_h2_ok, annual_co2_ok, annual_sell_ok, annual_curtail_ok, ...
    lcoa_cap_ok);
end

function project_dir = project_root_for_tests()
test_dir = fileparts(mfilename('fullpath'));
project_dir = fileparts(test_dir);
end

function renewable_data = synthetic_renewable_data(data_year, hour_count)
time = (datetime(data_year, 1, 1, 0, 0, 0):hours(1): ...
    datetime(data_year, 1, 1, 0, 0, 0) + hours(hour_count - 1))';
renewable_data = struct( ...
    'time', time, ...
    'time_index', (1:hour_count)', ...
    'time_step_h', 1, ...
    'time_count', hour_count, ...
    'pv_power_kw', 1000 + (1:hour_count)', ...
    'pw_power_kw', 2000 + (1:hour_count)', ...
    'renewable_power_kw', 3000 + 2 * (1:hour_count)');
renewable_data.source = struct( ...
    'pv_capacity_kw', 200000, ...
    'pw_capacity_kw', 200000);
end

function fallback = synthetic_residual_fallback()
base = table();
base.resource = ["pv"; "pv"; "pw"; "pw"];
base.month = [1; 1; 1; 1];
base.hour = [1; 2; 1; 2];
base.residual_kw = [10; -20; 30; -40];
fallback = struct( ...
    'source_years', [2022, 2023], ...
    'pv_power_kw', (1:24)', ...
    'pw_power_kw', (101:124)', ...
    'residual_library', base);
end
