clear; clc; close all;

root_dir = "C:\Users\祁水\Desktop\风光氢氨系统\project\data\renewables_ninja";

PV_file = fullfile(root_dir, '2022PV.csv');
PW_file = fullfile(root_dir, '2022PW.csv');

%% 1. 读取数据
opts_PV = detectImportOptions(PV_file);
opts_PV = setvaropts(opts_PV, 1, ...
    'InputFormat', 'yyyy/MM/dd HH:mm');

opts_PW = detectImportOptions(PW_file);
opts_PW = setvaropts(opts_PW, 1, ...
    'InputFormat', 'yyyy-MM-dd HH:mm');

pv_data = readtable(PV_file, opts_PV);
pw_data = readtable(PW_file, opts_PW);

time_pv_utc = pv_data{:,1};
time_pw_utc = pw_data{:,1};

% 系统参数
installed_capacity_MW = 200;
derating_factor = 0.8623;

% 容量因子转换为实际功率
power_pv = pv_data{:,2} ...
    .* installed_capacity_MW ...
    .* derating_factor;

power_wt = pw_data{:,2} ...
    .* installed_capacity_MW ...
    .* derating_factor;

%% 2. UTC转换为北京时间
time_pv = time_pv_utc + hours(8);
time_wt = time_pw_utc + hours(8);

%% 3. 计算日平均功率
date_pv = dateshift(time_pv, 'start', 'day');
date_wt = dateshift(time_wt, 'start', 'day');

[g_pv, day_id_pv] = findgroups(date_pv);
[g_wt, day_id_wt] = findgroups(date_wt);

daily_pv_all = splitapply( ...
    @(x) mean(x, 'omitnan'), power_pv, g_pv);

daily_wt_all = splitapply( ...
    @(x) mean(x, 'omitnan'), power_wt, g_wt);

% 统计每天有效小时数
hour_count_pv = splitapply( ...
    @(x) sum(~isnan(x)), power_pv, g_pv);

hour_count_wt = splitapply( ...
    @(x) sum(~isnan(x)), power_wt, g_wt);

% 仅保留具有24个有效小时的完整日期
valid_pv = hour_count_pv == 24;
valid_wt = hour_count_wt == 24;

pv_days = day_id_pv(valid_pv);
wt_days = day_id_wt(valid_wt);

pv_values = daily_pv_all(valid_pv);
wt_values = daily_wt_all(valid_wt);

% 对齐风电和光伏日期
[common_days, idx_pv, idx_wt] = ...
    intersect(pv_days, wt_days);

daily_pv = pv_values(idx_pv);
daily_wt = wt_values(idx_wt);

% 当前研究年份
target_year = 2022;

idx_year = year(common_days) == target_year;

common_days = common_days(idx_year);
daily_pv = daily_pv(idx_year);
daily_wt = daily_wt(idx_year);

fprintf('完整北京时间日期数：%d\n', ...
    numel(common_days));

fprintf('PV日平均功率范围：%.3f–%.3f MW\n', ...
    min(daily_pv), max(daily_pv));

fprintf('WT日平均功率范围：%.3f–%.3f MW\n', ...
    min(daily_wt), max(daily_wt));

%% 4. 顶刊风格绘图
fig = figure( ...
    'Color', 'w', ...
    'Units', 'centimeters', ...
    'Position', [3, 3, 18, 8.8], ...
    'Renderer', 'painters');

ax = axes(fig);
hold(ax, 'on');

% Okabe–Ito色盲友好颜色
color_pv = [213, 94, 0] / 255;
color_wt = [0, 114, 178] / 255;

line_pv = plot(ax, common_days, daily_pv, ...
    '-', ...
    'Color', color_pv, ...
    'LineWidth', 1.15);

line_wt = plot(ax, common_days, daily_wt, ...
    '-', ...
    'Color', color_wt, ...
    'LineWidth', 1.15);

hold(ax, 'off');

%% 5. 坐标轴格式
month_ticks = datetime( ...
    target_year, 1:12, 15);

month_labels = {
    'Jan','Feb','Mar','Apr','May','Jun', ...
    'Jul','Aug','Sep','Oct','Nov','Dec'
};

set(ax, ...
    'FontName', 'Times New Roman', ...
    'FontSize', 10, ...
    'LineWidth', 0.9, ...
    'TickDir', 'out', ...
    'TickLength', [0.015, 0.015], ...
    'Box', 'on', ...
    'Layer', 'top', ...
    'XLim', [datetime(target_year,1,1), ...
             datetime(target_year+1,1,1)], ...
    'XTick', month_ticks, ...
    'XTickLabel', month_labels, ...
    'YLim', [0, 1.05 * max([daily_pv; daily_wt])], ...
    'XGrid', 'off', ...
    'YGrid', 'on', ...
    'GridColor', [0.35, 0.35, 0.35], ...
    'GridAlpha', 0.16, ...
    'GridLineStyle', '-');

xlabel(ax, 'Month', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 11);

ylabel(ax, 'Daily mean power (MW)', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 11);

%% 6. 图例
lgd = legend(ax, ...
    [line_pv, line_wt], ...
    {'Solar PV', 'Wind PW'}, ...
    'Location', 'northoutside', ...
    'Orientation', 'horizontal', ...
    'Box', 'off', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 10);

lgd.ItemTokenSize = [18, 8];
