function protocol = protocol_v5(action, value)
%PROTOCOL_V5 Frozen research boundary before the new forecast-dispatch study.

if nargin > 0 && ~isempty(action)
    if nargin < 2
        value = [];
    end
    protocol = protocol_v5_dispatch(action, value);
    return
end

baseline = s2_baseline_manifest();

protocol = struct();
protocol.ProtocolVersion = "5.0.0";
protocol.FreezeDate = "2026-08-21";
protocol.FreezeStage = "research_boundary_and_s2_baseline";
protocol.Classification = "result_informed_prospective_boundary_protocol";
protocol.RegistrationStatus = ...
    "boundary_frozen_confirmatory_analysis_not_yet_complete";

protocol.EvidenceAudit = struct( ...
    'V4SelectionResultsInspected', true, ...
    'S2Dispatch2022Inspected', true, ...
    'NewForecastResultsInspected', false, ...
    'NewSchedulingResultsInspected', false, ...
    'IsFullyOutcomeBlind', false, ...
    'IsProspectiveForNewContribution', true);

protocol.ResearchBoundary = struct( ...
    'System', "fixed_capacity_wind_solar_hydrogen_ammonia", ...
    'BaselineScenario', "Zhou_S2_continuous_flexible_operation", ...
    'Contribution', ...
        "forecast_error_driven_h2_reserve_and_contract_ammonia_coordination", ...
    'Formulation', "hierarchical_dual_time_scale_coordinated_optimization", ...
    'UpperScale', "daily_contract_and_terminal_h2_targets", ...
    'LowerScale', "hourly_physical_economic_MILP_dispatch", ...
    'ExcludedClaims', [ ...
        "full_Zhou_capacity_optimization_replication"; ...
        "mathematical_bilevel_program_without_nested_response"; ...
        "universal_complete_ammonia_stability_index"; ...
        "outcome_blind_metric_selection"], ...
    'FixedCapacityDuringComparison', true, ...
    'FixedAnnualContractAcrossSchemes', true);

protocol.Data = struct( ...
    'DevelopmentYears', [2022, 2023], ...
    'CalibrationYear', 2024, ...
    'HoldoutYear', 2025, ...
    'DataType', "Renewables_ninja_MERRA2_deterministic_hindcast", ...
    'ForecastClaimLimit', "simulated_forecast_environment", ...
    'HoldoutStatus', "analysis_locked_not_strictly_blind", ...
    'StrictHoldoutBlinding', false, ...
    'LimitedRawHoldoutExposureDisclosed', true, ...
    'HoldoutUsedForMetricSelection', false, ...
    'ExternalConfirmationRequired', true, ...
    'ExternalConfirmationTarget', "unseen_year_or_independent_station");

protocol.Assumptions = struct( ...
    'ForecastInformation', "day_ahead_renewable_information_only", ...
    'ContractDemand', "external_and_not_dispatch_decision", ...
    'AnnualContractClosure', "terminal_backlog_equals_zero", ...
    'HydrogenPhysicalFloor', "pressure_derived_inventory_always_enforced", ...
    'HydrogenReserveTarget', ...
        "future_cumulative_h2_deficit_quantile_not_fixed_soc", ...
    'HBStateInS2', "always_online_due_to_positive_minimum_load", ...
    'CommonComparisonBasis', ...
        "same_capacity_data_information_contract_and_solver_tolerance");

protocol.Schemes = [ ...
    "economic_only"; ...
    "fixed_working_soc_reserve"; ...
    "forecast_driven_h2_reserve"; ...
    "contract_plan_and_hb_smoothing"; ...
    "joint_contract_h2_trajectory_coordination"; ...
    "perfect_information_oracle_diagnostic"];

protocol.Hypotheses = struct( ...
    'DirectionsFrozen', true, ...
    'Statements', [ ...
        "contract_planning_reduces_contract_shortfall_and_MAR"; ...
        "adaptive_reserve_improves_equal_cost_or_equal_risk_h2_security"; ...
        "joint_coordination_produces_a_nondominated_economic_risk_tradeoff"], ...
    'NumericSuperiorityThresholdsFrozen', false, ...
    'ThresholdStatus', "must_be_frozen_in_v5_1_before_new_results");

protocol.OutcomeRegistry = create_outcome_registry();
protocol.DecisionPrinciples = struct( ...
    'PrimaryComparison', "equal_annual_contract_and_common_physics", ...
    'TradeoffReporting', "equal_cost_risk_and_equal_risk_cost", ...
    'NoSingleMetricOptimizationClaim', true, ...
    'Known2022ValuesCannotDefineGates', true, ...
    'NoThresholdRelaxationAfterNewResults', true);

protocol.KnownS2Observation2022 = struct( ...
    'Status', "descriptive_known_before_v5_freeze", ...
    'UseAsAcceptanceThreshold', false, ...
    'UseForParameterTuningAfterFreeze', false, ...
    'FullRegressionDate', "2026-08-21", ...
    'ReproducedAfterParameterExternalization', true, ...
    'ObjectiveCostMinusRevenueUsd', -6980408.184133, ...
    'SolverRelativeGap', 9.9881e-5, ...
    'NH3ProductionTPerYear', 7.602e4, ...
    'DailyCumulativeVariabilityPercent', 17.28, ...
    'AELUtilizationHours', 5855.73, ...
    'AELStartupCount', 488, ...
    'AELStartupElectricityMWh', 366, ...
    'GridSellPercent', 14.8276, ...
    'CurtailmentPercent', 0.0006, ...
    'GridPurchasePercent', 0.9702, ...
    'CarbonIntensityKgPerKg', 0.070451, ...
    'LCOAUsdPerT', 465.18, ...
    'AnnualNetProfitUsd', 6.980e6, ...
    'PhysicalPressureFloorViolationHours', 0, ...
    'WorkingSOCBelow20PercentHours', 4935);

protocol.BaselineManifestSeal = baseline.Seal;
protocol.PendingSubprotocols = [ ...
    "forecast_model_features_hyperparameters_and_error_scenarios"; ...
    "contract_backlog_bounds_and_delay_definition"; ...
    "adaptive_reserve_quantile_window_and_risk_budget"; ...
    "epsilon_grid_statistical_tests_and_multiplicity_control"; ...
    "missing_data_solver_failure_and_holdout_opening_rules"];
protocol.ChangeControl = ...
    "append_only_v5_1_before_new_model_or_2025_outcomes";
expected_seal = "6B71CCF0";
computed_seal = checksum_value(protocol);
if computed_seal ~= expected_seal
    error('protocol_v5:seal_drift', ...
        'Frozen Protocol v5 drifted: expected %s, computed %s.', ...
        expected_seal, computed_seal);
end
protocol.Seal = expected_seal;
end

function registry = create_outcome_registry()
registry = repmat(struct( ...
    'Name', "", 'Role', "", 'Direction', "", 'Origin', "", ...
    'Interpretation', ""), 10, 1);

registry(1) = outcome("contract_shortfall_p95", "primary_outcome", ...
    "smaller_is_better", "mechanism_defined_after_baseline_diagnosis", ...
    "contract_lower_tail_shortfall");
registry(2) = outcome("mar", "primary_outcome", "smaller_is_better", ...
    "v4_data_selected_result_informed", "hourly_hb_dynamic_variation");
registry(3) = outcome("h2_soc_p05", "primary_outcome", "larger_is_better", ...
    "v4_data_selected_result_informed", "working_inventory_lower_tail_reserve");
registry(4) = outcome("daily_shortfall_p95", ...
    "legacy_descriptive_outcome", "smaller_is_better", ...
    "v4_data_selected_result_informed", ...
    "lower_tail_balance_not_contract_violation");
registry(5) = outcome("h2_low_reserve_hours", "secondary_outcome", ...
    "smaller_is_better", "mechanism_defined_after_baseline_diagnosis", ...
    "reserve_risk_frequency");
registry(6) = outcome("h2_longest_low_reserve_run", "secondary_outcome", ...
    "smaller_is_better", "mechanism_defined_after_baseline_diagnosis", ...
    "reserve_risk_duration");
registry(7) = outcome("h2_max_reserve_deficit", "secondary_outcome", ...
    "smaller_is_better", "mechanism_defined_after_baseline_diagnosis", ...
    "reserve_risk_depth");
registry(8) = outcome("maximum_contract_backlog", "feasibility_outcome", ...
    "smaller_is_better", "contract_state_definition", ...
    "maximum_deferred_contract_quantity");
registry(9) = outcome("terminal_contract_backlog", "hard_constraint", ...
    "must_equal_zero", "contract_state_definition", ...
    "annual_contract_closure");
registry(10) = outcome("switch_count", "excluded_for_s2", ...
    "not_applicable", "v4_data_selected_then_real_model_audited", ...
    "structurally_non_identifiable_hb_always_online");
end

function item = outcome(name, role, direction, origin, interpretation)
item = struct('Name', name, 'Role', role, 'Direction', direction, ...
    'Origin', origin, 'Interpretation', interpretation);
end

function output = protocol_v5_dispatch(action, value)
if isstring(action) && isscalar(action)
    action = char(action);
end
if ~ischar(action)
    error('protocol_v5:bad_action', ...
        ['action must be verify, checksum, v5_1, verify_v5_1, ', ...
        'v5_2, or verify_v5_2.']);
end

switch lower(strtrim(action))
    case 'verify'
        output = verify_protocol(value);
    case 'checksum'
        output = checksum_value(value);
    case 'v5_1'
        output = create_protocol_v5_1();
    case 'verify_v5_1'
        output = verify_protocol_v5_1(value);
    case 'v5_2'
        output = create_protocol_v5_2();
    case 'verify_v5_2'
        output = verify_protocol_v5_2(value);
    otherwise
        error('protocol_v5:bad_action', ...
            ['action must be verify, checksum, v5_1, verify_v5_1, ', ...
            'v5_2, or verify_v5_2.']);
end
end

function is_valid = verify_protocol(protocol)
is_valid = isstruct(protocol) && isfield(protocol, 'Seal') && ...
    isfield(protocol, 'ProtocolVersion') && ...
    string(protocol.ProtocolVersion) == "5.0.0" && ...
    string(protocol.Seal) == checksum_value(protocol);
end

function subprotocol = create_protocol_v5_1()
parent = protocol_v5();

stage1_mat_annual_output_t = 76022.9642746094;
frozen_annual_contract_t = 76022.964275;
frozen_daily_contract_kg = frozen_annual_contract_t * 1000 / 365;
max_delay_days = 7;

subprotocol = struct();
subprotocol.ProtocolVersion = "5.1.37";
subprotocol.ParentProtocolVersion = parent.ProtocolVersion;
subprotocol.ParentProtocolSeal = parent.Seal;
subprotocol.FreezeDate = "2026-08-24";
subprotocol.FreezeStage = ...
    "oracle_closure_after_persistence_bias_diagnostic";
subprotocol.ChangeControl = ...
    "user_authorized_scientific_annual_closure_corrections";

subprotocol.ConfirmedUserDecisions = struct( ...
    'KeepTwoProtocolFiles', true, ...
    'NoSeparateTestFile', true, ...
    'ForecastMode', "simulated_until_real_forecast_available", ...
    'UseRealForecastThroughSameInterface', true, ...
    'ExcludeBiasedSimulationFromConfirmatoryClaims', true, ...
    'ContractDelayDays', max_delay_days, ...
    'NoEarlyDeliveryCredit', true, ...
    'ExistingAssetsOnly', true, ...
    'NoAmmoniaStorage', true, ...
    'FreezeStage1MatOutputAsContract', true, ...
    'StopCapacitySearchAtFrozenContract', true, ...
    'StrictFIFODelivery', true, ...
    'PlanningHours', 72, ...
    'CommitHours', 24, ...
    'FixedHBAndAELCommitmentRecourse', true, ...
    'ApproveDispatchModelFile', true, ...
    'ApproveRollingDispatchFile', true, ...
    'AnnualCumulativeCarbonBudget', true, ...
    'NoIndependentDailyCarbonCap', true, ...
    'ContractAnchoredCarbonEnvelope', true, ...
    'DailyReachabilityCheckpoints', true, ...
    'AdaptiveCarbonReserve', true, ...
    'RecoursePurchaseExposureReserve', true, ...
    'LexicographicHBDownwardRecourse', true, ...
    'CarbonStateConsistentRecourse', true, ...
    'OneStepCarbonViabilityBuffer', true, ...
    'FeasibleCarbonBufferProjection', true, ...
    'DownwardAELCommitmentRecourse', true, ...
    'SchemeConsistentCarbonReference', true, ...
    'DayAheadReserveFeasibleProjection', true, ...
    'RealtimeInheritsAppliedDayAheadReserve', true, ...
    'AbsoluteAnnualEmissionsBudgetForEconomicOnly', true, ...
    'BankableCarbonBudgetWithBoundedBorrowing', true, ...
    'FourteenDayCarbonBorrowingAfterDiagnostic', true, ...
    'RejectBiasedPersistenceForClosure', true, ...
    'DevelopmentOracleNotForecastClaim', true, ...
    'AnnualProductionPacing', true, ...
    'ProductionReferenceGovernor', true, ...
    'HydrogenNeutralReserveWithinBankedBudget', true, ...
    'PlanningHorizonPhysicalCarbonReserve', true, ...
    'RestartViableHydrogenHandoff', true, ...
    'DisableDefaultStatisticalCarbonReserve', true, ...
    'AnnualCumulativeSellCurtailBudgets', true, ...
    'NoIndependentDailySellCurtailCaps', true, ...
    'ObservedRenewableGridBudgets', true);

subprotocol.DataSplit = struct( ...
    'DevelopmentYears', [2022, 2023], ...
    'CalibrationYear', 2024, ...
    'HoldoutYear', 2025, ...
    'HoldoutOpeningRule', ...
        "open_once_after_v5_1_verifies_and_all_code_paths_are_frozen", ...
    'NoHoldoutTuning', true);

subprotocol.Forecast = create_forecast_protocol();
subprotocol.Contract = struct( ...
    'AnnualQuantitySource', ...
        "stage1_2022_mat_actual_NH3_output_rounded_6dp_verified_feasible", ...
    'ReferenceAnnualQuantitySource', ...
        "stage1_2022_mat_baseline_actual_NH3_output", ...
    'ReferenceAnnualQuantityT', stage1_mat_annual_output_t, ...
    'AnnualQuantityT', frozen_annual_contract_t, ...
    'AnnualQuantityRoundingDecimals', 6, ...
    'DailyQuantityKG', frozen_daily_contract_kg, ...
    'CapacitySearchRole', ...
        "diagnostic_only_not_contract_selection", ...
    'BacklogStateUnit', "kg_NH3", ...
    'MaxDelayDays', max_delay_days, ...
    'MaxBacklogFormula', "max_delay_days*daily_contract_kg", ...
    'TerminalBacklogKG', 0, ...
    'BacklogUpdate', ...
        "B_d=max(0,B_{d-1}+daily_contract_kg-daily_NH3_kg)", ...
    'ProductionAboveDailyContractRecoversBacklog', true, ...
    'NoEarlyDeliveryCredit', true, ...
    'ContractIsExogenousNotDispatchDecision', true);

subprotocol.ContractCapacityOptimization = struct( ...
    'Status', "stopped_after_frozen_contract_verified", ...
    'Role', "diagnostic_only_not_contract_selection", ...
    'EquipmentScope', "existing_Zhou_S2_assets_only", ...
    'PrimaryObjective', ...
        "verify_frozen_stage1_mat_contract_feasibility", ...
    'SecondaryObjective', ...
        "minimize_annual_cost_minus_revenue_at_frozen_contract", ...
    'ObjectiveMethod', ...
        "fixed_contract_economic_feasibility_certificate", ...
    'FrozenAnnualQuantityT', frozen_annual_contract_t, ...
    'FrozenDailyQuantityKG', frozen_daily_contract_kg, ...
    'InitialCandidatesAnnualT', ...
        [70e3; 73e3; frozen_annual_contract_t], ...
    'ContractBracketRelativeTolerance', 0.005, ...
    'BaselineLCOASource', "stage1_2022_mat_result_summary_lcoa", ...
    'MaxLCOAIncreaseFraction', 0.02, ...
    'WarmStartSource', ...
        "stage1_or_prior_feasible_candidate_dispatch", ...
    'EconomicRelativeGapTolerance', 1e-4, ...
    'TimeoutWithIncumbentProvesFeasibilityOnly', true, ...
    'TimeoutWithoutIncumbentIsUnresolved', true, ...
    'InfeasibleCandidateRequiresSlackDiagnosis', true, ...
    'NoContractSlack', true, ...
    'TerminalBacklogMustBeZero', true);

subprotocol.ContractFeasibilityCertificate = struct( ...
    'ResultFile', ...
        "runs/stage3/v51_contract_candidate_076022p964t_2022_latest.mat", ...
    'SourceProtocolVersion', "5.1.3", ...
    'SourceProtocolSeal', "98AB91E8", ...
    'DataYear', 2022, ...
    'AnnualContractT', frozen_annual_contract_t, ...
    'DailyContractKG', frozen_daily_contract_kg, ...
    'Status', "feasible_economic_optimum", ...
    'ActualAnnualProductionT', 78194.835018008060, ...
    'LCOAUSDPerT', 469.05235868116608, ...
    'LCOAIncreaseFraction', 0.0083238491904971124, ...
    'NetProfitUSD', 6877051.3031491712, ...
    'PurchaseRate', 0.034105853292563319, ...
    'CO2IntensityKGPerKGNH3', 0.24077861774259146, ...
    'MaximumBacklogKG', 1457974.6573287677, ...
    'MaximumBacklogEqualsSevenDayLimit', true, ...
    'TerminalBacklogKG', 5.8207660913467407e-11, ...
    'SolverRelativeGap', 9.9839634878107e-05, ...
    'NoMaximumCapacityClaim', true);

subprotocol.RollingDispatch = struct( ...
    'PlanningHours', 72, ...
    'CommitHours', 24, ...
    'ReplanIntervalHours', 24, ...
    'MaxTimeSecondsPerSolve', 180, ...
    'RelativeGapTolerance', 1e-3, ...
    'ConstraintTolerance', 1e-5, ...
    'MeasuredDifficultWindowSeconds', 121.081, ...
    'Day58GapAt60Seconds', 0.000421193054, ...
    'StrictContractCohorts', true, ...
    'ContractDeliveryRule', ...
        "each_daily_obligation_delivered_on_due_day_through_due_day_plus_7", ...
    'TerminalH2Rule', ...
        "nonfinal_handoff_preserves_window_initial_and_one_step_HB_hydrogen", ...
    'YearEndH2Rule', "equal_annual_initial_storage", ...
    'ReachabilityCheckpoints', struct( ...
        'IntervalHours', 24, ...
        'AppliesTo', ["carbon"; "sell"; "curtail"], ...
        'Rule', ...
            "day_ahead_plan_must_satisfy_each_committed_day_boundary"), ...
    'CarbonReserve', struct( ...
        'Method', "expanding_recourse_purchase_exposure_quantile", ...
        'DefaultQuantileByScheme', struct( ...
            'economic_only', 0, ...
            'contract_plan_and_hb_smoothing', 0), ...
        'Role', "physical_feasibility_floor_with_optional_statistical_sensitivity", ...
        'ErrorDefinition', ...
            "positive_part_of_realtime_minus_day_ahead_grid_purchase_kwh", ...
        'FiniteSampleRank', "ceil((n+1)*quantile)_capped_at_n", ...
        'TrainingWindow', "completed_realtime_recourse_days_only", ...
        'ApplyTo', "first_24_hour_day_ahead_carbon_checkpoint", ...
        'FeasibilityProjection', ...
            "clip_requested_reserve_to_maximum_day_ahead_feasible_margin", ...
        'MinimumPhysicalReserve', struct( ...
            'Status', "active_with_bankable_bounded_borrowing_budget", ...
            'Active', true, ...
            'AppliesTo', "economic_only_until_penultimate_day", ...
            'HorizonHours', 72, ...
            'Definition', ...
                "zero_renewable_72h_HB_minimum_load_with_hydrogen_neutral_AEL", ...
            'EnergyMWh', 2703.292060647, ...
            'CO2KG', 1541687.462187024, ...
            'CombineRule', "maximum_of_statistical_and_physical_reserve", ...
            'FinalDayRelease', true), ...
        'RealtimeReserve', false, ...
        'NoFutureLeakage', true), ...
    'RealtimeRecourse', struct( ...
        'FixedPlan', ["HB_load"; "AEL_commitment"], ...
        'HBTargetRule', ...
            "strict_replay_then_downward_only_if_strict_replay_infeasible", ...
        'AELTargetRule', ...
            "strict_replay_then_downward_only_if_strict_replay_infeasible", ...
        'HBFallbackObjective', ...
            "lexicographic_maximum_feasible_buffer_then_minimum_nh3_deviation_then_economic_cost", ...
        'CarbonStateRule', ...
            "inherit_applied_day_ahead_reserve_then_project_to_realtime_feasible_set", ...
        'AdjustableControls', [ ...
            "HB_downward_on_hard_infeasibility"; ...
            "AEL_commitment_downward_on_hard_infeasibility"; ...
            "AEL_power"; ...
            "grid_purchase"; ...
            "grid_sale"; ...
            "curtailment"], ...
        'RejectEmergencySlack', true, ...
        'InfeasibleAction', "save_slack_diagnosis_and_stop"), ...
    'CarbonAccounting', struct( ...
        'Accounting', "scheme_specific_annual_cumulative", ...
        'StateVariables', [ ...
            "cumulative_grid_emissions_kg"; ...
            "cumulative_nh3_kg"], ...
        'IntermediateRule', ...
            "economic_scheduled_emissions_and_cumulative_output_pacing_or_contract_carbon_debt", ...
        'RemainingNH3Reference', ...
            "economic_uses_cumulative_common_output_schedule_and_contract_uses_frozen_quantity", ...
        'ReferenceByScheme', struct( ...
            'economic_only', ...
                "co2_limit_times_frozen_stage1_mat_annual_nh3", ...
            'contract_plan_and_hb_smoothing', ...
                "remaining_frozen_contract_quantity"), ...
        'EconomicBudgetSchedule', struct( ...
            'AnnualBudgetKG', 0.3 * frozen_annual_contract_t * 1000, ...
            'Accrual', "linear_over_8760_hours", ...
            'UnusedBudgetBankable', true, ...
            'MaximumBorrowingDays', 14, ...
            'DiagnosticMinimumBorrowingDays', 12.600081137, ...
            'DefaultStatisticalReserveQuantile', 0, ...
            'IndependentDailyCap', false), ...
        'PhysicalRecoveryFactorStatus', ...
            "superseded_by_cumulative_annual_output_pacing", ...
        'AnnualProductionSchedule', struct( ...
            'TargetKG', frozen_annual_contract_t * 1000, ...
            'StartupGraceDays', 7, ...
            'ScheduledDays', 358, ...
            'EarlyProductionBankable', true, ...
            'IndependentDailyTarget', false, ...
            'EnforcementBoundaryHours', 24, ...
            'PlanningTailTarget', false, ...
            'IntermediateProjection', ...
                "maximum_feasible_commitment_output", ...
            'UnmetProgressCarriesForward', true, ...
            'YearEndProjection', false), ...
        'ReachabilityMeaning', ...
            "economic_cumulative_output_pacing_with_14_day_emissions_borrowing_and_contract_declining_reachability", ...
        'YearEndRule', ...
            "cumulative_emissions_not_above_limit_times_cumulative_nh3", ...
        'IndependentDailyIntensityCap', false, ...
        'RejectCarbonSlack', true, ...
        'DailyCapDiagnosticFailureDay', 2, ...
        'DiagnosticMinimumDailyIntensity', 0.882171635, ...
        'DiagnosticDailyLimit', 0.3, ...
        'PhysicalEnvelopeDiagnosticFailureDay', 157, ...
        'PhysicalEnvelopeDay156MarginKG', 89835.836352, ...
        'PhysicalEnvelopeDay156CarbonDebtKG', 17088246.355429, ...
        'ForecastReserveDiagnosticFailureDay', 130, ...
        'ForecastOverestimateMWh', 1963.629560, ...
        'MinimumExtraPurchaseMWh', 649.980251434, ...
        'RequiredCarbonReserveEquivalentMWh', 509.071249293, ...
        'DiagnosticConclusion', ...
            "physical_max_recovery_reference_deferred_carbon_control_until_no_recourse_margin_remained"), ...
    'GridAccounting', struct( ...
        'Accounting', "annual_cumulative_observed_budget", ...
        'StateVariables', [ ...
            "cumulative_sell_kwh"; ...
            "cumulative_curtail_kwh"; ...
            "cumulative_renewable_kwh"], ...
        'SellLimitFraction', 0.20, ...
        'CurtailLimitFraction', 0.10, ...
        'IndependentBudgets', true, ...
        'IntermediateRule', ...
            "cumulative_energy_not_above_fraction_times_observed_and_current_forecast_renewable", ...
        'UnusedAllowanceBankable', true, ...
        'FutureActualRenewableCredit', false, ...
        'IndependentDailyCap', false, ...
        'YearEndRule', ...
            "sell_and_curtail_each_not_above_fraction_times_annual_renewable", ...
        'RejectGridBudgetSlack', true, ...
        'DiagnosticFailureDay', 10, ...
        'DiagnosticUnallocatedEnergyMWh', 1095.560804));

subprotocol.Schemes = create_scheme_registry();
subprotocol.OutcomeDefinitions = create_v5_1_outcomes();
subprotocol.Calibration = struct( ...
    'CandidateGrid', create_candidate_grid(), ...
    'SelectionYear', 2024, ...
    'SelectionRule', ...
        "lexicographic_primary_outcomes_under_two_percent_lcoa_cap", ...
    'LexicographicOrder', [ ...
        "contract_shortfall_p95"; ...
        "mar"; ...
        "h2_soc_p05"; ...
        "lcoa"], ...
    'ReportFullGrid', true);

subprotocol.SuperiorityRules = struct( ...
    'MaterialRiskImprovementFraction', 0.10, ...
    'MaxLCOAIncreaseFraction', 0.02, ...
    'ImprovementClaimRule', ...
        "risk_claim_requires_at_least_10_percent_primary_risk_improvement_and_no_more_than_2_percent_lcoa_increase", ...
    'NondominatedClaimRule', ...
        "joint_scheme_claim_is_allowed_only_if_no_compared_scheme_is_better_in_all_primary_risk_and_lcoa_dimensions");

subprotocol.FailureRules = struct( ...
    'InfeasibleDispatch', "report_infeasible_with_first_failed_hard_constraint", ...
    'SolverGapAboveTolerance', "mark_incomplete_no_superiority_claim", ...
    'MissingForecastRows', "reject_dataset_before_dispatch", ...
    'SchemaBreakingRealForecast', ...
        "do_not_compare_against_simulated_results_until_adapter_passes_schema_validation", ...
    'SimulationBiasDetected', ...
        "label_as_simulation_only_and_exclude_from_confirmatory_claims", ...
    'HoldoutRuleViolation', ...
        "invalidate_2025_confirmatory_status_and_report_as_exploratory");

expected_seal = "000CDCA8";
computed_seal = checksum_value(subprotocol);
if computed_seal ~= expected_seal
    error('protocol_v5:v5_1_seal_drift', ...
        'Frozen Protocol v5.1 drifted: expected %s, computed %s.', ...
        expected_seal, computed_seal);
end
subprotocol.Seal = expected_seal;
end

function forecast = create_forecast_protocol()
forecast = struct();
forecast.Mode = "simulated_day_ahead_with_real_forecast_schema";
forecast.RealForecastInterface = struct( ...
    'RequiredFields', [ ...
        "issue_time_utc"; ...
        "target_time_utc"; ...
        "horizon_hour"; ...
        "pv_power_kw"; ...
        "pw_power_kw"; ...
        "pv_capacity_kw"; ...
        "pw_capacity_kw"; ...
        "source_id"], ...
    'TimeZone', "UTC", ...
    'PowerUnit', "kW", ...
    'RequiredResolutionHours', 1, ...
    'RequiredHorizons', 1:72, ...
    'OneIssuePerOperatingDay', true, ...
    'NoObservedTargetPowerInForecastFields', true);
forecast.SimulatedGenerator = struct( ...
    'DeterministicCore', "day_ahead_persistence_no_future_leakage", ...
    'FirstDayFallback', "development_year_month_hour_median", ...
    'ResidualLibraryYears', [2022, 2023], ...
    'ResidualGrouping', "resource_month_hour", ...
    'ScenarioUse', "calibration_uncertainty_only_not_claimed_real_forecast", ...
    'NoHoldoutFitting', true);
forecast.DevelopmentOracle = struct( ...
    'Mode', "observed_oracle", ...
    'AllowedYears', [2022, 2023], ...
    'Role', "functional_closure_and_perfect_information_upper_bound", ...
    'OperationalForecastClaim', false, ...
    'HoldoutUseForbidden', true);
forecast.BiasGuard = struct( ...
    'SimulationClaimLimit', "simulation_environment_only", ...
    'RealForecastReplacementMustUseSameSchema', true, ...
    'ExcludeIfRealForecastRequiresDifferentDispatchInputs', true, ...
    'ExcludeIfSimulationChangesFeasibilityOrMaterialRanking', true);
end

function schemes = create_scheme_registry()
schemes = [
    scheme("economic_only", false, false, false, false, false)
    scheme("fixed_working_soc_reserve", false, false, true, false, false)
    scheme("forecast_driven_h2_reserve", true, false, true, false, false)
    scheme("contract_plan_and_hb_smoothing", false, true, false, true, false)
    scheme("joint_contract_h2_trajectory_coordination", ...
        true, true, true, true, false)
    scheme("perfect_information_oracle_diagnostic", ...
        true, true, true, true, true)];
end

function item = scheme(name, uses_forecast, uses_contract, ...
    uses_reserve, uses_smoothing, is_oracle)
item = struct( ...
    'Name', name, ...
    'UsesForecast', uses_forecast, ...
    'UsesContractBacklog', uses_contract, ...
    'UsesHydrogenReserveTarget', uses_reserve, ...
    'UsesHBSmoothing', uses_smoothing, ...
    'DiagnosticOracleOnly', is_oracle);
end

function outcomes = create_v5_1_outcomes()
outcomes = [
    v51_outcome("contract_shortfall_p95", "primary", "kg_NH3", ...
        "prctile(daily_positive_contract_backlog_kg,95)")
    v51_outcome("mar", "primary", "fraction_per_hour", ...
        "mean(abs(diff(HB_load_fraction))) for S2 always-online hours")
    v51_outcome("h2_soc_p05", "primary", "fraction", ...
        "prctile(working_h2_inventory_soc,5)")
    v51_outcome("lcoa", "economic", "USD_per_t_NH3", ...
        "annualized_total_cost_minus_non_ammonia_revenue_per_NH3_t")
    v51_outcome("maximum_contract_backlog", "hard_feasibility", ...
        "kg_NH3", "max(daily_contract_backlog_kg)")
    v51_outcome("terminal_contract_backlog", "hard_feasibility", ...
        "kg_NH3", "contract_backlog_kg(end)")];
end

function item = v51_outcome(name, role, unit, formula)
item = struct('Name', name, 'Role', role, 'Unit', unit, ...
    'Formula', formula);
end

function grid = create_candidate_grid()
grid = struct();
grid.ReserveQuantile = [0.50, 0.75, 0.90, 0.95];
grid.ReserveLookaheadDays = [1, 2, 3];
grid.LCOAEpsilonFraction = [0, 0.005, 0.01, 0.02];
grid.HBSmoothingTargetReductionFraction = [0, 0.05, 0.10, 0.20];
end

function is_valid = verify_protocol_v5_1(subprotocol)
is_valid = isstruct(subprotocol) && isfield(subprotocol, 'Seal') && ...
    isfield(subprotocol, 'ProtocolVersion') && ...
    string(subprotocol.ProtocolVersion) == "5.1.37" && ...
    string(subprotocol.Seal) == checksum_value(subprotocol);
end

function protocol = create_protocol_v5_2()
parent = protocol_v5('v5_1');

protocol = struct();
protocol.ProtocolVersion = "5.2.0";
protocol.ParentProtocolVersion = parent.ProtocolVersion;
protocol.ParentProtocolSeal = parent.Seal;
protocol.FreezeDate = "2026-08-26";
protocol.FreezeStage = "claim_selection_and_holdout_boundary";
protocol.ChangeControl = ...
    "append_only_before_2024_selection_or_2025_holdout_execution";

protocol.MainClaim = struct( ...
    'ClaimType', "cost_bounded_stability_noninferiority", ...
    'OneSentence', ...
        ["Under fixed Zhou S2 assets and a fixed annual ammonia ", ...
        "contract, joint contract pacing, forecast-driven hydrogen ", ...
        "reserve, and HB smoothing are tested for lower contract ", ...
        "tail risk, lower HB ramping, and higher lower-tail H2 ", ...
        "inventory without more than a 2 percent LCOA increase."], ...
    'ReferenceSystem', ...
        "fixed_capacity_wind_solar_hydrogen_ammonia_Zhou_S2", ...
    'KeyVariables', [ ...
        "h2_reserve_quantile"; ...
        "contract_pacing_aggressiveness"; ...
        "hb_smoothing_reduction_fraction"], ...
    'AllowsUniversalStabilityIndexClaim', false, ...
    'AllowsMaximumCapacityClaim', false, ...
    'AllowsRealForecastPerformanceClaim', false, ...
    'AllowsOracleAsMainEvidence', false);

protocol.DataSplit = struct( ...
    'DevelopmentYears', parent.DataSplit.DevelopmentYears, ...
    'SelectionYear', 2024, ...
    'HoldoutYear', 2025, ...
    'HoldoutUsedForSelection', false, ...
    'NoHoldoutTuning', true, ...
    'HoldoutOpeningRule', ...
        "open_once_after_v5_2_protocol_tests_and_quality_gate_pass", ...
    'SelectionUsesOnlyCalibrationYear', true);

protocol.Schemes = create_v5_2_scheme_registry(parent.Schemes);
protocol.PrimaryOutcomes = create_v5_2_primary_outcomes();
protocol.SecondaryOutcomes = [ ...
    "maximum_contract_backlog"; ...
    "terminal_contract_backlog"; ...
    "h2_low_reserve_hours"; ...
    "h2_longest_low_reserve_run"; ...
    "h2_max_reserve_deficit"; ...
    "co2_kg_per_kg"; ...
    "purchase_rate"; ...
    "sell_rate"; ...
    "curtail_rate"];

protocol.SuccessCriteria = struct( ...
    'MaxLCOAIncreaseFraction', 0.02, ...
    'ContractShortfallP95RelativeNoninferiorityMargin', 0.01, ...
    'MinimumMaterialImprovementFraction', 0.10, ...
    'H2SOCP05MinimumAbsoluteGain', 0, ...
    'HardFeasibilityRequired', true, ...
    'SolverStatusMustBeComplete', true);

protocol.SelectionRule = struct( ...
    'SelectionDataset', "calibration_year_2024_only", ...
    'Method', "filter_then_lexicographic_sort", ...
    'EligibilityFilters', [ ...
        "status_completed"; ...
        "hard_feasibility_passed"; ...
        "lcoa_increase_fraction_le_0p02"; ...
        "contract_shortfall_p95_not_worse_than_reference_by_1pct"], ...
    'SortOrder', [ ...
        "contract_shortfall_p95"; ...
        "mar"; ...
        "h2_soc_p05_desc"; ...
        "lcoa"], ...
    'TieBreakRule', "lower_lcoa_then_lower_case_id", ...
    'ReportFullGrid', true, ...
    'NoMetricWeightRetuning', true);

protocol.ClaimTiers = struct( ...
    'StrongConfirmatory', ...
        "all_primary_gates_pass_on_2025_holdout", ...
    'CostBoundedTradeoff', ...
        "stability_improves_but_one_primary_gate_is_noninferior_only", ...
    'NegativeOrExploratory', ...
        "holdout_fails_any_hard_gate_or_selection_rule_violation_occurs");

protocol.FailureInterpretation = struct( ...
    'NoCandidatePasses', ...
        "report_no_confirmatory_superiority_and_present_best_tradeoff", ...
    'HoldoutFailure', ...
        "do_not_reselect_parameters_after_2025", ...
    'OracleOutperformsOnly', ...
        "report_as_perfect_information_diagnostic_not_operational_claim", ...
    'SolverIncomplete', ...
        "exclude_from_superiority_claim_and retain failure audit");

protocol.ForbiddenPostHocChanges = [ ...
    "change_primary_metric_set_after_2024_or_2025_results"; ...
    "use_2025_to_select_candidate"; ...
    "promote_oracle_result_to_main_scheme"; ...
    "relax_lcoa_or_contract_noninferiority_threshold_after_results"; ...
    "delete_failed_candidates_from_reported_grid"; ...
    "reinterpret_switch_count_as_s2_stability_evidence"];

expected_seal = "D18BB5A0";
computed_seal = checksum_value(protocol);
if computed_seal ~= expected_seal
    error('protocol_v5:v5_2_seal_drift', ...
        'Frozen Protocol v5.2 drifted: expected %s, computed %s.', ...
        expected_seal, computed_seal);
end
protocol.Seal = expected_seal;
end

function schemes = create_v5_2_scheme_registry(parent_schemes)
schemes = repmat(struct( ...
    'Name', "", ...
    'DiagnosticOracleOnly', false, ...
    'EligibleForConfirmatorySelection', true), numel(parent_schemes), 1);
for scheme_index = 1:numel(parent_schemes)
    schemes(scheme_index).Name = parent_schemes(scheme_index).Name;
    schemes(scheme_index).DiagnosticOracleOnly = ...
        parent_schemes(scheme_index).DiagnosticOracleOnly;
    schemes(scheme_index).EligibleForConfirmatorySelection = ...
        ~parent_schemes(scheme_index).DiagnosticOracleOnly;
end
end

function outcomes = create_v5_2_primary_outcomes()
outcomes = [
    v52_outcome("contract_shortfall_p95", "smaller_is_better", ...
        "kg_NH3", "contract_tail_risk")
    v52_outcome("mar", "smaller_is_better", ...
        "fraction_per_hour", "HB_dynamic_ramping")
    v52_outcome("h2_soc_p05", "larger_is_better", ...
        "fraction", "lower_tail_hydrogen_security")
    v52_outcome("lcoa", "smaller_is_better", ...
        "USD_per_t_NH3", "economic_cost")];
end

function item = v52_outcome(name, direction, unit, interpretation)
item = struct( ...
    'Name', name, ...
    'Role', "primary", ...
    'Direction', direction, ...
    'Unit', unit, ...
    'Interpretation', interpretation);
end

function is_valid = verify_protocol_v5_2(protocol)
is_valid = isstruct(protocol) && isfield(protocol, 'Seal') && ...
    isfield(protocol, 'ProtocolVersion') && ...
    string(protocol.ProtocolVersion) == "5.2.0" && ...
    string(protocol.ParentProtocolSeal) == "000CDCA8" && ...
    string(protocol.Seal) == checksum_value(protocol);
end

function checksum = checksum_value(value)
if isstruct(value) && isfield(value, 'Seal')
    value = rmfield(value, 'Seal');
end

bytes = uint8(jsonencode(value));
hash_value = 2166136261;
for byte_index = 1:numel(bytes)
    hash_value = bitxor(uint32(hash_value), uint32(bytes(byte_index)));
    hash_value = mod(double(hash_value) * 16777619, 2^32);
end
checksum = string(sprintf('%08X', hash_value));
end
