function manifest = s2_baseline_manifest(action, value)
%S2_BASELINE_MANIFEST Machine-readable Zhou S2 physical-economic baseline.

if nargin > 0 && ~isempty(action)
    if nargin < 2
        value = [];
    end
    manifest = s2_baseline_manifest_dispatch(action, value);
    return
end

params = my_system('s2');
params.AEL.common.startup = true;
storage = h2_storage_limits(params.h2_storage, params.unit.h2_density);
fixed = annual_fixed_cost(params);

manifest = struct();
manifest.ManifestVersion = "S2-2026-08-21";
manifest.ModelVariant = "Zhou_S2_capacity_with_S3_startup_electricity";
manifest.Time = struct( ...
    'StepHours', params.time.step, ...
    'AnnualHours', params.time.hour_year);
manifest.Renewable = struct( ...
    'PVCapacityKW', params.renewable.PV_capacity, ...
    'PWCapacityKW', params.renewable.PW_capacity, ...
    'TotalCapacityKW', params.renewable.total_capacity, ...
    'InputScale', params.renewable.input_scale, ...
    'DevelopmentYear', 2022, ...
    'DataProduct', "Renewables_ninja_MERRA2_hindcast");
manifest.AEL = struct( ...
    'CapacityKW', params.AEL.common.max_power, ...
    'ModuleCount', params.AEL.common.module_num, ...
    'ModulePowerKW', params.AEL.common.module_power, ...
    'MinimumLoad', params.AEL.common.min_load, ...
    'SpecificEnergyKWhPerNm3', params.AEL.common.spec_energy, ...
    'MinimumStableMinutes', params.AEL.common.min_stable, ...
    'StartupElectricityEnabled', params.AEL.common.startup, ...
    'StartupLoadFractionHour', params.AEL.common.startup_elec);
manifest.HB = struct( ...
    'CapacityTPerYear', params.HB.capacity, ...
    'MinimumLoad', params.HB.min_load, ...
    'MaximumLoad', params.HB.max_load, ...
    'RampRatePerHour', params.HB.ramp_rate, ...
    'ElectricityMWhPerT', params.HB.spec_energy, ...
    'DispatchHydrogenTPerT', params.HB.lit_h2);
manifest.H2Storage = struct( ...
    'RatedCapacityNm3', params.h2_storage.capacity, ...
    'ModuleCapacityNm3', params.h2_storage.module_cap, ...
    'MinimumPressureMPa', params.h2_storage.min_pressure, ...
    'MaximumPressureMPa', params.h2_storage.max_pressure, ...
    'PressureBasis', string(params.h2_storage.pressure_basis), ...
    'TemperatureDegC', params.h2_storage.temperature, ...
    'MinimumMassKG', storage.min_mass, ...
    'MaximumMassKG', storage.max_mass, ...
    'WorkingMassKG', storage.work_mass, ...
    'InitialMassKG', storage.initial_mass);
manifest.Grid = struct( ...
    'TransformerNameplateMW', params.transformer.capacity, ...
    'TransformerMaximumLoad', params.transformer.max_load, ...
    'ContractKW', params.grid.contract_kw, ...
    'BuyPriceUsdPerKWh', params.grid.buy_price, ...
    'SellPriceUsdPerKWh', params.grid.sell_price, ...
    'CapacityFeeUsdPerKWMonth', params.grid.cap_fee, ...
    'CurtailmentPenaltyUsdPerKWh', params.grid.curtail_penalty, ...
    'MaximumSellFraction', params.grid.max_sell, ...
    'MaximumCurtailmentFraction', params.grid.curtail_limit);
manifest.Economics = struct( ...
    'AmmoniaPriceUsdPerT', params.ammonia.price, ...
    'WaterPriceUsdPerT', params.material.water_price, ...
    'CatalystPriceUsdPerT', params.material.cat_price, ...
    'LaborFTE', params.labor.fte, ...
    'LaborUsdPerFTEYear', params.labor.salary, ...
    'LifetimeYears', params.finance.lifetime, ...
    'DiscountRate', params.finance.discount, ...
    'CapitalRecoveryFactor', params.finance.crf, ...
    'LoanRatio', params.finance.loan_ratio, ...
    'LoanInterestRate', params.finance.loan_interest, ...
    'LoanTermYears', params.finance.loan_term, ...
    'WindCapexUsdPerKW', params.pw.capex, ...
    'WindOMRate', params.pw.om_rate, ...
    'PVCapexUsdPerKW', params.pv.capex, ...
    'PVOMRate', params.pv.om_rate, ...
    'AELCapexUsdPerKW', params.AEL.common.capex, ...
    'AELOMRate', params.AEL.common.om_rate, ...
    'HBcapexUsdPerTYear', params.HB.capex, ...
    'HBOMRate', params.HB.om_rate, ...
    'H2StorageCapexUsdPerNm3', params.h2_storage.capex, ...
    'H2StorageOMRate', params.h2_storage.om_rate, ...
    'ConverterCapexUsdPerKW', params.converter.capex, ...
    'ConverterOMRate', params.converter.om_rate, ...
    'TransformerCapexUsdPerKW', params.transformer.capex, ...
    'TransformerOMRate', params.transformer.om_rate);
manifest.VariableInputs = struct( ...
    'AELWaterTPerTH2', params.AEL.common.water_use, ...
    'HBWaterTPerTNH3', params.HB.water_use, ...
    'CatalystUsdPerTNH3', params.material.cat_price, ...
    'GridPurchaseUsdPerKWh', params.grid.buy_price, ...
    'GridSaleUsdPerKWh', params.grid.sell_price, ...
    'CurtailmentUsdPerKWh', params.grid.curtail_penalty);
manifest.AnnualFixedCost = struct( ...
    'CapitalUsdPerYear', fixed.CEC.total, ...
    'OMUsdPerYear', fixed.OM.total, ...
    'LaborUsdPerYear', fixed.LC.total, ...
    'GridCapacityUsdPerYear', fixed.grid_capacity, ...
    'BaseUsdPerYear', fixed.base_total, ...
    'TotalUsdPerYear', fixed.total);
manifest.Environment = struct( ...
    'GridCO2KgPerKWh', params.environment.grid_co2, ...
    'AmmoniaCO2LimitKgPerKG', params.environment.co2_limit);
manifest.Solver = struct( ...
    'Name', "intlinprog", ...
    'ConstraintTolerance', 1e-5, ...
    'RelativeGapTolerance', 1e-4, ...
    'Objective', "minimize_annual_cost_minus_revenue");
manifest.SourceClassification = struct( ...
    'ZhouScenarioParameters', "paper_reported_or_directly_derived", ...
    'RenewableCapacityMix', ...
        "current_200PV_200PW_design_not_Zhou_100PV_300PW_reference", ...
    'RenewableInputScale', "unresolved_calibration_factor", ...
    'GridContract', "s2_cost_closing_calibration_assumption", ...
    'Labor', "s2_cost_closing_calibration_assumption", ...
    'PressureBasis', "modeling_assumption_requires_sensitivity", ...
    'StartupElectricity', "s3_parameter_applied_as_s2_study_override", ...
    'WaterAndCatalystCosts', "supplemental_cost_assumptions", ...
    'GridCapacityFee', "supplemental_cost_assumption", ...
    'WeatherData', "hindcast_proxy_not_measured_operation_or_forecast");
expected_seal = "9FE68D80";
computed_seal = protocol_v5('checksum', manifest);
if computed_seal ~= expected_seal
    error('s2_baseline_manifest:seal_drift', ...
        'Frozen S2 baseline drifted: expected %s, computed %s.', ...
        expected_seal, computed_seal);
end
manifest.Seal = expected_seal;
end

function output = s2_baseline_manifest_dispatch(action, value)
if isstring(action) && isscalar(action)
    action = char(action);
end
if ~ischar(action)
    error('s2_baseline_manifest:bad_action', ...
        'action must be verify.');
end

switch lower(strtrim(action))
    case 'verify'
        output = verify_manifest(value);
    otherwise
        error('s2_baseline_manifest:bad_action', ...
            'action must be verify.');
end
end

function is_valid = verify_manifest(manifest)
is_valid = isstruct(manifest) && isfield(manifest, 'Seal') && ...
    isfield(manifest, 'ManifestVersion') && ...
    string(manifest.ManifestVersion) == "S2-2026-08-21" && ...
    string(manifest.Seal) == protocol_v5('checksum', manifest);
end
