function probe = probe_persistence_candidate(config)
%PROBE_PERSISTENCE_CANDIDATE Run one persistence candidate and report its cost.
%
%   probe = probe_persistence_candidate()
%   probe = probe_persistence_candidate(config)
%
% Runs rolling_dispatch with forecast_mode = "simulated_persistence" for one
% representative Stage-5-style candidate, measures wall-clock time, and reports
% the key metrics. This calibrates the persistence slowdown factor for
% benchmark_solver_time (whose baseline is observed_oracle).
%
% It never changes the dispatch model. Output is written to a probe folder so
% existing results are not overwritten.

if nargin < 1 || isempty(config)
    config = struct();
end

project_dir = setup_project_paths(mfilename('fullpath'));

source_mat_path = option_value(config, 'source_mat_path', ...
    fullfile(project_dir, 'runs', 'stage1', ...
    'zhou_s2_baseline_2022_latest.mat'));
output_dir = option_value(config, 'output_dir', ...
    fullfile(project_dir, 'runs', 'persistence_probe', 'rolling'));
verbose = option_value(config, 'verbose', true);

rolling_config = struct( ...
    'source_mat_path', source_mat_path, ...
    'scheme', "contract_plan_and_hb_smoothing", ...
    'forecast_mode', "simulated_persistence", ...
    'h2_reserve_quantile', option_value(config, 'h2_reserve_quantile', 0.75), ...
    'h2_reserve_lookahead_days', option_value(config, ...
        'h2_reserve_lookahead_days', 3), ...
    'h2_reserve_soft', option_value(config, 'h2_reserve_soft', true), ...
    'h2_reserve_gate_mode', option_value(config, ...
        'h2_reserve_gate_mode', "contract_carbon_state_gate"), ...
    'contract_pacing_aggressiveness', option_value(config, ...
        'contract_pacing_aggressiveness', 0.25), ...
    'hb_smoothing_reduction_fraction', option_value(config, ...
        'hb_smoothing_reduction_fraction', 0.10), ...
    'allow_infeasible_continuation', option_value(config, ...
        'allow_infeasible_continuation', true), ...
    'restoration_slack_penalty_usd_per_kg', option_value(config, ...
        'restoration_slack_penalty_usd_per_kg', 1e6), ...
    'output_dir', output_dir, ...
    'save_output', true, ...
    'verbose', verbose, ...
    'solver_display', 'none', ...
    'max_time_seconds_per_solve', option_value(config, ...
        'max_time_seconds_per_solve', 180), ...
    'relative_gap_tolerance', option_value(config, ...
        'relative_gap_tolerance', 1e-3));

probe = struct();
probe.config = rolling_config;
probe.started_at = string(datetime('now'));

timer = tic;
try
    [result, run_info, metrics] = rolling_dispatch(rolling_config);
    probe.elapsed_seconds = toc(timer);
    probe.status = string(run_info.status);
    probe.day_count = double(run_info.day_count);
    probe.succeeded = probe.status == "completed";
    probe.seconds_per_day = probe.elapsed_seconds / max(probe.day_count, 1);
    probe.solver_records = run_info.solver_records;
    if probe.succeeded
        probe.nh3_t_y = result.summary.NH3_prod_t_y;
        probe.lcoa_usd_t = result.summary.lcoa;
        probe.contract_shortfall_p95_kg = ...
            metrics.Primary.contract_shortfall_p95;
        probe.mar = metrics.Primary.mar;
        probe.h2_soc_p05 = metrics.Primary.h2_soc_p05;
        probe.restoration_days = ...
            nnz(run_info.production_pacing_history.day_ahead_restored);
        probe.h2_reserve_projected_days = ...
            nnz(run_info.production_pacing_history.h2_reserve_projected);
    end
catch exception
    probe.elapsed_seconds = toc(timer);
    probe.status = "error";
    probe.error_id = string(exception.identifier);
    probe.error_message = string(exception.message);
end

probe.finished_at = string(datetime('now'));

if verbose
    print_probe(probe);
end
end

function print_probe(probe)
fprintf('\n========== Persistence candidate probe ==========\n');
fprintf('Status: %s\n', probe.status);
fprintf('Elapsed: %.1f s (%.1f min)\n', probe.elapsed_seconds, ...
    probe.elapsed_seconds / 60);
if isfield(probe, 'day_count') && ~isnan(probe.day_count)
    fprintf('Days: %d | seconds/day: %.3f\n', probe.day_count, ...
        probe.seconds_per_day);
end
if probe.status == "completed"
    fprintf('NH3: %.3f t/a | LCOA: %.3f USD/t\n', ...
        probe.nh3_t_y, probe.lcoa_usd_t);
    fprintf('contract_shortfall_p95: %.3f kg | MAR: %.6f | h2_soc_p05: %.6f\n', ...
        probe.contract_shortfall_p95_kg, probe.mar, probe.h2_soc_p05);
    fprintf('restoration days: %d | h2 reserve projected days: %d\n', ...
        probe.restoration_days, probe.h2_reserve_projected_days);
end
if probe.status == "error"
    fprintf('Error: %s | %s\n', probe.error_id, probe.error_message);
end
fprintf('=================================================\n');
end
