function model = dispatch_model(params, renewable_data, options)
% DISPATCH_MODEL Build the shared AEL/HB/H2 dispatch optimization problem.
% The function defines variables, physics, contract constraints, and the
% economic objective. It does not solve the problem or read/write files.

if nargin < 3 || isempty(options)
    options = struct();
end

mode = string(option_value(options, 'mode', "annual"));
if ~isscalar(mode) || ~ismember(mode, ["annual", "day_ahead", "realtime"])
    error('dispatch_model:bad_mode', ...
        'mode must be annual, day_ahead, or realtime.');
end

T = renewable_data.time_count;
dt = params.time.step;
if ~(isnumeric(T) && isscalar(T) && T >= 1 && T == floor(T))
    error('dispatch_model:bad_horizon', ...
        'renewable_data.time_count must be a positive integer.');
end
if numel(renewable_data.pv_power_kw) ~= T || ...
        numel(renewable_data.pw_power_kw) ~= T
    error('dispatch_model:bad_renewable_shape', ...
        'PV and wind power vectors must match time_count.');
end

transformer_kw = params.transformer.max_load * ...
    params.transformer.capacity * 1000;
PV = renewable_data.pv_power_kw(:) * params.renewable.input_scale;
PW = renewable_data.pw_power_kw(:) * params.renewable.input_scale;
P_total = PV + PW;
renewable_energy = sum(P_total) * dt;

ael_common = params.AEL.common;
Num_AEL = ael_common.module_num;
P_AEL_max = ael_common.max_power;
AEL_spec_energy = ael_common.spec_energy;
AEL_module_power = ael_common.module_power;
AEL_start_power_per_module = 0;
if ael_common.startup
    AEL_start_power_per_module = ...
        ael_common.startup_elec * AEL_module_power;
end
H2_density = params.unit.h2_density;

storage_limits = h2_storage_limits(params.h2_storage, H2_density);
initial_options = option_value(options, 'initial_state', struct());
initial_state = struct( ...
    'h2_kg', option_value(initial_options, ...
    'h2_kg', storage_limits.initial_mass), ...
    'ael_online_modules', option_value(initial_options, ...
        'ael_online_modules', 0), ...
    'hb_load', option_value(initial_options, 'hb_load', []));
validate_initial_state(initial_state, storage_limits, Num_AEL, params.HB);
hydrogen = hydrogen_settings(options, T, storage_limits);
restoration = restoration_settings(options);

HB_max_load = params.HB.max_load;
HB_min_load = params.HB.min_load;
HB_ramp = params.HB.ramp_rate;
HB_power_kw = params.HB.nom_power * 1000;
NH3_rate = params.HB.nh3_output;

N_AEL = optimvar('n_ael', T, 'Type', 'integer', ...
    'LowerBound', 0, 'UpperBound', Num_AEL);
P_AEL = optimvar('P_AEL', T, 'LowerBound', 0, ...
    'UpperBound', P_AEL_max);
HB_load = optimvar('HB_load', T, 'LowerBound', HB_min_load, ...
    'UpperBound', HB_max_load);
storage_H2 = optimvar('storage_H2', T + 1, ...
    'LowerBound', storage_limits.min_mass, ...
    'UpperBound', storage_limits.max_mass);
P_purchase = optimvar('p_purchase', T, 'LowerBound', 0, ...
    'UpperBound', transformer_kw);
P_sell = optimvar('p_sell', T, 'LowerBound', 0, ...
    'UpperBound', transformer_kw);
P_curt = optimvar('p_curt', T, 'LowerBound', 0);
u_purchase = optimvar('u_purchase', T, 'Type', 'integer', ...
    'LowerBound', 0, 'UpperBound', 1);
SU_AEL = optimvar('SU_AEL', T, 'Type', 'integer', ...
    'LowerBound', 0, 'UpperBound', Num_AEL);
SD_AEL = optimvar('SD_AEL', T, 'Type', 'integer', ...
    'LowerBound', 0, 'UpperBound', Num_AEL);
I_AEL_up = optimvar('I_AEL_up', T, 'Type', 'integer', ...
    'LowerBound', 0, 'UpperBound', 1);
H2_reserve_slack = [];
if hydrogen.reserve_floor_active && hydrogen.reserve_floor_soft
    H2_reserve_slack = optimvar('H2_reserve_slack', T, ...
        'LowerBound', 0);
end
production_commit_slack_kg = [];
carbon_slack_kg = [];
H2_terminal_shortfall_kg = [];
H2_terminal_surplus_kg = [];
H2_commit_slack_kg = [];
if restoration.enabled
    production_commit_slack_kg = optimvar( ...
        'production_commit_slack_kg', 1, 'LowerBound', 0);
    carbon_slack_kg = optimvar('carbon_slack_kg', 1, ...
        'LowerBound', 0);
    H2_terminal_shortfall_kg = optimvar( ...
        'H2_terminal_shortfall_kg', 1, 'LowerBound', 0);
    H2_terminal_surplus_kg = optimvar( ...
        'H2_terminal_surplus_kg', 1, 'LowerBound', 0);
    H2_commit_slack_kg = optimvar('H2_commit_slack_kg', 1, ...
        'LowerBound', 0);
end

grid_contract_is_fixed = ~isempty(params.grid.contract_kw);
if ~grid_contract_is_fixed
    P_grid_contract = optimvar('grid_contract_kw', 1, ...
        'LowerBound', 0, 'UpperBound', transformer_kw);
end

P_AEL_start = AEL_start_power_per_module * SU_AEL;
H2_prod_kg = P_AEL * dt / AEL_spec_energy * H2_density;
NH3_prod_kg = HB_load * NH3_rate * dt;
H2_use_kg = NH3_prod_kg * params.HB.lit_h2;
P_HB_kw = HB_load * HB_power_kw;
H2_prod_t = H2_prod_kg / params.unit.mass_scale;
NH3_prod_t = NH3_prod_kg / params.unit.mass_scale;
water_use_t = params.AEL.common.water_use * H2_prod_t + ...
    params.HB.water_use * NH3_prod_t;
carbon = carbon_settings(options, mode, ...
    params.environment.co2_enabled, T);
production = production_settings(options, T);
horizon_grid_emissions_kg = params.environment.grid_co2 * ...
    sum(P_purchase) * dt;
horizon_nh3_kg = sum(NH3_prod_kg);
commit_nh3_kg = 0;
if production.commit_steps > 0
    commit_nh3_kg = sum(NH3_prod_kg(1:production.commit_steps));
end
carbon_emissions_after_horizon_kg = ...
    carbon.initial_emissions_kg + horizon_grid_emissions_kg;
carbon_debt_after_horizon_kg = ...
    carbon_emissions_after_horizon_kg ...
    - params.environment.co2_limit * ...
        (carbon.initial_nh3_kg + horizon_nh3_kg);
commit_carbon_debt_kg = carbon_debt_after_horizon_kg;
commit_carbon_emissions_kg = carbon_emissions_after_horizon_kg;
if carbon.commit_steps > 0 && carbon.commit_steps < T
    k = carbon.commit_steps;
    commit_carbon_emissions_kg = carbon.initial_emissions_kg ...
        + params.environment.grid_co2 * sum(P_purchase(1:k)) * dt;
    commit_carbon_debt_kg = carbon.initial_emissions_kg ...
        + params.environment.grid_co2 * sum(P_purchase(1:k)) * dt ...
        - params.environment.co2_limit ...
        * (carbon.initial_nh3_kg + sum(NH3_prod_kg(1:k)));
end
grid_budget = grid_budget_settings(options, mode);
remaining_grid_renewable_kwh = ...
    grid_budget.remaining_max_renewable_kwh;
max_grid_renewable_per_step_kwh = ...
    grid_budget.max_renewable_per_step_kwh;
if grid_budget.accounting == "annual_cumulative_observed_budget"
    remaining_grid_renewable_kwh = 0;
    max_grid_renewable_per_step_kwh = 0;
end
horizon_sell_kwh = sum(P_sell) * dt;
horizon_curtail_kwh = sum(P_curt) * dt;
sell_debt_after_horizon_kwh = ...
    grid_budget.initial_sell_kwh + horizon_sell_kwh ...
    - params.grid.max_sell * ...
        (grid_budget.initial_renewable_kwh + renewable_energy);
curtail_debt_after_horizon_kwh = ...
    grid_budget.initial_curtail_kwh + horizon_curtail_kwh ...
    - params.grid.curtail_limit * ...
        (grid_budget.initial_renewable_kwh + renewable_energy);

contract_options = option_value(options, 'contract', struct());
contract = contract_settings( ...
    contract_options, T, dt, HB_max_load, NH3_rate);
if contract.enabled
    daily_aggregation = kron(speye(contract.day_count), ...
        ones(1, contract.samples_per_day));
    daily_NH3_prod_kg = daily_aggregation * NH3_prod_kg;
    if contract.strict_delivery
        [contract_delivery, contract] = ...
            strict_delivery_variable(contract);
    else
        contract_backlog = optimvar('contract_backlog', ...
            contract.day_count + 1, 'LowerBound', 0);
    end
end

prob = optimproblem('ObjectiveSense', 'minimize');
prob.Constraints.power_balance = ...
    P_total + P_purchase == P_AEL + P_AEL_start + ...
    P_HB_kw + P_sell + P_curt;
prob.Constraints.H2_storage = ...
    storage_H2(2:end) == storage_H2(1:end-1) + ...
    H2_prod_kg - H2_use_kg;
prob.Constraints.H2_initial = storage_H2(1) == initial_state.h2_kg;
if hydrogen.reserve_floor_active
    if hydrogen.reserve_floor_soft
        prob.Constraints.H2_reserve_floor = ...
            storage_H2(2:end) + H2_reserve_slack >= ...
            hydrogen.min_storage_kg_by_step;
    else
        prob.Constraints.H2_reserve_floor = ...
            storage_H2(2:end) >= hydrogen.min_storage_kg_by_step;
    end
end
prob.Constraints.purchase = P_purchase <= u_purchase * transformer_kw;
prob.Constraints.sell = P_sell <= (1 - u_purchase) * transformer_kw;
if ~grid_contract_is_fixed
    prob.Constraints.grid_contract = P_purchase <= P_grid_contract;
end
if grid_budget.accounting == "annual_horizon"
    prob.Constraints.sell_rate = horizon_sell_kwh <= ...
        params.grid.max_sell * renewable_energy;
else
    prob.Constraints.sell_annual_reachability = ...
        sell_debt_after_horizon_kwh <= params.grid.max_sell ...
        * remaining_grid_renewable_kwh;
    checkpoint_indices = reachability_checkpoints( ...
        T, grid_budget.checkpoint_interval_steps);
    if ~isempty(checkpoint_indices)
        sell_checkpoints = optimconstr(numel(checkpoint_indices), 1);
        for checkpoint_number = 1:numel(checkpoint_indices)
            k = checkpoint_indices(checkpoint_number);
            remaining_max_kwh = ...
                remaining_grid_renewable_kwh + (T - k) ...
                * max_grid_renewable_per_step_kwh;
            sell_debt_kwh = grid_budget.initial_sell_kwh ...
                + sum(P_sell(1:k)) * dt - params.grid.max_sell ...
                * (grid_budget.initial_renewable_kwh ...
                + sum(P_total(1:k)) * dt);
            sell_checkpoints(checkpoint_number) = sell_debt_kwh <= ...
                params.grid.max_sell * remaining_max_kwh;
        end
        prob.Constraints.sell_annual_checkpoints = sell_checkpoints;
    end
end
if T > 1
    prob.Constraints.HB_ramp_up = ...
        HB_load(2:end) - HB_load(1:end-1) <= HB_ramp;
    prob.Constraints.HB_ramp_down = ...
        HB_load(1:end-1) - HB_load(2:end) <= HB_ramp;
end
if ~isempty(initial_state.hb_load)
    prob.Constraints.HB_initial_ramp_up = ...
        HB_load(1) - initial_state.hb_load <= HB_ramp;
    prob.Constraints.HB_initial_ramp_down = ...
        initial_state.hb_load - HB_load(1) <= HB_ramp;
end
prob.Constraints.curtail = P_curt <= P_total;
if grid_budget.accounting == "annual_horizon"
    prob.Constraints.curtail_rate = horizon_curtail_kwh <= ...
        params.grid.curtail_limit * renewable_energy;
else
    prob.Constraints.curtail_annual_reachability = ...
        curtail_debt_after_horizon_kwh <= params.grid.curtail_limit ...
        * remaining_grid_renewable_kwh;
    checkpoint_indices = reachability_checkpoints( ...
        T, grid_budget.checkpoint_interval_steps);
    if ~isempty(checkpoint_indices)
        curtail_checkpoints = optimconstr(numel(checkpoint_indices), 1);
        for checkpoint_number = 1:numel(checkpoint_indices)
            k = checkpoint_indices(checkpoint_number);
            remaining_max_kwh = ...
                remaining_grid_renewable_kwh + (T - k) ...
                * max_grid_renewable_per_step_kwh;
            curtail_debt_kwh = grid_budget.initial_curtail_kwh ...
                + sum(P_curt(1:k)) * dt - params.grid.curtail_limit ...
                * (grid_budget.initial_renewable_kwh ...
                + sum(P_total(1:k)) * dt);
            curtail_checkpoints(checkpoint_number) = ...
                curtail_debt_kwh <= ...
                params.grid.curtail_limit * remaining_max_kwh;
        end
        prob.Constraints.curtail_annual_checkpoints = ...
            curtail_checkpoints;
    end
end
prob.Constraints.AEL_module_lower = ...
    ael_common.min_load * N_AEL * AEL_module_power <= P_AEL;
prob.Constraints.AEL_module_upper = ...
    P_AEL <= ael_common.max_load * N_AEL * AEL_module_power;
N_AEL_previous = [initial_state.ael_online_modules; N_AEL(1:end-1)];
prob.Constraints.AEL_transition = ...
    N_AEL - N_AEL_previous == SU_AEL - SD_AEL;
prob.Constraints.AEL_start_available = ...
    SU_AEL <= Num_AEL - N_AEL_previous;
prob.Constraints.AEL_stop_available = SD_AEL <= N_AEL_previous;
prob.Constraints.AEL_start_indicator = SU_AEL <= Num_AEL * I_AEL_up;
prob.Constraints.AEL_stop_indicator = ...
    SD_AEL <= Num_AEL * (1 - I_AEL_up);

min_run_h = 1;
L_run = ceil(min_run_h / dt);
AEL_min_run = optimconstr(T, 1);
for tau = 1:T
    k1 = max(1, tau - L_run);
    k2 = tau - 1;
    if k1 <= k2
        AEL_min_run(tau) = N_AEL(tau) >= sum(SU_AEL(k1:k2));
    else
        AEL_min_run(tau) = N_AEL(tau) >= 0;
    end
end
prob.Constraints.AEL_min_run = AEL_min_run;

if carbon.enabled
    if carbon.accounting == "annual_horizon"
        prob.Constraints.co2_limit = ...
            horizon_grid_emissions_kg <= ...
            params.environment.co2_limit * horizon_nh3_kg;
    else
        horizon_reserve_kg = 0;
        if carbon.commit_steps == T
            horizon_reserve_kg = carbon.commit_reserve_kg;
        end
        if carbon.accounting == "annual_cumulative_absolute_budget" && ...
                ~carbon.is_year_end
            available_budget_kg = min( ...
                carbon.annual_emissions_budget_kg, ...
                carbon.budget_available_at_start_kg ...
                + T * carbon.budget_accrual_per_step_kg);
            if restoration.enabled
                prob.Constraints.co2_annual_reachability = ...
                    carbon_emissions_after_horizon_kg <= ...
                    available_budget_kg - horizon_reserve_kg ...
                    + carbon_slack_kg;
            else
                prob.Constraints.co2_annual_reachability = ...
                    carbon_emissions_after_horizon_kg <= ...
                    available_budget_kg - horizon_reserve_kg;
            end
        else
            if restoration.enabled
                prob.Constraints.co2_annual_reachability = ...
                    carbon_debt_after_horizon_kg <= ...
                    params.environment.co2_limit * ...
                        carbon.remaining_reference_nh3_kg ...
                        - horizon_reserve_kg + carbon_slack_kg;
            else
                prob.Constraints.co2_annual_reachability = ...
                    carbon_debt_after_horizon_kg <= ...
                    params.environment.co2_limit * ...
                        carbon.remaining_reference_nh3_kg ...
                        - horizon_reserve_kg;
            end
        end
        checkpoint_indices = reachability_checkpoints( ...
            T, carbon.checkpoint_interval_steps);
        if ~isempty(checkpoint_indices)
            carbon_checkpoints = optimconstr( ...
                numel(checkpoint_indices), 1);
            for checkpoint_number = 1:numel(checkpoint_indices)
                k = checkpoint_indices(checkpoint_number);
                remaining_reference_kg = ...
                    carbon.remaining_reference_nh3_kg + (T - k) ...
                    * carbon.reference_nh3_per_step_kg;
                checkpoint_reserve_kg = 0;
                if k == carbon.commit_steps
                    checkpoint_reserve_kg = carbon.commit_reserve_kg;
                end
                if carbon.accounting == ...
                        "annual_cumulative_absolute_budget"
                    checkpoint_emissions_kg = ...
                        carbon.initial_emissions_kg ...
                        + params.environment.grid_co2 ...
                        * sum(P_purchase(1:k)) * dt;
                    checkpoint_budget_kg = min( ...
                        carbon.annual_emissions_budget_kg, ...
                        carbon.budget_available_at_start_kg ...
                        + k * carbon.budget_accrual_per_step_kg);
                    if restoration.enabled
                        carbon_checkpoints(checkpoint_number) = ...
                            checkpoint_emissions_kg <= ...
                            checkpoint_budget_kg ...
                            - checkpoint_reserve_kg ...
                            + carbon_slack_kg;
                    else
                        carbon_checkpoints(checkpoint_number) = ...
                            checkpoint_emissions_kg <= ...
                            checkpoint_budget_kg ...
                            - checkpoint_reserve_kg;
                    end
                else
                    checkpoint_debt_kg = carbon.initial_emissions_kg ...
                        + params.environment.grid_co2 ...
                        * sum(P_purchase(1:k)) * dt ...
                        - params.environment.co2_limit ...
                        * (carbon.initial_nh3_kg ...
                        + sum(NH3_prod_kg(1:k)));
                    if restoration.enabled
                        carbon_checkpoints(checkpoint_number) = ...
                            checkpoint_debt_kg <= ...
                            params.environment.co2_limit ...
                            * remaining_reference_kg ...
                            - checkpoint_reserve_kg + carbon_slack_kg;
                    else
                        carbon_checkpoints(checkpoint_number) = ...
                            checkpoint_debt_kg <= ...
                            params.environment.co2_limit ...
                            * remaining_reference_kg ...
                            - checkpoint_reserve_kg;
                    end
                end
            end
            prob.Constraints.co2_annual_checkpoints = ...
                carbon_checkpoints;
        end
        if carbon.accounting == ...
                "annual_cumulative_absolute_budget" && ...
                carbon.commit_steps > 0
            prob.Constraints.nh3_commit_pacing = ...
                carbon.initial_nh3_kg ...
                + sum(NH3_prod_kg(1:carbon.commit_steps)) >= ...
                carbon.production_target_at_commit_kg;
        end
    end
end
if production.commit_steps > 0
    if restoration.enabled
        prob.Constraints.production_commit_min = ...
            commit_nh3_kg + production_commit_slack_kg ...
            >= production.commit_min_nh3_kg;
    else
        prob.Constraints.production_commit_min = ...
            commit_nh3_kg >= production.commit_min_nh3_kg;
    end
end

terminal_options = option_value(options, 'terminal', struct());
terminal_equal_kg = field_value(terminal_options, ...
    'h2_equal_kg', initial_state.h2_kg);
terminal_min_kg = field_value(terminal_options, 'h2_min_kg', []);
terminal_commit_steps = option_value( ...
    terminal_options, 'commit_steps', 0);
if ~(isnumeric(terminal_commit_steps) && ...
        isscalar(terminal_commit_steps) && ...
        isfinite(terminal_commit_steps) && ...
        terminal_commit_steps >= 0 && ...
        terminal_commit_steps == floor(terminal_commit_steps))
    error('dispatch_model:bad_terminal', ...
        'terminal.commit_steps must be a nonnegative integer.');
end
if terminal_commit_steps > T
    error('dispatch_model:bad_terminal', ...
        'terminal.commit_steps cannot exceed the dispatch horizon.');
end
terminal_h2_commit_min_kg = field_value( ...
    terminal_options, 'h2_commit_min_kg', []);
if ~isempty(terminal_h2_commit_min_kg)
    if terminal_commit_steps == 0
        error('dispatch_model:bad_terminal', ...
            'terminal.h2_commit_min_kg requires positive commit_steps.');
    end
    validate_h2_bound(terminal_h2_commit_min_kg, storage_limits, ...
        'terminal.h2_commit_min_kg');
end
terminal = struct( ...
    'h2_equal_kg', terminal_equal_kg, ...
    'h2_min_kg', terminal_min_kg, ...
    'commit_steps', terminal_commit_steps, ...
    'h2_commit_min_kg', terminal_h2_commit_min_kg);
if ~isempty(terminal_equal_kg)
    if restoration.enabled
        prob.Constraints.H2_terminal = ...
            storage_H2(end) + H2_terminal_shortfall_kg ...
            - H2_terminal_surplus_kg == terminal_equal_kg;
    else
        prob.Constraints.H2_terminal = storage_H2(end) == ...
            terminal_equal_kg;
    end
elseif ~isempty(terminal_min_kg)
    if restoration.enabled
        prob.Constraints.H2_terminal_min = ...
            storage_H2(end) + H2_terminal_shortfall_kg ...
            >= terminal_min_kg;
    else
        prob.Constraints.H2_terminal_min = ...
            storage_H2(end) >= terminal_min_kg;
    end
end
if ~isempty(terminal_h2_commit_min_kg)
    if restoration.enabled
        prob.Constraints.H2_commit_min = ...
            storage_H2(terminal_commit_steps + 1) ...
            + H2_commit_slack_kg >= terminal_h2_commit_min_kg;
    else
        prob.Constraints.H2_commit_min = ...
            storage_H2(terminal_commit_steps + 1) >= ...
            terminal_h2_commit_min_kg;
    end
end

fixed_plan = option_value(options, 'fixed_plan', struct());
hb_shortfall_load_hours = 0;
if isfield(fixed_plan, 'HB_load') && ~isempty(fixed_plan.HB_load)
    validate_fixed_vector(fixed_plan.HB_load, T, 'HB_load');
    prob.Constraints.fixed_HB_load = HB_load == fixed_plan.HB_load(:);
elseif isfield(fixed_plan, 'HB_load_upper') && ...
        ~isempty(fixed_plan.HB_load_upper)
    validate_fixed_vector(fixed_plan.HB_load_upper, T, 'HB_load_upper');
    hb_target = fixed_plan.HB_load_upper(:);
    prob.Constraints.HB_recourse_upper = HB_load <= hb_target;
    hb_shortfall_load_hours = sum(hb_target - HB_load) * dt;
    if isfield(fixed_plan, 'max_hb_shortfall_load_hours') && ...
            ~isempty(fixed_plan.max_hb_shortfall_load_hours)
        max_shortfall = fixed_plan.max_hb_shortfall_load_hours;
        if ~(isnumeric(max_shortfall) && isscalar(max_shortfall) && ...
                isfinite(max_shortfall) && max_shortfall >= 0)
            error('dispatch_model:bad_fixed_plan', ...
                ['fixed_plan.max_hb_shortfall_load_hours must be ', ...
                 'a finite nonnegative scalar.']);
        end
        prob.Constraints.HB_recourse_shortfall = ...
            hb_shortfall_load_hours <= max_shortfall;
    end
end
if isfield(fixed_plan, 'AEL_commitment') && ...
        ~isempty(fixed_plan.AEL_commitment)
    validate_fixed_vector(fixed_plan.AEL_commitment, T, ...
        'AEL_commitment');
    prob.Constraints.fixed_AEL_commitment = ...
        N_AEL == fixed_plan.AEL_commitment(:);
elseif isfield(fixed_plan, 'AEL_commitment_upper') && ...
        ~isempty(fixed_plan.AEL_commitment_upper)
    validate_fixed_vector(fixed_plan.AEL_commitment_upper, T, ...
        'AEL_commitment_upper');
    prob.Constraints.AEL_recourse_upper = ...
        N_AEL <= fixed_plan.AEL_commitment_upper(:);
end

NH3_total_kg = sum(NH3_prod_kg);
NH3_income = params.ammonia.price * NH3_total_kg / 1000;
C_curt = params.grid.curtail_penalty;
C_purchase = params.grid.buy_price;
C_sell = params.grid.sell_price;
C_water = params.material.water_price;
C_catalyst = params.material.cat_price;
h2_reserve_slack_kg = 0;
if hydrogen.reserve_floor_active && hydrogen.reserve_floor_soft
    h2_reserve_slack_kg = sum(H2_reserve_slack);
end
restoration_slack_kg = 0;
if restoration.enabled
    restoration_slack_kg = production_commit_slack_kg ...
        + carbon_slack_kg + H2_terminal_shortfall_kg ...
        + H2_terminal_surplus_kg + H2_commit_slack_kg;
end
variable_objective = sum(C_curt .* P_curt * dt) + ...
    sum(C_purchase .* P_purchase * dt) - ...
    sum(C_sell .* P_sell * dt) - NH3_income + ...
    C_water * sum(water_use_t) + C_catalyst * sum(NH3_prod_t) + ...
    hydrogen.reserve_slack_penalty_usd_per_kg * h2_reserve_slack_kg + ...
    restoration.slack_penalty_usd_per_kg * restoration_slack_kg;

include_fixed_cost = option_value(options, ...
    'include_annual_fixed_cost', mode == "annual");
fixed_cost_expression = 0;
if include_fixed_cost
    if grid_contract_is_fixed
        fixed_cost = annual_fixed_cost(params);
        grid_capacity_cost = fixed_cost.grid_capacity;
    else
        fixed_cost = annual_fixed_cost(params, 0);
        grid_capacity_cost = params.grid.cap_fee * 12 * P_grid_contract;
    end
    fixed_cost_expression = fixed_cost.base_total + grid_capacity_cost;
end

if contract.enabled
    if contract.strict_delivery
        prob = add_strict_delivery_constraints(prob, ...
            contract_delivery, daily_NH3_prod_kg, contract);
    else
        prob.Constraints.contract_initial = contract_backlog(1) == 0;
        prob.Constraints.contract_update = contract_backlog(2:end) >= ...
            contract_backlog(1:end-1) + contract.daily_quantity_kg ...
            - daily_NH3_prod_kg;
        prob.Constraints.contract_delay = contract_backlog(2:end) <= ...
            contract.max_delay_days * contract.daily_quantity_kg;
        prob.Constraints.contract_terminal = contract_backlog(end) == 0;
    end
end

economic_objective = variable_objective + fixed_cost_expression;
objective_mode = string(option_value(options, ...
    'objective_mode', "economic"));
objective_expression = [];
if objective_mode == "economic"
    objective_expression = economic_objective;
elseif objective_mode == "minimize_hb_shortfall"
    if ~isfield(fixed_plan, 'HB_load_upper') || ...
            isempty(fixed_plan.HB_load_upper)
        error('dispatch_model:missing_hb_target', ...
            ['minimize_hb_shortfall requires ', ...
             'fixed_plan.HB_load_upper.']);
    end
    objective_expression = hb_shortfall_load_hours;
elseif objective_mode == "minimize_carbon_debt"
    if ~carbon.enabled
        error('dispatch_model:carbon_objective_disabled', ...
            'minimize_carbon_debt requires enabled carbon accounting.');
    end
    if carbon.accounting == "annual_cumulative_absolute_budget"
        objective_expression = carbon_emissions_after_horizon_kg;
    else
        objective_expression = carbon_debt_after_horizon_kg;
    end
elseif objective_mode == "minimize_commit_carbon_debt"
    if ~carbon.enabled || carbon.commit_steps == 0
        error('dispatch_model:commit_carbon_objective_unavailable', ...
            ['minimize_commit_carbon_debt requires enabled carbon ', ...
             'accounting and positive carbon.commit_steps.']);
    end
    if carbon.accounting == "annual_cumulative_absolute_budget"
        objective_expression = commit_carbon_emissions_kg;
    else
        objective_expression = commit_carbon_debt_kg;
    end
elseif objective_mode == "maximize_commit_nh3"
    if carbon.commit_steps == 0
        error('dispatch_model:commit_nh3_objective_unavailable', ...
            'maximize_commit_nh3 requires positive carbon.commit_steps.');
    end
    objective_expression = -sum(NH3_prod_kg(1:carbon.commit_steps));
else
    error('dispatch_model:bad_objective_mode', ...
        ['objective_mode must be economic, minimize_hb_shortfall, ', ...
         'minimize_carbon_debt, minimize_commit_carbon_debt, or ', ...
         'maximize_commit_nh3.']);
end
if restoration.enabled && objective_mode ~= "economic"
    objective_expression = objective_expression + ...
        restoration.slack_penalty_usd_per_kg * restoration_slack_kg;
end
prob.Objective = objective_expression;
lcoa_numerator = economic_objective + NH3_income;
if contract.enabled && ~isempty(contract.lcoa_cap_usd_per_t)
    prob.Constraints.contract_lcoa_cap = lcoa_numerator <= ...
        contract.lcoa_cap_usd_per_t * sum(NH3_prod_t);
end

variables = struct( ...
    'n_ael', N_AEL, ...
    'P_AEL', P_AEL, ...
    'HB_load', HB_load, ...
    'storage_H2', storage_H2, ...
    'p_purchase', P_purchase, ...
    'p_sell', P_sell, ...
    'p_curt', P_curt, ...
    'u_purchase', u_purchase, ...
    'SU_AEL', SU_AEL, ...
    'SD_AEL', SD_AEL, ...
    'I_AEL_up', I_AEL_up);
if ~grid_contract_is_fixed
    variables.grid_contract_kw = P_grid_contract;
end
if contract.enabled
    if contract.strict_delivery
        variables.contract_delivery = contract_delivery;
    else
        variables.contract_backlog = contract_backlog;
    end
end
if hydrogen.reserve_floor_active && hydrogen.reserve_floor_soft
    variables.H2_reserve_slack = H2_reserve_slack;
end
if restoration.enabled
    variables.production_commit_slack_kg = production_commit_slack_kg;
    variables.carbon_slack_kg = carbon_slack_kg;
    variables.H2_terminal_shortfall_kg = H2_terminal_shortfall_kg;
    variables.H2_terminal_surplus_kg = H2_terminal_surplus_kg;
    variables.H2_commit_slack_kg = H2_commit_slack_kg;
end

expressions = struct( ...
    'P_AEL_start', P_AEL_start, ...
    'H2_prod_kg', H2_prod_kg, ...
    'NH3_prod_kg', NH3_prod_kg, ...
    'H2_use_kg', H2_use_kg, ...
    'P_HB_kw', P_HB_kw, ...
    'NH3_income', NH3_income, ...
    'horizon_grid_emissions_kg', horizon_grid_emissions_kg, ...
    'horizon_nh3_kg', horizon_nh3_kg, ...
    'carbon_emissions_after_horizon_kg', ...
        carbon_emissions_after_horizon_kg, ...
    'carbon_debt_after_horizon_kg', ...
        carbon_debt_after_horizon_kg, ...
    'commit_carbon_debt_kg', commit_carbon_debt_kg, ...
    'commit_carbon_emissions_kg', commit_carbon_emissions_kg, ...
    'commit_nh3_kg', commit_nh3_kg, ...
    'h2_reserve_slack_kg', h2_reserve_slack_kg, ...
    'restoration_slack_kg', restoration_slack_kg, ...
    'horizon_sell_kwh', horizon_sell_kwh, ...
    'horizon_curtail_kwh', horizon_curtail_kwh, ...
    'sell_debt_after_horizon_kwh', sell_debt_after_horizon_kwh, ...
    'curtail_debt_after_horizon_kwh', ...
        curtail_debt_after_horizon_kwh, ...
    'hb_shortfall_load_hours', hb_shortfall_load_hours, ...
    'economic_objective', economic_objective);

context = struct( ...
    'T', T, ...
    'dt', dt, ...
    'P_total', P_total, ...
    'AEL_spec_energy', AEL_spec_energy, ...
    'H2_density', H2_density, ...
    'NH3_rate', NH3_rate, ...
    'HB_power_kw', HB_power_kw, ...
    'C_curt', C_curt, ...
    'C_purchase', C_purchase, ...
    'C_sell', C_sell, ...
    'ael_common', ael_common, ...
    'N_AEL_initial', initial_state.ael_online_modules, ...
    'AEL_start_power_per_module', AEL_start_power_per_module);

model = struct( ...
    'problem', prob, ...
    'variables', variables, ...
    'expressions', expressions, ...
    'context', context, ...
    'contract', contract, ...
    'carbon', carbon, ...
    'production', production, ...
    'terminal', terminal, ...
    'hydrogen', hydrogen, ...
    'grid_budget', grid_budget, ...
    'restoration', restoration, ...
    'initial_state', initial_state, ...
    'mode', mode);
end



%% Function

function restoration = restoration_settings(options)
restoration = struct( ...
    'enabled', false, ...
    'slack_penalty_usd_per_kg', 1e6);
if ~isfield(options, 'restoration') || ...
        ~isstruct(options.restoration) || ...
        isempty(fieldnames(options.restoration))
    return
end
restoration.enabled = option_value(options.restoration, ...
    'enabled', false);
if ~(islogical(restoration.enabled) && isscalar(restoration.enabled))
    error('dispatch_model:bad_restoration', ...
        'restoration.enabled must be a scalar logical.');
end
penalty = option_value(options.restoration, ...
    'slack_penalty_usd_per_kg', restoration.slack_penalty_usd_per_kg);
if ~(isnumeric(penalty) && isscalar(penalty) && ...
        isfinite(penalty) && penalty >= 0)
    error('dispatch_model:bad_restoration', ...
        ['restoration.slack_penalty_usd_per_kg must be a finite ', ...
         'nonnegative scalar.']);
end
restoration.slack_penalty_usd_per_kg = penalty;
end

function hydrogen = hydrogen_settings(options, time_count, storage_limits)
hydrogen = struct( ...
    'reserve_floor_active', false, ...
    'reserve_floor_soft', false, ...
    'reserve_slack_penalty_usd_per_kg', 0, ...
    'min_storage_kg_by_step', zeros(time_count, 1));
if ~isfield(options, 'hydrogen') || ...
        ~isstruct(options.hydrogen) || ...
        isempty(fieldnames(options.hydrogen))
    return
end
floor_kg = option_value( ...
    options.hydrogen, 'min_storage_kg_by_step', []);
if isempty(floor_kg)
    return
end
if ~(isnumeric(floor_kg) && numel(floor_kg) == time_count && ...
        all(isfinite(floor_kg(:))) && ...
        all(floor_kg(:) >= storage_limits.min_mass - 1e-6) && ...
        all(floor_kg(:) <= storage_limits.max_mass + 1e-6))
    error('dispatch_model:bad_hydrogen_reserve', ...
        ['hydrogen.min_storage_kg_by_step must contain one finite ', ...
         'storage-bound value per dispatch step.']);
end
hydrogen.reserve_floor_active = true;
hydrogen.min_storage_kg_by_step = floor_kg(:);
hydrogen.reserve_floor_soft = option_value( ...
    options.hydrogen, 'reserve_floor_soft', false);
if ~(islogical(hydrogen.reserve_floor_soft) && ...
        isscalar(hydrogen.reserve_floor_soft))
    error('dispatch_model:bad_hydrogen_reserve', ...
        'hydrogen.reserve_floor_soft must be a scalar logical.');
end
penalty = option_value(options.hydrogen, ...
    'reserve_slack_penalty_usd_per_kg', 0);
if ~(isnumeric(penalty) && isscalar(penalty) && ...
        isfinite(penalty) && penalty >= 0)
    error('dispatch_model:bad_hydrogen_reserve', ...
        ['hydrogen.reserve_slack_penalty_usd_per_kg must be ', ...
         'a finite nonnegative scalar.']);
end
hydrogen.reserve_slack_penalty_usd_per_kg = penalty;
end

function validate_h2_bound(value, storage_limits, name)
if ~(isnumeric(value) && isscalar(value) && isfinite(value) && ...
        value >= storage_limits.min_mass - 1e-6 && ...
        value <= storage_limits.max_mass + 1e-6)
    error('dispatch_model:bad_terminal', ...
        '%s must be within physical hydrogen storage bounds.', name);
end
end

function production = production_settings(options, time_count)
production = struct( ...
    'commit_steps', 0, ...
    'commit_min_nh3_kg', 0);
if ~isfield(options, 'production') || ...
        ~isstruct(options.production) || ...
        isempty(fieldnames(options.production))
    return
end
production.commit_steps = optional_nonnegative_integer( ...
    options.production, 'commit_steps', ...
    'dispatch_model:bad_production', 'production');
production.commit_min_nh3_kg = optional_nonnegative_scalar( ...
    options.production, 'commit_min_nh3_kg', 0, ...
    'dispatch_model:bad_production', 'production');
if production.commit_steps > time_count
    error('dispatch_model:bad_production', ...
        'production.commit_steps cannot exceed the dispatch horizon.');
end
if production.commit_steps == 0 && production.commit_min_nh3_kg > 0
    error('dispatch_model:bad_production', ...
        ['production.commit_min_nh3_kg requires positive ', ...
         'production.commit_steps.']);
end
end

function budget = grid_budget_settings(options, mode)
budget = struct( ...
    'accounting', "annual_horizon", ...
    'initial_sell_kwh', 0, ...
    'initial_curtail_kwh', 0, ...
    'initial_renewable_kwh', 0, ...
    'remaining_max_renewable_kwh', 0, ...
    'max_renewable_per_step_kwh', 0, ...
    'checkpoint_interval_steps', 0, ...
    'is_year_end', mode == "annual");
if ~isfield(options, 'grid_budget') || ...
        ~isstruct(options.grid_budget) || ...
        isempty(fieldnames(options.grid_budget))
    return
end
accounting = string(option_value( ...
    options.grid_budget, 'accounting', ""));
supported = ["annual_cumulative_reachability", ...
    "annual_cumulative_observed_budget"];
if mode == "annual" || ~ismember(accounting, supported)
    error('dispatch_model:bad_grid_budget', ...
        'Unsupported rolling grid accounting mode.');
end
budget.accounting = accounting;
fields = {'initial_sell_kwh', 'initial_curtail_kwh', ...
    'initial_renewable_kwh', 'remaining_max_renewable_kwh'};
for field_index = 1:numel(fields)
    name = fields{field_index};
    budget.(name) = required_grid_scalar(options.grid_budget, name);
end
budget.max_renewable_per_step_kwh = optional_nonnegative_scalar( ...
    options.grid_budget, 'max_renewable_per_step_kwh', 0, ...
    'dispatch_model:bad_grid_budget', 'grid_budget');
budget.checkpoint_interval_steps = optional_nonnegative_integer( ...
    options.grid_budget, 'checkpoint_interval_steps', ...
    'dispatch_model:bad_grid_budget', 'grid_budget');
budget.is_year_end = budget.remaining_max_renewable_kwh <= 1e-9;
end

function value = required_grid_scalar(options, name)
if ~isfield(options, name)
    error('dispatch_model:bad_grid_budget', ...
        'grid_budget.%s is required.', name);
end
value = options.(name);
if ~(isnumeric(value) && isscalar(value) && ...
        isfinite(value) && value >= 0)
    error('dispatch_model:bad_grid_budget', ...
        'grid_budget.%s must be a finite nonnegative scalar.', name);
end
end

function carbon = carbon_settings(options, mode, enabled, time_count)
carbon = struct( ...
    'enabled', logical(enabled), ...
    'accounting', "disabled", ...
    'initial_emissions_kg', 0, ...
    'initial_nh3_kg', 0, ...
    'remaining_reference_nh3_kg', 0, ...
    'reference_nh3_per_step_kg', 0, ...
    'checkpoint_interval_steps', 0, ...
    'commit_reserve_kg', 0, ...
    'commit_steps', 0, ...
    'annual_emissions_budget_kg', 0, ...
    'annual_nh3_target_kg', 0, ...
    'production_target_at_commit_kg', 0, ...
    'budget_available_at_start_kg', 0, ...
    'budget_accrual_per_step_kg', 0, ...
    'is_year_end', false);
if ~carbon.enabled
    return
end

has_carbon_state = isfield(options, 'carbon') && ...
    isstruct(options.carbon) && ~isempty(fieldnames(options.carbon));
if mode == "annual"
    accounting = "annual_horizon";
    if has_carbon_state
        accounting = string(option_value( ...
            options.carbon, 'accounting', accounting));
    end
    if accounting ~= "annual_horizon"
        error('dispatch_model:bad_carbon_accounting', ...
            'Annual mode requires annual_horizon carbon accounting.');
    end
    carbon.accounting = accounting;
    carbon.is_year_end = true;
    return
end

if ~has_carbon_state
    error('dispatch_model:missing_carbon_state', ...
        ['Day-ahead and realtime modes require explicit annual ', ...
         'cumulative carbon state when the CO2 limit is enabled.']);
end
accounting = string(option_value(options.carbon, 'accounting', ""));
if ~isscalar(accounting) || ~ismember(accounting, [ ...
        "annual_cumulative_reachability", ...
        "annual_cumulative_absolute_budget"])
    error('dispatch_model:bad_carbon_accounting', ...
        'Unsupported rolling carbon accounting mode.');
end

carbon.accounting = accounting;
carbon.initial_emissions_kg = required_nonnegative_scalar( ...
    options.carbon, 'initial_emissions_kg');
carbon.initial_nh3_kg = required_nonnegative_scalar( ...
    options.carbon, 'initial_nh3_kg');
carbon.remaining_reference_nh3_kg = required_nonnegative_scalar( ...
    options.carbon, 'remaining_reference_nh3_kg');
carbon.reference_nh3_per_step_kg = optional_nonnegative_scalar( ...
    options.carbon, 'reference_nh3_per_step_kg', 0, ...
    'dispatch_model:bad_carbon_state', 'carbon');
carbon.checkpoint_interval_steps = optional_nonnegative_integer( ...
    options.carbon, 'checkpoint_interval_steps', ...
    'dispatch_model:bad_carbon_state', 'carbon');
carbon.commit_reserve_kg = optional_nonnegative_scalar( ...
    options.carbon, 'commit_reserve_kg', 0, ...
    'dispatch_model:bad_carbon_state', 'carbon');
carbon.commit_steps = optional_nonnegative_integer( ...
    options.carbon, 'commit_steps', ...
    'dispatch_model:bad_carbon_state', 'carbon');
if carbon.commit_steps > time_count
    error('dispatch_model:bad_carbon_state', ...
        'carbon.commit_steps cannot exceed the dispatch horizon.');
end
if accounting == "annual_cumulative_absolute_budget"
    carbon.annual_emissions_budget_kg = required_nonnegative_scalar( ...
        options.carbon, 'annual_emissions_budget_kg');
    carbon.annual_nh3_target_kg = required_nonnegative_scalar( ...
        options.carbon, 'annual_nh3_target_kg');
    carbon.production_target_at_commit_kg = ...
        required_nonnegative_scalar( ...
        options.carbon, 'production_target_at_commit_kg');
    carbon.budget_available_at_start_kg = required_nonnegative_scalar( ...
        options.carbon, 'budget_available_at_start_kg');
    carbon.budget_accrual_per_step_kg = required_nonnegative_scalar( ...
        options.carbon, 'budget_accrual_per_step_kg');
    is_year_end = option_value(options.carbon, 'is_year_end', false);
    if ~(islogical(is_year_end) && isscalar(is_year_end))
        error('dispatch_model:bad_carbon_state', ...
            'carbon.is_year_end must be a logical scalar.');
    end
    carbon.is_year_end = is_year_end;
else
    carbon.is_year_end = carbon.remaining_reference_nh3_kg <= 1e-9;
end
end

function value = optional_nonnegative_scalar( ...
        options, name, default_value, error_id, namespace)
value = option_value(options, name, default_value);
if ~(isnumeric(value) && isscalar(value) && ...
        isfinite(value) && value >= 0)
    error(error_id, '%s.%s must be a finite nonnegative scalar.', ...
        namespace, name);
end
end

function value = optional_nonnegative_integer( ...
        options, name, error_id, namespace)
value = option_value(options, name, 0);
if ~(isnumeric(value) && isscalar(value) && isfinite(value) && ...
        value >= 0 && value == floor(value))
    error(error_id, ...
        '%s.%s must be a nonnegative integer.', namespace, name);
end
end

function indices = reachability_checkpoints(time_count, interval)
if interval == 0
    indices = zeros(1, 0);
else
    indices = interval:interval:(time_count - 1);
end
end

function value = required_nonnegative_scalar(options, name)
if ~isfield(options, name)
    error('dispatch_model:bad_carbon_state', ...
        'carbon.%s is required.', name);
end
value = options.(name);
if ~(isnumeric(value) && isscalar(value) && ...
        isfinite(value) && value >= 0)
    error('dispatch_model:bad_carbon_state', ...
        'carbon.%s must be a finite nonnegative scalar.', name);
end
end

function contract = contract_settings( ...
        options, T, dt, hb_max_load, nh3_rate)
contract = struct();
contract.enabled = option_value(options, 'enabled', false);
contract.max_delay_days = [];
contract.daily_quantity_kg = [];
contract.daily_quantity_upper_kg = [];
contract.lcoa_cap_usd_per_t = [];
contract.samples_per_day = [];
contract.day_count = [];
contract.strict_delivery = false;
contract.terminal_clear = true;
contract.initial_cohorts_kg = [];
if ~contract.enabled
    return
end

samples_per_day = integer_samples_per_day(dt);
if mod(T, samples_per_day) ~= 0
    error('baseline:contract_requires_complete_days', ...
        'Contract mode requires a whole number of days.');
end
max_delay_days = option_value(options, 'max_delay_days', 7);
if ~(isnumeric(max_delay_days) && isscalar(max_delay_days) && ...
        isfinite(max_delay_days) && max_delay_days >= 0 && ...
        max_delay_days == floor(max_delay_days))
    error('baseline:bad_contract_delay', ...
        'max_delay_days must be a nonnegative integer.');
end
daily_upper = option_value(options, 'daily_quantity_upper_kg', ...
    hb_max_load * nh3_rate * 24);
if ~(isnumeric(daily_upper) && isscalar(daily_upper) && ...
        isfinite(daily_upper) && daily_upper > 0)
    error('baseline:bad_contract_upper_bound', ...
        'daily_quantity_upper_kg must be positive.');
end
daily_quantity = option_value(options, 'fixed_daily_quantity_kg', []);
if ~(isnumeric(daily_quantity) && isscalar(daily_quantity) && ...
        isfinite(daily_quantity) && daily_quantity > 0 && ...
        daily_quantity <= daily_upper + 1e-9)
    error('baseline:bad_fixed_contract_quantity', ...
        ['fixed_daily_quantity_kg must be positive and no greater ', ...
        'than daily_quantity_upper_kg.']);
end
lcoa_cap = option_value(options, 'lcoa_cap_usd_per_t', []);
if ~isempty(lcoa_cap) && ~(isnumeric(lcoa_cap) && isscalar(lcoa_cap) && ...
        isfinite(lcoa_cap) && lcoa_cap > 0)
    error('baseline:bad_lcoa_cap', ...
        'lcoa_cap_usd_per_t must be empty or positive.');
end

contract.max_delay_days = max_delay_days;
contract.daily_quantity_kg = daily_quantity;
contract.daily_quantity_upper_kg = daily_upper;
contract.lcoa_cap_usd_per_t = lcoa_cap;
contract.samples_per_day = samples_per_day;
contract.day_count = T / samples_per_day;
contract.strict_delivery = option_value(options, ...
    'strict_delivery', false);
contract.terminal_clear = option_value(options, 'terminal_clear', true);
initial_cohorts_kg = option_value(options, 'initial_cohorts_kg', ...
    zeros(max_delay_days, 1));
if ~(isnumeric(initial_cohorts_kg) && ...
        numel(initial_cohorts_kg) == max_delay_days && ...
        all(isfinite(initial_cohorts_kg(:))) && ...
        all(initial_cohorts_kg(:) >= 0))
    error('dispatch_model:bad_contract_cohorts', ...
        'initial_cohorts_kg must contain one nonnegative value per delay day.');
end
contract.initial_cohorts_kg = initial_cohorts_kg(:);
end

function [delivery, contract] = strict_delivery_variable(contract)
delay_offsets = 0:contract.max_delay_days;
initial_due_day = 1 - (1:contract.max_delay_days)';
new_due_day = (1:contract.day_count)';
obligation_due_day = [initial_due_day; new_due_day];
obligation_kg = [contract.initial_cohorts_kg; ...
    contract.daily_quantity_kg * ones(contract.day_count, 1)];
delivery_day = obligation_due_day + delay_offsets;
valid_delivery = delivery_day >= 1 & ...
    delivery_day <= contract.day_count;
upper_bound = obligation_kg .* ones(1, numel(delay_offsets));
upper_bound(~valid_delivery) = 0;

delivery = optimvar('contract_delivery', ...
    numel(obligation_kg), numel(delay_offsets), ...
    'LowerBound', 0, 'UpperBound', upper_bound);
contract.obligation_due_day = obligation_due_day;
contract.obligation_kg = obligation_kg;
contract.delivery_day = delivery_day;
contract.must_clear_in_horizon = contract.terminal_clear | ...
    obligation_due_day + contract.max_delay_days <= contract.day_count;
end

function prob = add_strict_delivery_constraints( ...
        prob, delivery, daily_nh3_kg, contract)
obligation_count = numel(contract.obligation_kg);
clear_indices = find(contract.must_clear_in_horizon);
carry_indices = find(~contract.must_clear_in_horizon);
clearance = optimconstr(numel(clear_indices), 1);
for constraint_index = 1:numel(clear_indices)
    obligation_index = clear_indices(constraint_index);
    delivered_kg = sum(delivery(obligation_index, :));
    clearance(constraint_index) = delivered_kg == ...
        contract.obligation_kg(obligation_index);
end
prob.Constraints.contract_cohort_clearance = clearance;
if ~isempty(carry_indices)
    carryover = optimconstr(numel(carry_indices), 1);
    for constraint_index = 1:numel(carry_indices)
        obligation_index = carry_indices(constraint_index);
        carryover(constraint_index) = ...
            sum(delivery(obligation_index, :)) <= ...
            contract.obligation_kg(obligation_index);
    end
    prob.Constraints.contract_cohort_carryover = carryover;
end

daily_supply = optimconstr(contract.day_count, 1);
for day_index = 1:contract.day_count
    delivered_today = 0;
    for obligation_index = 1:obligation_count
        offset_index = find( ...
            contract.delivery_day(obligation_index, :) == day_index, ...
            1, 'first');
        if ~isempty(offset_index)
            delivered_today = delivered_today + ...
                delivery(obligation_index, offset_index);
        end
    end
    daily_supply(day_index) = delivered_today <= daily_nh3_kg(day_index);
end
prob.Constraints.contract_daily_supply = daily_supply;
end

function validate_initial_state(state, storage_limits, module_count, hb)
if ~(isnumeric(state.h2_kg) && isscalar(state.h2_kg) && ...
        isfinite(state.h2_kg) && ...
        state.h2_kg >= storage_limits.min_mass - 1e-6 && ...
        state.h2_kg <= storage_limits.max_mass + 1e-6)
    error('dispatch_model:bad_initial_h2', ...
        'initial_state.h2_kg is outside physical storage bounds.');
end
if ~(isnumeric(state.ael_online_modules) && ...
        isscalar(state.ael_online_modules) && ...
        state.ael_online_modules == floor(state.ael_online_modules) && ...
        state.ael_online_modules >= 0 && ...
        state.ael_online_modules <= module_count)
    error('dispatch_model:bad_initial_ael', ...
        'initial AEL online modules must be a valid integer count.');
end
if ~isempty(state.hb_load) && ...
        ~(isnumeric(state.hb_load) && isscalar(state.hb_load) && ...
        isfinite(state.hb_load) && state.hb_load >= hb.min_load && ...
        state.hb_load <= hb.max_load)
    error('dispatch_model:bad_initial_hb', ...
        'initial HB load must be within operating bounds.');
end
end

function validate_fixed_vector(value, expected_count, name)
if ~isnumeric(value) || numel(value) ~= expected_count || ...
        any(~isfinite(value(:)))
    error('dispatch_model:bad_fixed_plan', ...
        'fixed_plan.%s must contain %d finite values.', ...
        name, expected_count);
end
end

function samples_per_day = integer_samples_per_day(dt)
samples_per_day = round(24 / dt);
if abs(samples_per_day - 24 / dt) > 1e-9
    error('baseline:bad_contract_time_step', ...
        'Contract mode requires dt to divide 24 hours exactly.');
end
end

function value = option_value(options, name, default_value)
if isstruct(options) && isfield(options, name) && ~isempty(options.(name))
    value = options.(name);
else
    value = default_value;
end
end

function value = field_value(options, name, default_value)
if isstruct(options) && isfield(options, name)
    value = options.(name);
else
    value = default_value;
end
end
