function [result, run_info, metrics] = rolling_dispatch(config)
% ROLLING_DISPATCH Run forecast planning, realtime recourse, and state handoff.
% The function reads one input MAT file, plans 72 hours, commits 24 hours,
% replays those controls against observed renewable power, and repeats.

if nargin < 1 || isempty(config)
    config = struct();
end
project_dir = project_root();
add_project_paths(project_dir);

source_mat_path = option_value(config, 'source_mat_path', ...
    fullfile(project_dir, 'runs', 'stage1', ...
    'zhou_s2_baseline_2022_latest.mat'));
save_output = option_value(config, 'save_output', true);
verbose = option_value(config, 'verbose', true);
scheme = string(option_value(config, 'scheme', ...
    "contract_plan_and_hb_smoothing"));
forecast_mode = string(option_value(config, 'forecast_mode', ...
    "simulated_persistence"));
loaded = load_input(source_mat_path);
params = loaded.params;
renewable_data = loaded.renewable_data;
source_run_info = loaded.run_info;
subprotocol = protocol_v5('v5_1');
validate_configuration(config, renewable_data, subprotocol, ...
    scheme, forecast_mode);
h2_reserve = h2_reserve_settings(config, subprotocol);
joint = joint_coordination_settings(config, params, subprotocol);
params = apply_joint_coordination_params(params, joint);
restoration = rolling_restoration_settings(config);

hour_count = renewable_data.time_count;
samples_per_day = round(24 / params.time.step);
day_count = hour_count / samples_per_day;
data_year = source_year(source_run_info, renewable_data);
output_dir = option_value(config, 'output_dir', ...
    fullfile(project_dir, 'runs', 'rolling'));
output_path = rolling_output_path( ...
    output_dir, scheme, data_year, h2_reserve, joint);
contract_enabled = scheme == "contract_plan_and_hb_smoothing";

run_info = initial_run_info(source_mat_path, scheme, forecast_mode, ...
    subprotocol, data_year, day_count, output_path, save_output);
run_info.h2_reserve = h2_reserve.summary;
run_info.joint = joint.summary;
run_info.restoration = restoration.summary;
run_info.allow_infeasible_continuation = ...
    restoration.allow_infeasible_continuation;
result = [];
metrics = [];

forecast_source = prepare_forecast_source( ...
    renewable_data, config, forecast_mode, subprotocol, data_year);
run_info.forecast_fallback_source = forecast_source.fallback_source;
storage_limits = h2_storage_limits( ...
    params.h2_storage, params.unit.h2_density);
annual_initial_h2_kg = storage_limits.initial_mass;
if option_value(config, 'dry_run', false)
    first_forecast = forecast_window( ...
        forecast_source, renewable_data, 1, ...
        min(subprotocol.RollingDispatch.PlanningHours, hour_count));
    dry_state = initial_rolling_state( ...
        annual_initial_h2_kg, subprotocol);
    dry_remaining_after_commit_count = max( ...
        0, hour_count - round(24 / params.time.step));
    [dry_h2_reserve, dry_h2_reserve_gate] = ...
        gated_h2_reserve_for_day(h2_reserve, joint, dry_state, ...
        params, subprotocol.Contract.DailyQuantityKG, subprotocol, ...
        dry_remaining_after_commit_count);
    dry_options = planning_options(dry_state, subprotocol, ...
        subprotocol.Contract.DailyQuantityKG, contract_enabled, ...
        first_forecast.time_count == hour_count, ...
        annual_initial_h2_kg, params, ...
        hour_count - first_forecast.time_count, 0, ...
        first_forecast.time_count, first_forecast, ...
        dry_h2_reserve, joint.contract_pacing_aggressiveness);
    run_info.status = "ready";
    run_info.first_forecast_hour_count = first_forecast.time_count;
    run_info.first_h2_reserve = dry_options.h2_reserve;
    run_info.first_h2_reserve_gate = dry_h2_reserve_gate;
    run_info.first_production = dry_options.production;
    run_info.output_path = "";
    return
end

state = initial_rolling_state(annual_initial_h2_kg, subprotocol);
realized = empty_solution(hour_count, annual_initial_h2_kg);
day_ahead = empty_plan(hour_count);
records = empty_solver_records(day_count);
carbon_history = empty_carbon_history(day_count);
carbon_reserve_quantile = option_value( ...
    config, 'carbon_reserve_quantile', ...
    default_carbon_reserve_quantile());
carbon_reserve_history = empty_carbon_reserve_history( ...
    day_count, carbon_reserve_quantile, ...
    minimum_absolute_carbon_reserve_kg(params, contract_enabled));
production_pacing_history = empty_production_pacing_history(day_count);
hb_recourse_history = empty_hb_recourse_history(day_count);
daily_contract_kg = subprotocol.Contract.DailyQuantityKG;
if contract_enabled
    carbon_history.accounting = "annual_cumulative_reachability";
else
    carbon_history.accounting = "annual_cumulative_absolute_budget";
end
run_info.carbon_accounting = carbon_history.accounting;
failure_context = struct();

try
    for day_index = 1:day_count
        failure_context = struct('day_index', day_index, 'state', state);
        first_hour = (day_index - 1) * samples_per_day + 1;
        plan_hour_count = min( ...
            subprotocol.RollingDispatch.PlanningHours, ...
            hour_count - first_hour + 1);
        plan_indices = first_hour:first_hour + plan_hour_count - 1;
        commit_indices = first_hour:first_hour + samples_per_day - 1;
        commit_count = numel(commit_indices);
        is_final_window = plan_indices(end) == hour_count;
        remaining_after_commit_count = hour_count - commit_indices(end);

        forecast_data = forecast_window( ...
            forecast_source, renewable_data, day_index, plan_hour_count);
        [effective_h2_reserve, h2_reserve_gate] = ...
            gated_h2_reserve_for_day(h2_reserve, joint, state, ...
            params, daily_contract_kg, subprotocol, ...
            remaining_after_commit_count);
        [base_carbon_reserve_kg, carbon_reserve_history] = ...
            carbon_reserve_for_day( ...
            carbon_reserve_history, day_index, params);
        h2_carbon_guard_kg = h2_reserve_carbon_guard_kg( ...
            params, daily_contract_kg, effective_h2_reserve, subprotocol);
        carbon_reserve_kg = max(base_carbon_reserve_kg, ...
            h2_carbon_guard_kg);
        failure_context.carbon_reserve_kg = carbon_reserve_kg;
        failure_context.base_carbon_reserve_kg = base_carbon_reserve_kg;
        failure_context.h2_carbon_guard_kg = h2_carbon_guard_kg;
        plan_options = planning_options(state, subprotocol, ...
            daily_contract_kg, contract_enabled, is_final_window, ...
            annual_initial_h2_kg, params, ...
            hour_count - plan_indices(end), carbon_reserve_kg, ...
            plan_hour_count, forecast_data, effective_h2_reserve, ...
            joint.contract_pacing_aggressiveness);
        failure_context.plan_options = plan_options;
        if contract_enabled
            requested_production_target_kg = NaN;
        else
            requested_production_target_kg = ...
                plan_options.carbon.production_target_at_commit_kg;
        end
        applied_production_target_kg = requested_production_target_kg;
        production_pacing_history.requested_target_kg(day_index) = ...
            requested_production_target_kg;
        plan_model = dispatch_model(params, forecast_data, plan_options);
        [plan_sol, plan_fval, plan_exitflag, plan_output, ...
            plan_time, plan_succeeded] = solve_dispatch( ...
            plan_model.problem, config, "day_ahead", true);
        applied_plan_reserve_kg = carbon_reserve_kg;
        applied_h2_reserve_scale = effective_h2_reserve.target_scale;
        if ~plan_succeeded && effective_h2_reserve.active
            [plan_sol, plan_fval, plan_exitflag, plan_output, ...
                plan_time, plan_succeeded, plan_options, ...
                applied_h2_reserve_scale, carbon_reserve_kg, ...
                h2_carbon_guard_kg] = project_h2_reserve_plan( ...
                config, state, subprotocol, daily_contract_kg, ...
                contract_enabled, is_final_window, annual_initial_h2_kg, ...
                params, hour_count - plan_indices(end), ...
                base_carbon_reserve_kg, plan_hour_count, forecast_data, ...
                effective_h2_reserve, ...
                joint.contract_pacing_aggressiveness, plan_time);
            failure_context.plan_options = plan_options;
            failure_context.carbon_reserve_kg = carbon_reserve_kg;
            failure_context.h2_carbon_guard_kg = h2_carbon_guard_kg;
            applied_plan_reserve_kg = carbon_reserve_kg;
        end
        if ~plan_succeeded
            projection_options = plan_options;
            projection_options.carbon.commit_reserve_kg = 0;
            projection_options.objective_mode = ...
                "minimize_commit_carbon_debt";
            projection_model = dispatch_model( ...
                params, forecast_data, projection_options);
            [projection_sol, ~, projection_exitflag, projection_output, ...
                projection_time, projection_succeeded] = ...
                solve_dispatch(projection_model.problem, config, ...
                "day_ahead_carbon_projection", true);
            if ~projection_succeeded
                if restoration.allow_infeasible_continuation
                    projection_options = restoration_plan_options( ...
                        plan_options, restoration);
                    projection_options.carbon.commit_reserve_kg = 0;
                    projection_options.objective_mode = ...
                        "minimize_commit_carbon_debt";
                    projection_model = dispatch_model( ...
                        params, forecast_data, projection_options);
                    [projection_sol, ~, projection_exitflag, ...
                        projection_output, restore_projection_time] = ...
                        solve_dispatch(projection_model.problem, config, ...
                        "day_ahead_restoration_projection");
                    projection_time = projection_time ...
                        + restore_projection_time;
                    plan_options = projection_options;
                    plan_options.objective_mode = "economic";
                    carbon_reserve_kg = 0;
                    h2_carbon_guard_kg = 0;
                    applied_plan_reserve_kg = 0;
                    production_pacing_history.day_ahead_restored( ...
                        day_index) = true;
                elseif contract_enabled || is_final_window
                    error('rolling_dispatch:solve_failed', ...
                        ['day_ahead_carbon_projection solve failed or ', ...
                         'did not converge. Exitflag: %d. Message: %s'], ...
                        projection_exitflag, projection_output.message);
                end
                target_options = projection_options;
                target_options.carbon.production_target_at_commit_kg = ...
                    state.nh3_produced_kg;
                target_options.objective_mode = "maximize_commit_nh3";
                target_model = dispatch_model( ...
                    params, forecast_data, target_options);
                [target_sol, ~, ~, ~, target_time] = solve_dispatch( ...
                    target_model.problem, config, ...
                    "day_ahead_production_projection");
                maximum_target_kg = state.nh3_produced_kg ...
                    + sum(target_sol.HB_load(1:commit_count)) ...
                    * params.HB.nh3_output * params.time.step;
                applied_production_target_kg = min( ...
                    requested_production_target_kg, maximum_target_kg);
                plan_options.carbon.production_target_at_commit_kg = max( ...
                    state.nh3_produced_kg, ...
                    applied_production_target_kg - 1e-3);
                projection_options = plan_options;
                projection_options.carbon.commit_reserve_kg = 0;
                projection_options.objective_mode = ...
                    "minimize_commit_carbon_debt";
                projection_model = dispatch_model( ...
                    params, forecast_data, projection_options);
                [projection_sol, ~, ~, ~, projected_target_time] = ...
                    solve_dispatch(projection_model.problem, config, ...
                    "day_ahead_projected_production");
                projection_time = projection_time + target_time ...
                    + projected_target_time;
                production_pacing_history.day_ahead_projected( ...
                    day_index) = true;
            end
            projection_nh3_kg = sum( ...
                projection_sol.HB_load(1:commit_count)) ...
                * params.HB.nh3_output * params.time.step;
            projection_emissions_kg = params.environment.grid_co2 ...
                * sum(projection_sol.p_purchase(1:commit_count)) ...
                * params.time.step;
            if projection_options.carbon.accounting == ...
                    "annual_cumulative_absolute_budget"
                available_plan_reserve_kg = ...
                    available_absolute_carbon_budget( ...
                    projection_options.carbon, commit_count) ...
                    - state.co2_emitted_kg - projection_emissions_kg;
            else
                projection_debt_kg = state.co2_emitted_kg ...
                    + projection_emissions_kg ...
                    - params.environment.co2_limit ...
                    * (state.nh3_produced_kg + projection_nh3_kg);
                commit_remaining_reference_kg = ...
                    projection_options.carbon.remaining_reference_nh3_kg ...
                    + (plan_hour_count - commit_count) ...
                    * projection_options.carbon.reference_nh3_per_step_kg;
                available_plan_reserve_kg = ...
                    params.environment.co2_limit ...
                    * commit_remaining_reference_kg - projection_debt_kg;
            end
            applied_plan_reserve_kg = min(carbon_reserve_kg, ...
                max(available_plan_reserve_kg, 0));
            plan_options.carbon.commit_reserve_kg = ...
                max(applied_plan_reserve_kg - 1e-3, 0);
            plan_model = dispatch_model( ...
                params, forecast_data, plan_options);
            [plan_sol, plan_fval, plan_exitflag, plan_output, ...
                projected_plan_time] = solve_dispatch( ...
                plan_model.problem, config, "day_ahead_projected");
            plan_time = plan_time + projection_time ...
                + projected_plan_time;
        end
        production_pacing_history.contract_commit_min_nh3_kg( ...
            day_index) = plan_options.production.commit_min_nh3_kg;
        production_pacing_history.contract_allowable_backlog_kg( ...
            day_index) = ...
            plan_options.production.allowable_backlog_after_commit_kg;
        production_pacing_history.contract_h2_commit_min_kg( ...
            day_index) = scalar_or_nan( ...
            plan_options.terminal.h2_commit_min_kg);
        production_pacing_history.h2_reserve_target_min_kg( ...
            day_index) = plan_options.h2_reserve.target_min_kg;
        production_pacing_history.h2_reserve_raw_deficit_kg( ...
            day_index) = plan_options.h2_reserve.raw_deficit_quantile_kg;
        production_pacing_history.h2_reserve_deficit_kg( ...
            day_index) = plan_options.h2_reserve.deficit_quantile_kg;
        production_pacing_history.h2_reserve_applied_scale( ...
            day_index) = applied_h2_reserve_scale;
        production_pacing_history.h2_reserve_projected(day_index) = ...
            applied_h2_reserve_scale ...
            < effective_h2_reserve.target_scale - 1e-12;
        production_pacing_history.h2_reserve_carbon_guard_kg( ...
            day_index) = h2_carbon_guard_kg;
        production_pacing_history.h2_reserve_gate_open(day_index) = ...
            h2_reserve_gate.open;
        production_pacing_history.h2_reserve_gate_reason(day_index) = ...
            h2_reserve_gate.reason;
        carbon_reserve_history.applied_reserve_kgco2(day_index) = ...
            applied_plan_reserve_kg;
        production_pacing_history.day_ahead_target_kg(day_index) = ...
            applied_production_target_kg;
        records = record_solver(records, day_index, "plan", ...
            plan_fval, plan_exitflag, plan_output, plan_time);

        day_ahead = assign_plan(day_ahead, commit_indices, ...
            plan_sol, forecast_data, commit_count);
        actual_data = renewable_slice(renewable_data, commit_indices);
        recourse_options = recourse_options_for_day( ...
            state, plan_sol, commit_count, day_index == day_count, ...
            annual_initial_h2_kg, params, daily_contract_kg, ...
            contract_enabled, subprotocol, applied_plan_reserve_kg, ...
            hour_count - commit_indices(end), ...
            plan_options.hydrogen.min_storage_kg_by_step( ...
            1:commit_count), ...
            plan_options.hydrogen.reserve_floor_soft, ...
            plan_options.hydrogen.reserve_slack_penalty_usd_per_kg, ...
            joint.contract_pacing_aggressiveness, ...
            restoration_from_options(plan_options));
        if ~contract_enabled
            recourse_options.carbon.production_target_at_commit_kg = ...
                applied_production_target_kg;
        end
        failure_context.plan_solution = plan_sol;
        failure_context.actual_data = actual_data;
        failure_context.recourse_options = recourse_options;
        recourse_model = dispatch_model( ...
            params, actual_data, recourse_options);
        [actual_sol, actual_fval, actual_exitflag, ...
            actual_output, actual_time, recourse_succeeded] = ...
            solve_dispatch(recourse_model.problem, config, ...
            "realtime", true);
        fallback_invoked = ~recourse_succeeded;
        if fallback_invoked
            target_hb = recourse_options.fixed_plan.HB_load;
            target_ael = recourse_options.fixed_plan.AEL_commitment;
            fallback_options = recourse_options;
            fallback_options.fixed_plan = rmfield( ...
                fallback_options.fixed_plan, 'HB_load');
            fallback_options.fixed_plan = rmfield( ...
                fallback_options.fixed_plan, 'AEL_commitment');
            fallback_options.fixed_plan.HB_load_upper = target_hb;
            fallback_options.fixed_plan.AEL_commitment_upper = target_ael;
            fallback_options.carbon.commit_reserve_kg = 0;
            if ~contract_enabled && day_index < day_count
                target_options = fallback_options;
                target_options.carbon.production_target_at_commit_kg = ...
                    state.nh3_produced_kg;
                target_options.objective_mode = "maximize_commit_nh3";
                target_model = dispatch_model( ...
                    params, actual_data, target_options);
                [target_sol, ~, ~, ~, target_time] = solve_dispatch( ...
                    target_model.problem, config, ...
                    "realtime_production_projection");
                maximum_target_kg = state.nh3_produced_kg ...
                    + sum(target_sol.HB_load) * params.HB.nh3_output ...
                    * params.time.step;
                realtime_target_kg = min( ...
                    applied_production_target_kg, maximum_target_kg);
                fallback_options.carbon.production_target_at_commit_kg = ...
                    max(state.nh3_produced_kg, realtime_target_kg - 1e-3);
                production_pacing_history.realtime_target_kg(day_index) = ...
                    realtime_target_kg;
                production_pacing_history.realtime_projected(day_index) = ...
                    realtime_target_kg < applied_production_target_kg - 1e-3;
            else
                target_time = 0;
                production_pacing_history.realtime_target_kg(day_index) = ...
                    applied_production_target_kg;
            end
            fallback_options.objective_mode = "minimize_carbon_debt";
            phase1_model = dispatch_model( ...
                params, actual_data, fallback_options);
            [phase1_sol, ~, ~, ~, phase1_time] = solve_dispatch( ...
                phase1_model.problem, config, "realtime_carbon_phase1");
            phase1_nh3_kg = sum(phase1_sol.HB_load) ...
                * params.HB.nh3_output * params.time.step;
            phase1_emissions_kg = params.environment.grid_co2 ...
                * sum(phase1_sol.p_purchase) * params.time.step;
            phase1_debt_kg = ...
                fallback_options.carbon.initial_emissions_kg ...
                + phase1_emissions_kg - params.environment.co2_limit ...
                * (fallback_options.carbon.initial_nh3_kg ...
                + phase1_nh3_kg);
            if fallback_options.carbon.accounting == ...
                    "annual_cumulative_absolute_budget"
                available_margin_kg = ...
                    available_absolute_carbon_budget( ...
                    fallback_options.carbon, commit_count) ...
                    - fallback_options.carbon.initial_emissions_kg ...
                    - phase1_emissions_kg;
            else
                available_margin_kg = ...
                    params.environment.co2_limit ...
                    * fallback_options.carbon.remaining_reference_nh3_kg ...
                    - phase1_debt_kg;
            end
            projected_reserve_kg = min( ...
                recourse_options.carbon.commit_reserve_kg, ...
                max(available_margin_kg, 0));
            fallback_options.carbon.commit_reserve_kg = ...
                max(projected_reserve_kg - 1e-3, 0);
            fallback_options.objective_mode = "minimize_hb_shortfall";
            phase2_model = dispatch_model( ...
                params, actual_data, fallback_options);
            [phase2_sol, ~, ~, ~, phase2_time] = solve_dispatch( ...
                phase2_model.problem, config, "realtime_hb_phase2");
            minimum_shortfall = sum(target_hb - phase2_sol.HB_load) ...
                * params.time.step;
            fallback_options.fixed_plan.max_hb_shortfall_load_hours = ...
                minimum_shortfall + 1e-5;
            fallback_options.objective_mode = "economic";
            recourse_model = dispatch_model( ...
                params, actual_data, fallback_options);
            [actual_sol, actual_fval, actual_exitflag, ...
                actual_output, phase3_time] = solve_dispatch( ...
                recourse_model.problem, config, "realtime_economic_phase3");
            actual_time = actual_time + target_time + phase1_time ...
                + phase2_time + phase3_time;
        end
        if ~fallback_invoked
            production_pacing_history.realtime_target_kg(day_index) = ...
                applied_production_target_kg;
        end
        records = record_solver(records, day_index, "recourse", ...
            actual_fval, actual_exitflag, actual_output, actual_time);
        actual_sol.P_AEL_start = ...
            recourse_model.context.AEL_start_power_per_module ...
            * actual_sol.SU_AEL;
        realized = assign_solution( ...
            realized, commit_indices, actual_sol);
        carbon_reserve_history.realized_shortfall_kwh(day_index) = ...
            renewable_shortfall_kwh( ...
            forecast_data, actual_data, commit_count, params);
        planned_purchase_kwh = sum( ...
            plan_sol.p_purchase(1:commit_count)) * params.time.step;
        actual_purchase_kwh = sum(actual_sol.p_purchase) * params.time.step;
        carbon_reserve_history.planned_purchase_kwh(day_index) = ...
            planned_purchase_kwh;
        carbon_reserve_history.actual_purchase_kwh(day_index) = ...
            actual_purchase_kwh;
        carbon_reserve_history.purchase_exposure_kwh(day_index) = ...
            max(actual_purchase_kwh - planned_purchase_kwh, 0);
        target_nh3_kg = sum(plan_sol.HB_load(1:commit_count)) ...
            * params.HB.nh3_output * params.time.step;
        actual_nh3_kg = sum(actual_sol.HB_load) ...
            * params.HB.nh3_output * params.time.step;
        hb_recourse_history.fallback_invoked(day_index) = fallback_invoked;
        hb_recourse_history.target_nh3_kg(day_index) = target_nh3_kg;
        hb_recourse_history.actual_nh3_kg(day_index) = actual_nh3_kg;
        hb_recourse_history.shortfall_nh3_kg(day_index) = ...
            max(target_nh3_kg - actual_nh3_kg, 0);
        hb_recourse_history.requested_carbon_reserve_kg(day_index) = ...
            recourse_options.carbon.commit_reserve_kg;
        if recourse_options.carbon.accounting == ...
                "annual_cumulative_absolute_budget"
            hb_recourse_history.realized_carbon_margin_kg(day_index) = ...
                available_absolute_carbon_budget( ...
                recourse_options.carbon, commit_count) ...
                - state.co2_emitted_kg ...
                - params.environment.grid_co2 * actual_purchase_kwh;
        else
            actual_carbon_debt_kg = state.co2_emitted_kg ...
                + params.environment.grid_co2 * actual_purchase_kwh ...
                - params.environment.co2_limit ...
                * (state.nh3_produced_kg + actual_nh3_kg);
            hb_recourse_history.realized_carbon_margin_kg(day_index) = ...
                params.environment.co2_limit ...
                * recourse_options.carbon.remaining_reference_nh3_kg ...
                - actual_carbon_debt_kg;
        end
        hb_recourse_history.target_ael_module_hours(day_index) = ...
            sum(plan_sol.n_ael(1:commit_count)) * params.time.step;
        hb_recourse_history.actual_ael_module_hours(day_index) = ...
            sum(actual_sol.n_ael) * params.time.step;
        hb_recourse_history.ael_shortfall_module_hours(day_index) = ...
            max(hb_recourse_history.target_ael_module_hours(day_index) ...
            - hb_recourse_history.actual_ael_module_hours(day_index), 0);

        daily_nh3_kg = sum(actual_sol.HB_load) ...
            * params.HB.nh3_output * params.time.step;
        [next_cohorts, expired_kg] = update_contract_cohorts( ...
            state.contract_cohorts_kg, daily_contract_kg, daily_nh3_kg);
        production_pacing_history.expired_contract_kg(day_index) = ...
            expired_kg;
        if contract_enabled && expired_kg > 1e-3 && ...
                ~restoration.allow_infeasible_continuation
            error('rolling_dispatch:strict_delivery_breach', ...
                'Contract cohort expired on operating day %d by %.6f kg.', ...
                day_index, expired_kg);
        end
        state.h2_kg = actual_sol.storage_H2(end);
        state.ael_online_modules = round(actual_sol.n_ael(end));
        state.hb_load = min(params.HB.max_load, ...
            max(params.HB.min_load, actual_sol.HB_load(end)));
        daily_emissions_kg = params.environment.grid_co2 ...
            * sum(actual_sol.p_purchase) * params.time.step;
        state.co2_emitted_kg = clean_nonnegative_state_value( ...
            state.co2_emitted_kg + daily_emissions_kg, ...
            'co2_emitted_kg');
        state.nh3_produced_kg = clean_nonnegative_state_value( ...
            state.nh3_produced_kg + daily_nh3_kg, ...
            'nh3_produced_kg');
        state.sell_kwh = clean_nonnegative_state_value( ...
            state.sell_kwh + sum(actual_sol.p_sell) ...
            * params.time.step, 'sell_kwh');
        state.curtail_kwh = clean_nonnegative_state_value( ...
            state.curtail_kwh + sum(actual_sol.p_curt) ...
            * params.time.step, 'curtail_kwh');
        state.renewable_kwh = clean_nonnegative_state_value( ...
            state.renewable_kwh ...
            + sum(actual_data.pv_power_kw + actual_data.pw_power_kw) ...
            * params.renewable.input_scale * params.time.step, ...
            'renewable_kwh');
        state.contract_cohorts_kg = next_cohorts;
        carbon_history = record_carbon_day(carbon_history, day_index, ...
            daily_emissions_kg, daily_nh3_kg, state, params, ...
            daily_contract_kg, contract_enabled, ...
            hour_count - commit_indices(end));

        if verbose
            fprintf(['Completed day %d/%d: plan %.2fs, ', ...
                'recourse %.2fs.\n'], ...
                day_index, day_count, plan_time, actual_time);
        end
    end

    terminal_contract_backlog_kg = 0;
    if contract_enabled
        terminal_contract_backlog_kg = sum(state.contract_cohorts_kg);
    end
    run_info.terminal_contract_backlog_kg = terminal_contract_backlog_kg;
    if contract_enabled && terminal_contract_backlog_kg > 1e-3 && ...
            ~restoration.allow_infeasible_continuation
        error('rolling_dispatch:terminal_contract_breach', ...
            'Year-end unserved contract is %.6f kg.', ...
            terminal_contract_backlog_kg);
    end
    if ~restoration.allow_infeasible_continuation
        require_annual_carbon_feasibility(state, params);
        require_annual_grid_feasibility(state, params);
    end
catch exception
    run_info.status = "requires_slack_diagnosis";
    run_info.failed_day = first_unfinished_day(records);
    run_info.error_id = string(exception.identifier);
    run_info.error_message = string(exception.message);
    run_info.solver_records = records;
    run_info.carbon_state = carbon_state_summary(state, params);
    run_info.grid_state = grid_state_summary(state, params);
    run_info.carbon_history = carbon_history;
    run_info.carbon_reserve_history = carbon_reserve_history;
    run_info.production_pacing_history = production_pacing_history;
    run_info.hb_recourse_history = hb_recourse_history;
    run_info.restoration.used_day_count = ...
        nnz(production_pacing_history.day_ahead_restored);
    run_info.restoration.expired_contract_kg = ...
        sum(production_pacing_history.expired_contract_kg, 'omitnan');
    run_info.slack_diagnosis = slack_diagnosis_plan();
    diagnosis = classify_failure(run_info, failure_context, params);
    run_info.infeasibility_diagnosis = diagnosis;
    if save_output
        ensure_directory(output_dir);
        save(output_path, 'run_info', 'params', 'renewable_data', ...
            'source_run_info', 'failure_context', 'diagnosis');
    end
    rethrow(exception)
end

context = result_context(params, renewable_data);
aggregate_output = aggregate_solver_output(records);
if verbose
    result = results(params, renewable_data, realized, 0, 1, ...
        aggregate_output, context);
else
    evalc('result = results(params, renewable_data, realized, 0, 1, aggregate_output, context);');
end
result.fval = -result.summary.net_profit;
result.cost.objective_value = result.fval;
result.optimization.mode = 'rolling_day_ahead_with_realtime_recourse';
result.optimization.objective_value = result.fval;
result.day_ahead = day_ahead;
result.carbon = carbon_history;
result.hb_recourse = hb_recourse_history;
metrics = calculate_metrics(result, params, renewable_data, day_ahead, ...
    subprotocol, daily_contract_kg, contract_enabled);
result.contract = metrics.Contract;

run_info.status = "completed";
run_info.solver_records = records;
final_carbon = carbon_state_summary(state, params);
run_info.carbon_accounting = carbon_history.accounting;
run_info.final_carbon_emissions_kg = final_carbon.emissions_kg;
run_info.final_nh3_kg = final_carbon.nh3_kg;
run_info.final_carbon_debt_kg = final_carbon.debt_kg;
final_grid = grid_state_summary(state, params);
run_info.grid_accounting = "annual_cumulative_observed_budget";
run_info.final_sell_kwh = final_grid.sell_kwh;
run_info.final_curtail_kwh = final_grid.curtail_kwh;
run_info.final_renewable_kwh = final_grid.renewable_kwh;
run_info.carbon_reserve_history = carbon_reserve_history;
run_info.production_pacing_history = production_pacing_history;
run_info.hb_recourse_history = hb_recourse_history;
run_info.restoration.used_day_count = ...
    nnz(production_pacing_history.day_ahead_restored);
run_info.restoration.expired_contract_kg = ...
    sum(production_pacing_history.expired_contract_kg, 'omitnan');
run_info.output_path = "";
if save_output
    ensure_directory(output_dir);
    run_info.output_path = string(output_path);
    save(output_path, 'result', 'run_info', 'metrics', 'params', ...
        'renewable_data', 'source_run_info');
end
end

function loaded = load_input(source_mat_path)
if isstring(source_mat_path) && isscalar(source_mat_path)
    source_mat_path = char(source_mat_path);
end
if ~isfile(source_mat_path)
    error('rolling_dispatch:missing_input', ...
        'Missing input MAT file: %s', source_mat_path);
end
loaded = load(source_mat_path, 'params', 'renewable_data', 'run_info');
required = {'params', 'renewable_data', 'run_info'};
for field_index = 1:numel(required)
    if ~isfield(loaded, required{field_index})
        error('rolling_dispatch:bad_input', ...
            'Input MAT file must contain %s.', required{field_index});
    end
end
end

function validate_configuration(config, renewable_data, subprotocol, ...
        scheme, forecast_mode)
if ~protocol_v5('verify_v5_1', subprotocol)
    error('rolling_dispatch:bad_protocol', ...
        'Protocol v5.1 verification failed.');
end
supported_schemes = [ ...
    "economic_only", ...
    "contract_plan_and_hb_smoothing"];
if ~isscalar(scheme) || ~ismember(scheme, supported_schemes)
    error('rolling_dispatch:unsupported_scheme', ...
        'The current closed loop supports economic_only and contract planning.');
end
if ~isscalar(forecast_mode) || ...
        ~ismember(forecast_mode, ...
        ["simulated_persistence", "observed_oracle", "table"])
    error('rolling_dispatch:bad_forecast_mode', ...
        ['forecast_mode must be simulated_persistence, ', ...
         'observed_oracle, or table.']);
end
reserve_quantile = option_value(config, 'carbon_reserve_quantile', ...
    default_carbon_reserve_quantile());
if ~(isnumeric(reserve_quantile) && isscalar(reserve_quantile) && ...
        isfinite(reserve_quantile) && reserve_quantile >= 0 && ...
        reserve_quantile <= 1)
    error('rolling_dispatch:bad_carbon_reserve_quantile', ...
        'carbon_reserve_quantile must be a finite scalar in [0, 1].');
end
dt = renewable_data_time_step(renewable_data);
samples_per_day = 24 / dt;
if abs(samples_per_day - round(samples_per_day)) > 1e-9 || ...
        mod(renewable_data.time_count, round(samples_per_day)) ~= 0
    error('rolling_dispatch:incomplete_days', ...
        'Input must contain complete operating days.');
end
if subprotocol.RollingDispatch.PlanningHours ~= 72 || ...
        subprotocol.RollingDispatch.CommitHours ~= 24
    error('rolling_dispatch:protocol_horizon_drift', ...
        'The implementation requires the frozen 72/24-hour protocol.');
end
end

function quantile = default_carbon_reserve_quantile()
quantile = 0;
end

function reserve = h2_reserve_settings(config, subprotocol)
quantile = option_value(config, 'h2_reserve_quantile', 0);
lookahead_days = option_value(config, 'h2_reserve_lookahead_days', 0);
if ~(isnumeric(quantile) && isscalar(quantile) && ...
        isfinite(quantile) && quantile >= 0 && quantile <= 1)
    error('rolling_dispatch:bad_h2_reserve_quantile', ...
        'h2_reserve_quantile must be a finite scalar in [0, 1].');
end
if quantile > 0 && lookahead_days == 0
    lookahead_days = subprotocol.Calibration.CandidateGrid ...
        .ReserveLookaheadDays(1);
end
if ~(isnumeric(lookahead_days) && isscalar(lookahead_days) && ...
        isfinite(lookahead_days) && lookahead_days >= 0 && ...
        lookahead_days == floor(lookahead_days))
    error('rolling_dispatch:bad_h2_reserve_lookahead', ...
        'h2_reserve_lookahead_days must be a nonnegative integer.');
end
maximum_lookahead_days = ...
    subprotocol.RollingDispatch.PlanningHours / 24;
if lookahead_days > maximum_lookahead_days
    error('rolling_dispatch:bad_h2_reserve_lookahead', ...
        ['h2_reserve_lookahead_days cannot exceed the frozen ', ...
         'planning horizon.']);
end
reserve = struct();
reserve.active = quantile > 0;
reserve.quantile = quantile;
reserve.lookahead_days = lookahead_days;
reserve.target_scale = option_value(config, 'h2_reserve_target_scale', 1);
if ~(isnumeric(reserve.target_scale) && isscalar(reserve.target_scale) && ...
        isfinite(reserve.target_scale) && reserve.target_scale >= 0 && ...
        reserve.target_scale <= 1)
    error('rolling_dispatch:bad_h2_reserve_target_scale', ...
        'h2_reserve_target_scale must be a finite scalar in [0, 1].');
end
reserve.method = "future_cumulative_h2_deficit_quantile";
reserve.soft = option_value(config, 'h2_reserve_soft', false);
if ~(islogical(reserve.soft) && isscalar(reserve.soft))
    error('rolling_dispatch:bad_h2_reserve_soft', ...
        'h2_reserve_soft must be a scalar logical.');
end
reserve.soft_penalty_usd_per_kg = option_value(config, ...
    'h2_reserve_soft_penalty_usd_per_kg', 100);
if ~(isnumeric(reserve.soft_penalty_usd_per_kg) && ...
        isscalar(reserve.soft_penalty_usd_per_kg) && ...
        isfinite(reserve.soft_penalty_usd_per_kg) && ...
        reserve.soft_penalty_usd_per_kg >= 0)
    error('rolling_dispatch:bad_h2_reserve_soft', ...
        ['h2_reserve_soft_penalty_usd_per_kg must be a finite ', ...
         'nonnegative scalar.']);
end
reserve.summary = struct( ...
    'active', reserve.active, ...
    'quantile', reserve.quantile, ...
    'lookahead_days', reserve.lookahead_days, ...
    'target_scale', reserve.target_scale, ...
    'soft', reserve.soft, ...
    'soft_penalty_usd_per_kg', reserve.soft_penalty_usd_per_kg, ...
    'method', reserve.method);
end

function joint = joint_coordination_settings(config, params, subprotocol)
pacing = option_value(config, 'contract_pacing_aggressiveness', 0);
smoothing = option_value(config, ...
    'hb_smoothing_reduction_fraction', 0);
if ~(isnumeric(pacing) && isscalar(pacing) && isfinite(pacing) && ...
        pacing >= 0 && pacing <= 1)
    error('rolling_dispatch:bad_contract_pacing', ...
        'contract_pacing_aggressiveness must be a finite scalar in [0, 1].');
end
if ~(isnumeric(smoothing) && isscalar(smoothing) && ...
        isfinite(smoothing) && smoothing >= 0 && smoothing < 1)
    error('rolling_dispatch:bad_hb_smoothing', ...
        'hb_smoothing_reduction_fraction must be finite in [0, 1).');
end
gate_mode = string(option_value(config, ...
    'h2_reserve_gate_mode', "off"));
if ~isscalar(gate_mode) || ~ismember(gate_mode, ...
        ["off", "contract_carbon_state_gate"])
    error('rolling_dispatch:bad_h2_reserve_gate_mode', ...
        ['h2_reserve_gate_mode must be off or ', ...
         'contract_carbon_state_gate.']);
end
backlog_fraction = option_value(config, ...
    'h2_reserve_gate_backlog_fraction', 0.85);
carbon_guard_days = option_value(config, ...
    'h2_reserve_gate_carbon_guard_days', 0);
if ~(isnumeric(backlog_fraction) && isscalar(backlog_fraction) && ...
        isfinite(backlog_fraction) && backlog_fraction >= 0 && ...
        backlog_fraction <= 1)
    error('rolling_dispatch:bad_h2_reserve_gate', ...
        'h2_reserve_gate_backlog_fraction must be in [0, 1].');
end
if ~(isnumeric(carbon_guard_days) && isscalar(carbon_guard_days) && ...
        isfinite(carbon_guard_days) && carbon_guard_days >= 0)
    error('rolling_dispatch:bad_h2_reserve_gate', ...
        'h2_reserve_gate_carbon_guard_days must be nonnegative.');
end
joint = struct();
joint.contract_pacing_aggressiveness = pacing;
joint.hb_smoothing_reduction_fraction = smoothing;
joint.original_hb_ramp_rate = params.HB.ramp_rate;
joint.effective_hb_ramp_rate = params.HB.ramp_rate * (1 - smoothing);
joint.h2_reserve_gate_mode = gate_mode;
joint.h2_reserve_gate_backlog_fraction = backlog_fraction;
joint.h2_reserve_gate_carbon_guard_days = carbon_guard_days;
joint.summary = struct( ...
    'contract_pacing_aggressiveness', pacing, ...
    'hb_smoothing_reduction_fraction', smoothing, ...
    'original_hb_ramp_rate', joint.original_hb_ramp_rate, ...
    'effective_hb_ramp_rate', joint.effective_hb_ramp_rate, ...
    'h2_reserve_gate_mode', gate_mode, ...
    'h2_reserve_gate_backlog_fraction', backlog_fraction, ...
    'h2_reserve_gate_carbon_guard_days', carbon_guard_days);
end

function params = apply_joint_coordination_params(params, joint)
params.HB.ramp_rate = joint.effective_hb_ramp_rate;
end

function restoration = rolling_restoration_settings(config)
allow = option_value(config, 'allow_infeasible_continuation', false);
if ~(islogical(allow) && isscalar(allow))
    error('rolling_dispatch:bad_restoration', ...
        'allow_infeasible_continuation must be a scalar logical.');
end
penalty = option_value(config, ...
    'restoration_slack_penalty_usd_per_kg', 1e6);
if ~(isnumeric(penalty) && isscalar(penalty) && ...
        isfinite(penalty) && penalty >= 0)
    error('rolling_dispatch:bad_restoration', ...
        ['restoration_slack_penalty_usd_per_kg must be a finite ', ...
         'nonnegative scalar.']);
end
restoration = struct( ...
    'allow_infeasible_continuation', allow, ...
    'slack_penalty_usd_per_kg', penalty, ...
    'summary', struct( ...
        'allow_infeasible_continuation', allow, ...
        'slack_penalty_usd_per_kg', penalty, ...
        'method', "candidate_level_feasibility_restoration"));
end

function options = restoration_plan_options(options, restoration)
if ~restoration.allow_infeasible_continuation
    return
end
options.restoration = restoration_dispatch_options(restoration);
if isfield(options, 'contract')
    options.contract.enabled = false;
    options.contract.strict_delivery = false;
    options.contract.terminal_clear = false;
end
if isfield(options, 'carbon')
    options.carbon.commit_reserve_kg = 0;
end
end

function restoration_options = restoration_from_options(options)
restoration_options = struct('enabled', false, ...
    'slack_penalty_usd_per_kg', 1e6);
if isfield(options, 'restoration') && isstruct(options.restoration)
    restoration_options = options.restoration;
end
end

function restoration_options = restoration_dispatch_options(restoration)
restoration_options = struct( ...
    'enabled', true, ...
    'slack_penalty_usd_per_kg', ...
        restoration.slack_penalty_usd_per_kg);
end

function [effective_reserve, gate] = gated_h2_reserve_for_day( ...
        h2_reserve, joint, state, params, daily_contract_kg, ...
        subprotocol, remaining_after_commit_count)
effective_reserve = h2_reserve;
remaining_days_after_commit = ...
    remaining_after_commit_count * params.time.step / 24;
max_backlog_kg = subprotocol.Contract.MaxDelayDays * daily_contract_kg;
backlog_kg = sum(state.contract_cohorts_kg);
if max_backlog_kg > 0
    backlog_fraction = backlog_kg / max_backlog_kg;
else
    backlog_fraction = 0;
end
carbon_debt_kg = state.co2_emitted_kg ...
    - params.environment.co2_limit * state.nh3_produced_kg;
remaining_reference_kg = remaining_contract_reference_nh3_kg( ...
    params, daily_contract_kg, remaining_after_commit_count);
carbon_margin_kg = params.environment.co2_limit ...
    * remaining_reference_kg - carbon_debt_kg;
carbon_guard_kg = h2_gate_carbon_guard_kg( ...
    params, daily_contract_kg, joint);
gate = struct( ...
    'mode', joint.h2_reserve_gate_mode, ...
    'open', true, ...
    'reason', "open", ...
    'backlog_kg', backlog_kg, ...
    'backlog_fraction', backlog_fraction, ...
    'carbon_margin_kg', carbon_margin_kg, ...
    'carbon_guard_kg', carbon_guard_kg, ...
    'remaining_days_after_commit', remaining_days_after_commit);
if ~h2_reserve.active
    gate.open = false;
    gate.reason = "inactive_reserve";
    return
end
if joint.h2_reserve_gate_mode == "off"
    gate.reason = "gate_off";
    return
end
recovery_window_days = subprotocol.RollingDispatch.PlanningHours / 24 ...
    + subprotocol.Contract.MaxDelayDays;
if remaining_days_after_commit <= recovery_window_days
    gate.open = false;
    gate.reason = "year_end_h2_recovery_priority";
elseif backlog_fraction >= joint.h2_reserve_gate_backlog_fraction
    gate.open = false;
    gate.reason = "contract_backlog_priority";
elseif carbon_margin_kg < carbon_guard_kg
    gate.open = false;
    gate.reason = "carbon_reachability_priority";
end
if ~gate.open
    effective_reserve.target_scale = 0;
    effective_reserve.summary.target_scale = 0;
end
end

function guard_kg = h2_gate_carbon_guard_kg( ...
        params, daily_contract_kg, joint)
if joint.h2_reserve_gate_carbon_guard_days == 0
    guard_kg = 0;
    return
end
daily_h2_kg = daily_contract_kg * params.HB.lit_h2;
daily_ael_kwh = daily_h2_kg * params.AEL.common.spec_energy ...
    / params.unit.h2_density;
daily_hb_kwh = params.HB.nom_power * 1000 * 24;
daily_grid_emissions_kg = (daily_ael_kwh + daily_hb_kwh) ...
    * params.environment.grid_co2;
guard_kg = daily_grid_emissions_kg ...
    * joint.h2_reserve_gate_carbon_guard_days;
end

function output_path = rolling_output_path( ...
        output_dir, scheme, data_year, h2_reserve, joint)
tag = sprintf('v51_%s', char(scheme));
if h2_reserve.active
    tag = sprintf('%s_h2q%03d_l%d', ...
        tag, round(100 * h2_reserve.quantile), ...
        h2_reserve.lookahead_days);
    if h2_reserve.soft
        tag = sprintf('%s_soft', tag);
    end
end
if joint.contract_pacing_aggressiveness > 0
    tag = sprintf('%s_cp%03d', tag, ...
        round(100 * joint.contract_pacing_aggressiveness));
end
if joint.hb_smoothing_reduction_fraction > 0
    tag = sprintf('%s_hb%03d', tag, ...
        round(100 * joint.hb_smoothing_reduction_fraction));
end
if joint.h2_reserve_gate_mode ~= "off"
    tag = sprintf('%s_gate', tag);
end
output_path = fullfile(output_dir, ...
    sprintf('%s_%d_latest.mat', tag, data_year));
end

function source = prepare_forecast_source( ...
        renewable_data, config, forecast_mode, subprotocol, data_year)
source = struct('mode', forecast_mode);
if forecast_mode == "observed_oracle"
    if ~ismember(data_year, subprotocol.DataSplit.DevelopmentYears)
        error('rolling_dispatch:oracle_holdout_forbidden', ...
            'observed_oracle is restricted to frozen development years.');
    end
    source.fallback_source = ...
        "observed_development_oracle_not_forecast_claim";
    return
end
if forecast_mode == "simulated_persistence"
    if isfield(config, 'forecast_fallback')
        fallback = validate_development_fallback( ...
            config.forecast_fallback, subprotocol);
        source.pv_fallback = fallback.pv_power_kw(:);
        source.pw_fallback = fallback.pw_power_kw(:);
        source.fallback_source = ...
            "external_development_years_2022_2023";
        return
    end
    if ~ismember(data_year, subprotocol.DataSplit.DevelopmentYears)
        error('rolling_dispatch:missing_development_fallback', ...
            ['Target-year simulated forecasts require forecast_fallback ', ...
             'derived only from the frozen 2022/2023 development years.']);
    end
    samples_per_day = 24 / renewable_data_time_step(renewable_data);
    day_count = renewable_data.time_count / samples_per_day;
    source.pv_fallback = median(reshape( ...
        renewable_data.pv_power_kw, samples_per_day, day_count), 2);
    source.pw_fallback = median(reshape( ...
        renewable_data.pw_power_kw, samples_per_day, day_count), 2);
    source.fallback_source = "current_development_year_hour_median";
    return
end

forecast_table = option_value(config, 'forecast_table', table());
if ~istable(forecast_table)
    error('rolling_dispatch:bad_forecast_table', ...
        'forecast_table must be a MATLAB table.');
end
required = cellstr(subprotocol.Forecast.RealForecastInterface.RequiredFields);
missing = setdiff(required, forecast_table.Properties.VariableNames);
if ~isempty(missing)
    error('rolling_dispatch:bad_forecast_table', ...
        'forecast_table is missing: %s.', strjoin(missing, ', '));
end
source.table = forecast_table;
source.fallback_source = "not_applicable";
end

function fallback = validate_development_fallback(fallback, subprotocol)
required = {'source_years', 'pv_power_kw', 'pw_power_kw'};
for field_index = 1:numel(required)
    field_name = required{field_index};
    if ~isfield(fallback, field_name)
        error('rolling_dispatch:bad_forecast_fallback', ...
            'forecast_fallback must contain %s.', field_name);
    end
end
source_years = sort(double(fallback.source_years(:)));
development_years = sort(double( ...
    subprotocol.DataSplit.DevelopmentYears(:)));
if ~isequal(source_years, development_years)
    error('rolling_dispatch:bad_forecast_fallback', ...
        'forecast_fallback.source_years must be exactly 2022 and 2023.');
end
validate_fallback_profile(fallback.pv_power_kw, 'pv_power_kw');
validate_fallback_profile(fallback.pw_power_kw, 'pw_power_kw');
end

function validate_fallback_profile(profile, field_name)
if ~isnumeric(profile) || numel(profile) ~= 24 || ...
        any(~isfinite(profile(:))) || any(profile(:) < 0)
    error('rolling_dispatch:bad_forecast_fallback', ...
        'forecast_fallback.%s must contain 24 finite nonnegative values.', ...
        field_name);
end
end

function forecast = forecast_window( ...
        source, observed, day_index, hour_count)
if source.mode == "observed_oracle"
    first_hour = (day_index - 1) * 24 + 1;
    indices = first_hour:first_hour + hour_count - 1;
    forecast = struct( ...
        'time_count', hour_count, ...
        'pv_power_kw', observed.pv_power_kw(indices), ...
        'pw_power_kw', observed.pw_power_kw(indices));
    return
end
if source.mode == "simulated_persistence"
    if day_index == 1
        pv_profile = source.pv_fallback;
        pw_profile = source.pw_fallback;
    else
        previous = (day_index - 2) * 24 + (1:24);
        pv_profile = observed.pv_power_kw(previous);
        pw_profile = observed.pw_power_kw(previous);
    end
    repeat_count = ceil(hour_count / 24);
    forecast = struct();
    forecast.time_count = hour_count;
    forecast.pv_power_kw = repmat(pv_profile(:), repeat_count, 1);
    forecast.pw_power_kw = repmat(pw_profile(:), repeat_count, 1);
    forecast.pv_power_kw = forecast.pv_power_kw(1:hour_count);
    forecast.pw_power_kw = forecast.pw_power_kw(1:hour_count);
    return
end

if ~isfield(observed, 'time') || ~isdatetime(observed.time)
    error('rolling_dispatch:forecast_time_required', ...
        'Table forecasts require datetime values in renewable_data.time.');
end
issue_time = observed.time((day_index - 1) * 24 + 1);
rows = source.table.issue_time_utc == issue_time;
current = sortrows(source.table(rows, :), 'horizon_hour');
required_horizons = (1:hour_count)';
if height(current) ~= hour_count || ...
        any(current.horizon_hour(:) ~= required_horizons)
    error('rolling_dispatch:forecast_horizon_missing', ...
        'Forecast issued at %s must contain horizons 1:%d.', ...
        string(issue_time), hour_count);
end
forecast = struct( ...
    'time_count', hour_count, ...
    'pv_power_kw', current.pv_power_kw(:), ...
    'pw_power_kw', current.pw_power_kw(:));
end

function options = planning_options(state, subprotocol, ...
        daily_contract_kg, contract_enabled, final_window, ...
        annual_initial_h2, params, remaining_time_count, ...
        carbon_reserve_kg, horizon_time_count, forecast_data, ...
        h2_reserve, contract_pacing_aggressiveness)
commit_steps = round(24 / params.time.step);
remaining_after_commit_count = ...
    remaining_time_count + horizon_time_count - commit_steps;
h2_commit_min_kg = contract_h2_commit_min_kg( ...
    contract_enabled, params, annual_initial_h2, subprotocol, ...
    remaining_after_commit_count);
[hydrogen, h2_reserve_plan] = hydrogen_reserve_options( ...
    state, forecast_data, params, daily_contract_kg, ...
    contract_enabled, h2_reserve, commit_steps, ...
    h2_commit_min_kg);
if final_window
    terminal = struct('h2_equal_kg', annual_initial_h2, ...
        'h2_min_kg', [], ...
        'commit_steps', commit_steps, ...
        'h2_commit_min_kg', h2_commit_min_kg);
else
    handoff_h2_kg = h2_handoff_inventory_kg(params);
    if h2_reserve.active
        terminal_h2_min_kg = max([state.h2_kg, ...
            handoff_h2_kg, h2_reserve_plan.target_min_kg]);
    else
        terminal_h2_min_kg = max(state.h2_kg, handoff_h2_kg);
    end
    terminal = struct('h2_equal_kg', [], ...
        'h2_min_kg', terminal_h2_min_kg, ...
        'commit_steps', commit_steps, ...
        'h2_commit_min_kg', h2_commit_min_kg);
end
options = struct( ...
    'mode', "day_ahead", ...
    'include_annual_fixed_cost', false, ...
    'initial_state', state_without_contract(state), ...
    'terminal', terminal, ...
    'carbon', rolling_carbon_options( ...
        state, params, daily_contract_kg, contract_enabled, ...
        remaining_time_count, carbon_reserve_kg, ...
        commit_steps, ...
        horizon_time_count), ...
    'grid_budget', rolling_grid_options(state, params), ...
    'hydrogen', hydrogen, ...
    'h2_reserve', h2_reserve_plan, ...
    'production', contract_production_options( ...
        state, params, daily_contract_kg, contract_enabled, ...
        commit_steps, remaining_after_commit_count, ...
        contract_pacing_aggressiveness), ...
    'contract', struct( ...
        'enabled', contract_enabled, ...
        'strict_delivery', true, ...
        'terminal_clear', final_window, ...
        'max_delay_days', subprotocol.Contract.MaxDelayDays, ...
        'fixed_daily_quantity_kg', daily_contract_kg, ...
        'initial_cohorts_kg', state.contract_cohorts_kg, ...
        'lcoa_cap_usd_per_t', []));
end

function options = recourse_options_for_day( ...
        state, plan_sol, commit_count, final_day, annual_initial_h2, ...
        params, daily_contract_kg, contract_enabled, subprotocol, ...
        applied_plan_reserve_kg, remaining_time_count, ...
        committed_h2_floor_kg, h2_reserve_soft, ...
        h2_reserve_soft_penalty_usd_per_kg, ...
        contract_pacing_aggressiveness, restoration)
h2_commit_min_kg = contract_h2_commit_min_kg( ...
    contract_enabled, params, annual_initial_h2, subprotocol, ...
    remaining_time_count);
if final_day
    terminal = struct('h2_equal_kg', annual_initial_h2, ...
        'h2_min_kg', [], ...
        'commit_steps', commit_count, ...
        'h2_commit_min_kg', h2_commit_min_kg);
else
    terminal = struct('h2_equal_kg', [], ...
        'h2_min_kg', h2_handoff_inventory_kg(params), ...
        'commit_steps', commit_count, ...
        'h2_commit_min_kg', h2_commit_min_kg);
end
remaining_reference_nh3_kg = remaining_contract_reference_nh3_kg( ...
    params, daily_contract_kg, remaining_time_count);
planned_nh3_kg = sum(plan_sol.HB_load(1:commit_count)) ...
    * params.HB.nh3_output * params.time.step;
planned_emissions_kg = params.environment.grid_co2 ...
    * sum(plan_sol.p_purchase(1:commit_count)) * params.time.step;
if contract_enabled
    planned_carbon_debt_kg = ...
        state.co2_emitted_kg + planned_emissions_kg ...
        - params.environment.co2_limit ...
        * (state.nh3_produced_kg + planned_nh3_kg);
    state_consistency_reserve_kg = max(0, ...
        params.environment.co2_limit * remaining_reference_nh3_kg ...
        - planned_carbon_debt_kg);
else
    base_carbon = rolling_carbon_options( ...
        state, params, daily_contract_kg, false, ...
        remaining_time_count, 0, commit_count, commit_count);
    available_emissions_budget_kg = ...
        available_absolute_carbon_budget(base_carbon, commit_count);
    state_consistency_reserve_kg = max(0, ...
        available_emissions_budget_kg ...
        - state.co2_emitted_kg - planned_emissions_kg);
end
state_consistency_reserve_kg = min(state_consistency_reserve_kg, ...
    applied_plan_reserve_kg);
options = struct( ...
    'mode', "realtime", ...
    'include_annual_fixed_cost', false, ...
    'initial_state', state_without_contract(state), ...
    'terminal', terminal, ...
    'carbon', rolling_carbon_options( ...
        state, params, daily_contract_kg, contract_enabled, ...
        remaining_time_count, state_consistency_reserve_kg, ...
        commit_count, commit_count), ...
    'grid_budget', rolling_grid_options(state, params), ...
    'hydrogen', struct( ...
        'min_storage_kg_by_step', committed_h2_floor_kg(:), ...
        'reserve_floor_soft', h2_reserve_soft, ...
        'reserve_slack_penalty_usd_per_kg', ...
            h2_reserve_soft_penalty_usd_per_kg), ...
    'production', contract_production_options( ...
        state, params, daily_contract_kg, contract_enabled, ...
        commit_count, remaining_time_count, ...
        contract_pacing_aggressiveness), ...
    'fixed_plan', struct( ...
        'HB_load', plan_sol.HB_load(1:commit_count), ...
        'AEL_commitment', plan_sol.n_ael(1:commit_count)), ...
    'contract', struct('enabled', false), ...
    'restoration', restoration);
end

function production = contract_production_options( ...
        state, params, daily_contract_kg, contract_enabled, ...
        commit_steps, remaining_after_commit_count, ...
        contract_pacing_aggressiveness)
production = struct( ...
    'commit_steps', 0, ...
    'commit_min_nh3_kg', 0, ...
    'method', "disabled", ...
    'pacing_aggressiveness', contract_pacing_aggressiveness, ...
    'due_at_commit_kg', 0, ...
    'allowable_backlog_after_commit_kg', Inf, ...
    'remaining_days_after_commit', ...
        remaining_after_commit_count * params.time.step / 24);
if ~contract_enabled
    return
end
daily_capacity_kg = params.HB.max_load * params.HB.nh3_output * 24;
daily_surplus_capacity_kg = max(0, daily_capacity_kg - daily_contract_kg);
allowable_backlog_kg = production.remaining_days_after_commit ...
    * daily_surplus_capacity_kg;
allowable_backlog_kg = allowable_backlog_kg ...
    * (1 - contract_pacing_aggressiveness);
due_at_commit_kg = sum(state.contract_cohorts_kg) + daily_contract_kg;
production.commit_steps = commit_steps;
production.commit_min_nh3_kg = max( ...
    0, due_at_commit_kg - allowable_backlog_kg);
production.method = ...
    "year_end_terminal_clearance_reachability_commit_floor";
production.due_at_commit_kg = due_at_commit_kg;
production.allowable_backlog_after_commit_kg = allowable_backlog_kg;
end

function h2_min_kg = contract_h2_commit_min_kg( ...
        contract_enabled, params, annual_initial_h2, subprotocol, ...
        remaining_after_commit_count)
if ~contract_enabled
    h2_min_kg = [];
    return
end
h2_handoff_kg = h2_handoff_inventory_kg(params);
planning_days = subprotocol.RollingDispatch.PlanningHours / 24;
recovery_days = subprotocol.Contract.MaxDelayDays;
remaining_days = remaining_after_commit_count * params.time.step / 24;
if remaining_days <= planning_days
    h2_min_kg = annual_initial_h2;
else
    recovery_fraction = max(0, ...
        1 - (remaining_days - planning_days) / recovery_days);
    h2_min_kg = h2_handoff_kg + recovery_fraction ...
        * (annual_initial_h2 - h2_handoff_kg);
end
h2_min_kg = min(annual_initial_h2, max(h2_handoff_kg, h2_min_kg));
end

function initial = state_without_contract(state)
initial = struct( ...
    'h2_kg', state.h2_kg, ...
    'ael_online_modules', state.ael_online_modules, ...
    'hb_load', state.hb_load);
end

function state = initial_rolling_state(annual_initial_h2_kg, subprotocol)
state = struct( ...
    'h2_kg', annual_initial_h2_kg, ...
    'ael_online_modules', 0, ...
    'hb_load', [], ...
    'co2_emitted_kg', 0, ...
    'nh3_produced_kg', 0, ...
    'sell_kwh', 0, ...
    'curtail_kwh', 0, ...
    'renewable_kwh', 0, ...
    'contract_cohorts_kg', ...
        zeros(subprotocol.Contract.MaxDelayDays, 1));
end

function value = scalar_or_nan(value)
if isempty(value)
    value = NaN;
end
end

function value = clean_nonnegative_state_value(value, name)
if ~(isnumeric(value) && isscalar(value) && isfinite(value))
    error('rolling_dispatch:bad_state_value', ...
        'State value %s must be finite.', name);
end
tolerance = 1e-6;
if value < -tolerance
    error('rolling_dispatch:negative_state_value', ...
        'State value %s is negative by %.6g.', name, value);
end
value = max(value, 0);
end

function carbon = rolling_carbon_options( ...
        state, params, daily_contract_kg, contract_enabled, ...
        remaining_time_count, commit_reserve_kg, commit_steps, ...
        horizon_time_count)
if ~contract_enabled
    annual_nh3_target_kg = daily_contract_kg * 365;
    total_hours = params.time.hour_year * params.time.step;
    production_grace_hours = 7 * 24;
    production_schedule_hours = total_hours - production_grace_hours;
    elapsed_horizon_end_hours = ...
        (params.time.hour_year - remaining_time_count) ...
        * params.time.step;
    elapsed_commit_end_hours = elapsed_horizon_end_hours ...
        - (horizon_time_count - commit_steps) * params.time.step;
    [annual_budget_kg, available_at_start_kg, accrual_per_step_kg] = ...
        absolute_carbon_budget_schedule(params, daily_contract_kg, ...
        remaining_time_count, horizon_time_count);
    carbon = struct( ...
        'accounting', "annual_cumulative_absolute_budget", ...
        'initial_emissions_kg', state.co2_emitted_kg, ...
        'initial_nh3_kg', state.nh3_produced_kg, ...
        'remaining_reference_nh3_kg', 0, ...
        'reference_nh3_per_step_kg', 0, ...
        'checkpoint_interval_steps', round(24 / params.time.step), ...
        'commit_reserve_kg', commit_reserve_kg, ...
        'commit_steps', commit_steps, ...
        'annual_emissions_budget_kg', annual_budget_kg, ...
        'annual_nh3_target_kg', annual_nh3_target_kg, ...
        'production_target_at_commit_kg', annual_nh3_target_kg ...
            * max(0, elapsed_commit_end_hours ...
            - production_grace_hours) / production_schedule_hours, ...
        'budget_available_at_start_kg', available_at_start_kg, ...
        'budget_accrual_per_step_kg', accrual_per_step_kg, ...
        'is_year_end', remaining_time_count == 0);
    return
end
carbon = struct( ...
    'accounting', "annual_cumulative_reachability", ...
    'initial_emissions_kg', state.co2_emitted_kg, ...
    'initial_nh3_kg', state.nh3_produced_kg, ...
    'remaining_reference_nh3_kg', remaining_contract_reference_nh3_kg( ...
        params, daily_contract_kg, remaining_time_count), ...
    'reference_nh3_per_step_kg', ...
        daily_contract_kg * params.time.step / 24, ...
    'checkpoint_interval_steps', round(24 / params.time.step), ...
    'commit_reserve_kg', commit_reserve_kg, ...
    'commit_steps', commit_steps);
end

function budget = rolling_grid_options(state, params)
budget = struct( ...
    'accounting', "annual_cumulative_observed_budget", ...
    'initial_sell_kwh', state.sell_kwh, ...
    'initial_curtail_kwh', state.curtail_kwh, ...
    'initial_renewable_kwh', state.renewable_kwh, ...
    'remaining_max_renewable_kwh', 0, ...
    'max_renewable_per_step_kwh', 0, ...
        'checkpoint_interval_steps', round(24 / params.time.step));
end

function [hydrogen, reserve] = hydrogen_reserve_options( ...
        state, forecast_data, params, daily_contract_kg, ...
        contract_enabled, h2_reserve, commit_steps, h2_commit_min_kg)
storage_limits = h2_storage_limits( ...
    params.h2_storage, params.unit.h2_density);
time_count = forecast_data.time_count;
base_floor_kg = storage_limits.min_mass * ones(time_count, 1);
base_target_kg = scalar_or_value( ...
    h2_commit_min_kg, h2_handoff_inventory_kg(params));
raw_deficit_quantile_kg = 0;
deficit_quantile_kg = 0;
reserve_target_kg = storage_limits.min_mass;
lookahead_steps = 0;
surplus_charge_cap_kg = 0;
active_commit_steps = min(commit_steps, time_count);
if contract_enabled && h2_reserve.active
    lookahead_steps = min(time_count, ...
        h2_reserve.lookahead_days * round(24 / params.time.step));
    raw_deficit_quantile_kg = forecast_h2_deficit_quantile_kg( ...
        forecast_data, params, daily_contract_kg, ...
        lookahead_steps, h2_reserve.quantile);
    deficit_quantile_kg = h2_reserve.target_scale ...
        * raw_deficit_quantile_kg;
    reserve_target_kg = storage_limits.min_mass ...
        + min(storage_limits.work_mass, deficit_quantile_kg);
    surplus_charge_cap_kg = forecast_renewable_surplus_h2_kg( ...
        forecast_data, params, daily_contract_kg, commit_steps);
    commit_contract_h2_use_kg = daily_contract_kg ...
        * params.HB.lit_h2 * active_commit_steps ...
        * params.time.step / 24;
    reserve_target_kg = min(reserve_target_kg, ...
        state.h2_kg - commit_contract_h2_use_kg ...
        + surplus_charge_cap_kg);
    reserve_target_kg = max(storage_limits.min_mass, ...
        reserve_target_kg);
end
target_kg = min(storage_limits.max_mass, ...
    max(base_target_kg, reserve_target_kg));
if active_commit_steps > 0
    base_floor_kg(1:active_commit_steps) = reserve_floor_trajectory( ...
        state.h2_kg, target_kg, active_commit_steps, ...
        storage_limits);
end
hydrogen = struct( ...
    'min_storage_kg_by_step', base_floor_kg, ...
    'reserve_floor_soft', h2_reserve.soft, ...
    'reserve_slack_penalty_usd_per_kg', ...
        h2_reserve.soft_penalty_usd_per_kg);
reserve = struct( ...
    'active', h2_reserve.active, ...
    'method', h2_reserve.method, ...
    'quantile', h2_reserve.quantile, ...
    'lookahead_days', h2_reserve.lookahead_days, ...
    'applied_scale', h2_reserve.target_scale, ...
    'soft', h2_reserve.soft, ...
    'soft_penalty_usd_per_kg', ...
        h2_reserve.soft_penalty_usd_per_kg, ...
    'lookahead_steps', lookahead_steps, ...
    'raw_deficit_quantile_kg', raw_deficit_quantile_kg, ...
    'deficit_quantile_kg', deficit_quantile_kg, ...
    'surplus_charge_cap_kg', surplus_charge_cap_kg, ...
    'renewable_capped', reserve_target_kg < storage_limits.min_mass ...
        + min(storage_limits.work_mass, deficit_quantile_kg) ...
        - 1e-9, ...
    'target_min_kg', target_kg, ...
    'target_work_soc', ...
        (target_kg - storage_limits.min_mass) ...
        / storage_limits.work_mass);
end

function value = scalar_or_value(value, default_value)
if isempty(value)
    value = default_value;
end
end

function floor_kg = reserve_floor_trajectory( ...
        initial_kg, target_kg, step_count, storage_limits)
if target_kg > initial_kg
    floor_kg = initial_kg + (target_kg - initial_kg) ...
        * (1:step_count)' / step_count;
else
    floor_kg = target_kg * ones(step_count, 1);
end
floor_kg = min(storage_limits.max_mass, ...
    max(storage_limits.min_mass, floor_kg));
end

function deficit_quantile_kg = forecast_h2_deficit_quantile_kg( ...
        forecast_data, params, daily_contract_kg, ...
        lookahead_steps, quantile)
if lookahead_steps <= 0
    deficit_quantile_kg = 0;
    return
end
dt = params.time.step;
contract_hb_load = daily_contract_kg ...
    / (24 * params.HB.nh3_output);
contract_hb_load = min(params.HB.max_load, ...
    max(params.HB.min_load, contract_hb_load));
contract_h2_use_kg = contract_hb_load ...
    * params.HB.nh3_output * params.HB.lit_h2 * dt;
contract_hb_power_kw = contract_hb_load ...
    * params.HB.nom_power * 1000;
renewable_kw = (forecast_data.pv_power_kw(1:lookahead_steps) ...
    + forecast_data.pw_power_kw(1:lookahead_steps)) ...
    * params.renewable.input_scale;
available_ael_kw = min(params.AEL.common.max_power, ...
    max(renewable_kw - contract_hb_power_kw, 0));
h2_from_forecast_kg = available_ael_kw * dt ...
    / params.AEL.common.spec_energy * params.unit.h2_density;
cumulative_deficit_kg = cumsum( ...
    contract_h2_use_kg - h2_from_forecast_kg);
cumulative_deficit_kg = max(cumulative_deficit_kg, 0);
deficit_quantile_kg = prctile( ...
    cumulative_deficit_kg, 100 * quantile);
end

function surplus_h2_kg = forecast_renewable_surplus_h2_kg( ...
        forecast_data, params, daily_contract_kg, commit_steps)
if commit_steps <= 0
    surplus_h2_kg = 0;
    return
end
steps = min(commit_steps, forecast_data.time_count);
dt = params.time.step;
contract_hb_load = daily_contract_kg ...
    / (24 * params.HB.nh3_output);
contract_hb_load = min(params.HB.max_load, ...
    max(params.HB.min_load, contract_hb_load));
contract_hb_power_kw = contract_hb_load ...
    * params.HB.nom_power * 1000;
renewable_kw = (forecast_data.pv_power_kw(1:steps) ...
    + forecast_data.pw_power_kw(1:steps)) ...
    * params.renewable.input_scale;
available_ael_kw = min(params.AEL.common.max_power, ...
    max(renewable_kw - contract_hb_power_kw, 0));
surplus_h2_kg = sum(available_ael_kw) * dt ...
    / params.AEL.common.spec_energy * params.unit.h2_density;
end

function [sol, fval, exitflag, output, elapsed, succeeded] = ...
        solve_dispatch(problem, config, label, allow_failure)
if nargin < 4
    allow_failure = false;
end
solver_options = optimoptions('intlinprog', ...
    'Display', option_value(config, 'solver_display', 'none'), ...
    'ConstraintTolerance', 1e-5, ...
    'RelativeGapTolerance', option_value( ...
        config, 'relative_gap_tolerance', 1e-3));
max_time = option_value(config, 'max_time_seconds_per_solve', 180);
solver_options.MaxTime = max_time;
timer = tic;
[sol, fval, exitflag, output] = solve(problem, ...
    'Solver', 'intlinprog', 'Options', solver_options);
elapsed = toc(timer);
has_solution = isstruct(sol) && isfield(sol, 'P_AEL') && ...
    ~isempty(sol.P_AEL);
succeeded = has_solution && exitflag == 1 && ...
    output.constrviolation <= solver_options.ConstraintTolerance;
if ~succeeded && ~allow_failure
    error('rolling_dispatch:solve_failed', ...
        ['%s solve failed or did not converge. Exitflag: %d. ', ...
        'Message: %s'], label, exitflag, output.message);
end
end

function [sol, fval, exitflag, output, elapsed, succeeded, ...
        projected_options, applied_scale, projected_carbon_reserve_kg, ...
        projected_h2_carbon_guard_kg] = project_h2_reserve_plan( ...
        config, state, subprotocol, daily_contract_kg, ...
        contract_enabled, final_window, annual_initial_h2, params, ...
        remaining_time_count, base_carbon_reserve_kg, horizon_time_count, ...
        forecast_data, h2_reserve, contract_pacing_aggressiveness, ...
        elapsed)
projection_scales = [0.75, 0.50, 0.25, 0];
sol = struct();
fval = NaN;
exitflag = NaN;
output = struct('message', 'H2 reserve projection was not attempted.');
succeeded = false;
projected_h2_carbon_guard_kg = h2_reserve_carbon_guard_kg( ...
    params, daily_contract_kg, h2_reserve, subprotocol);
projected_carbon_reserve_kg = max( ...
    base_carbon_reserve_kg, projected_h2_carbon_guard_kg);
projected_options = planning_options(state, subprotocol, ...
    daily_contract_kg, contract_enabled, final_window, ...
    annual_initial_h2, params, remaining_time_count, ...
    projected_carbon_reserve_kg, horizon_time_count, ...
    forecast_data, h2_reserve, contract_pacing_aggressiveness);
applied_scale = h2_reserve.target_scale;
for scale_index = 1:numel(projection_scales)
    trial_reserve = h2_reserve;
    trial_reserve.target_scale = ...
        min(h2_reserve.target_scale, projection_scales(scale_index));
    trial_h2_carbon_guard_kg = h2_reserve_carbon_guard_kg( ...
        params, daily_contract_kg, trial_reserve, subprotocol);
    trial_carbon_reserve_kg = max( ...
        base_carbon_reserve_kg, trial_h2_carbon_guard_kg);
    trial_options = planning_options(state, subprotocol, ...
        daily_contract_kg, contract_enabled, final_window, ...
        annual_initial_h2, params, remaining_time_count, ...
        trial_carbon_reserve_kg, horizon_time_count, forecast_data, ...
        trial_reserve, contract_pacing_aggressiveness);
    trial_model = dispatch_model(params, forecast_data, trial_options);
    [trial_sol, trial_fval, trial_exitflag, trial_output, ...
        trial_elapsed, trial_succeeded] = solve_dispatch( ...
        trial_model.problem, config, ...
        sprintf('day_ahead_h2_projection_%.2f', ...
        trial_reserve.target_scale), true);
    elapsed = elapsed + trial_elapsed;
    sol = trial_sol;
    fval = trial_fval;
    exitflag = trial_exitflag;
    output = trial_output;
    projected_options = trial_options;
    applied_scale = trial_reserve.target_scale;
    projected_carbon_reserve_kg = trial_carbon_reserve_kg;
    projected_h2_carbon_guard_kg = trial_h2_carbon_guard_kg;
    if trial_succeeded
        succeeded = true;
        return
    end
end
end

function solution = empty_solution(hour_count, initial_h2)
fields = {'P_AEL', 'HB_load', 'p_purchase', 'p_sell', 'p_curt', ...
    'u_purchase', 'n_ael', 'SU_AEL', 'SD_AEL', 'I_AEL_up', ...
    'P_AEL_start'};
solution = struct();
for field_index = 1:numel(fields)
    solution.(fields{field_index}) = zeros(hour_count, 1);
end
solution.storage_H2 = zeros(hour_count + 1, 1);
solution.storage_H2(1) = initial_h2;
end

function plan = empty_plan(hour_count)
plan = struct( ...
    'HB_load', zeros(hour_count, 1), ...
    'P_AEL', zeros(hour_count, 1), ...
    'n_ael', zeros(hour_count, 1), ...
    'pv_power_kw', zeros(hour_count, 1), ...
    'pw_power_kw', zeros(hour_count, 1));
end

function plan = assign_plan(plan, indices, sol, forecast, count)
plan.HB_load(indices) = sol.HB_load(1:count);
plan.P_AEL(indices) = sol.P_AEL(1:count);
plan.n_ael(indices) = sol.n_ael(1:count);
plan.pv_power_kw(indices) = forecast.pv_power_kw(1:count);
plan.pw_power_kw(indices) = forecast.pw_power_kw(1:count);
end

function aggregate = assign_solution(aggregate, indices, sol)
fields = {'P_AEL', 'HB_load', 'p_purchase', 'p_sell', 'p_curt', ...
    'u_purchase', 'n_ael', 'SU_AEL', 'SD_AEL', 'I_AEL_up', ...
    'P_AEL_start'};
for field_index = 1:numel(fields)
    name = fields{field_index};
    aggregate.(name)(indices) = sol.(name);
end
aggregate.storage_H2(indices + 1) = sol.storage_H2(2:end);
end

function sliced = renewable_slice(source, indices)
sliced = struct( ...
    'time_count', numel(indices), ...
    'pv_power_kw', source.pv_power_kw(indices), ...
    'pw_power_kw', source.pw_power_kw(indices));
if isfield(source, 'time')
    sliced.time = source.time(indices);
end
end

function [next_cohorts, expired_kg] = update_contract_cohorts( ...
        cohorts, daily_contract_kg, daily_nh3_kg)
remaining = cohorts(:);
available_kg = daily_nh3_kg;
for age = numel(remaining):-1:1
    delivered_kg = min(remaining(age), available_kg);
    remaining(age) = remaining(age) - delivered_kg;
    available_kg = available_kg - delivered_kg;
end
current_remaining = max(0, daily_contract_kg - available_kg);
expired_kg = remaining(end);
next_cohorts = [current_remaining; remaining(1:end - 1)];
next_cohorts(next_cohorts < 1e-6) = 0;
end

function metrics = calculate_metrics( ...
        result, params, renewable_data, plan, subprotocol, ...
        daily_contract_kg, contract_enabled)
daily_nh3_kg = sum(reshape(result.dispatch.NH3_prod, 24, []), 1)';
contract = contract_metrics(daily_nh3_kg, daily_contract_kg, ...
    subprotocol.Contract.MaxDelayDays);
forecast_total = (plan.pv_power_kw + plan.pw_power_kw) ...
    * subprotocol.Forecast.RealForecastInterface.RequiredResolutionHours;
observed_total = renewable_data.pv_power_kw(:) + ...
    renewable_data.pw_power_kw(:);
forecast_error = forecast_total - observed_total;
carbon_emissions_kg = params.environment.grid_co2 ...
    * result.summary.purchase_kwh;
carbon_debt_kg = carbon_emissions_kg ...
    - params.environment.co2_limit * result.summary.NH3_prod_kg;
carbon_tolerance_kg = annual_carbon_tolerance_kg( ...
    result.summary.NH3_prod_kg, params);

metrics = struct();
metrics.ProtocolVersion = subprotocol.ProtocolVersion;
metrics.ProtocolSeal = subprotocol.Seal;
metrics.Contract = contract;
metrics.Contract.applicable = contract_enabled;
metrics.Primary = struct( ...
    'contract_shortfall_p95', prctile(contract.backlog_kg, 95), ...
    'mar', mean(abs(diff(result.dispatch.HB_load))), ...
    'h2_soc_p05', prctile(result.storage.soc_work, 5), ...
    'nh3_output_t', result.summary.NH3_prod_kg / 1000, ...
    'annual_output_target_t', daily_contract_kg * 365 / 1000);
metrics.Economic = struct( ...
    'lcoa', result.summary.lcoa, ...
    'net_profit_usd', result.summary.net_profit);
metrics.Forecast = struct( ...
    'mae_kw', mean(abs(forecast_error)), ...
    'rmse_kw', sqrt(mean(forecast_error .^ 2)), ...
    'bias_kw', mean(forecast_error));
metrics.Carbon = struct( ...
    'accounting', string(result.carbon.accounting), ...
    'emissions_kg', carbon_emissions_kg, ...
    'nh3_kg', result.summary.NH3_prod_kg, ...
    'debt_kg', carbon_debt_kg, ...
    'intensity_kg_per_kg_nh3', result.summary.co2_intensity, ...
    'limit_kg_per_kg_nh3', params.environment.co2_limit, ...
    'tolerance_kg', carbon_tolerance_kg);
metrics.GridBudget = grid_state_summary_from_result(result, params);
metrics.Feasibility = struct( ...
    'contract_applicable', contract_enabled, ...
    'strict_delivery_ok', ~contract_enabled || ...
        (contract.late_cohort_count == 0 && ...
        contract.unserved_cohort_count == 0), ...
    'terminal_contract_ok', ~contract_enabled || ...
        contract.terminal_backlog_kg <= 1e-3, ...
    'annual_output_ok', result.summary.NH3_prod_kg >= ...
        daily_contract_kg * 365 - 1e-3, ...
    'terminal_h2_ok', abs(result.storage.H2(end) - ...
        result.storage.H2(1)) <= 1e-3, ...
    'power_balance_ok', result.check.max_power_residual_kw <= 1e-5, ...
    'storage_balance_ok', result.check.max_storage_residual_kg <= 1e-5, ...
    'annual_co2_ok', ~params.environment.co2_enabled || ...
        carbon_debt_kg <= carbon_tolerance_kg, ...
    'annual_sell_ok', metrics.GridBudget.sell_debt_kwh <= ...
        metrics.GridBudget.tolerance_kwh, ...
    'annual_curtail_ok', metrics.GridBudget.curtail_debt_kwh <= ...
        metrics.GridBudget.tolerance_kwh, ...
    'lcoa_cap_ok', result.summary.lcoa <= ...
        subprotocol.ContractFeasibilityCertificate.LCOAUSDPerT / ...
        (1 + subprotocol.ContractFeasibilityCertificate.LCOAIncreaseFraction) ...
        * (1 + subprotocol.SuperiorityRules.MaxLCOAIncreaseFraction) + 1e-6);
end

function contract = contract_metrics( ...
        daily_nh3_kg, daily_contract_kg, max_delay_days)
day_count = numel(daily_nh3_kg);
backlog = zeros(day_count, 1);
for day_index = 1:day_count
    previous = 0;
    if day_index > 1
        previous = backlog(day_index - 1);
    end
    backlog(day_index) = max(0, ...
        previous + daily_contract_kg - daily_nh3_kg(day_index));
end

remaining = zeros(day_count, 1);
completion = NaN(day_count, 1);
tol = 1e-3;
for delivery_day = 1:day_count
    remaining(delivery_day) = daily_contract_kg;
    available = daily_nh3_kg(delivery_day);
    for contract_day = 1:delivery_day
        delivered = min(remaining(contract_day), available);
        remaining(contract_day) = remaining(contract_day) - delivered;
        available = available - delivered;
        if remaining(contract_day) <= tol && isnan(completion(contract_day))
            remaining(contract_day) = 0;
            completion(contract_day) = delivery_day;
        end
        if available <= tol
            break
        end
    end
end
delays = completion - (1:day_count)';
completed = delays(~isnan(delays));
if isempty(completed)
    maximum_delay = NaN;
else
    maximum_delay = max(completed);
end
contract = struct( ...
    'daily_quantity_kg', daily_contract_kg, ...
    'annual_quantity_t', daily_contract_kg * day_count / 1000, ...
    'daily_nh3_kg', daily_nh3_kg, ...
    'backlog_kg', backlog, ...
    'maximum_backlog_kg', max(backlog), ...
    'terminal_backlog_kg', backlog(end), ...
    'delivery_delay_days', delays, ...
    'maximum_delivery_delay_days', maximum_delay, ...
    'late_cohort_count', nnz(delays > max_delay_days), ...
    'unserved_cohort_count', nnz(remaining > tol));
end

function history = empty_carbon_history(day_count)
history = struct( ...
    'accounting', "annual_cumulative_reachability", ...
    'daily_emissions_kg', zeros(day_count, 1), ...
    'daily_nh3_kg', zeros(day_count, 1), ...
    'cumulative_emissions_kg', zeros(day_count, 1), ...
    'cumulative_nh3_kg', zeros(day_count, 1), ...
    'cumulative_debt_kg', zeros(day_count, 1), ...
    'remaining_reference_nh3_kg', zeros(day_count, 1), ...
    'reachability_margin_kg', zeros(day_count, 1), ...
    'completed_days', 0);
end

function history = empty_carbon_reserve_history( ...
        day_count, quantile, minimum_reserve_kgco2)
history = struct( ...
    'method', "expanding_recourse_purchase_exposure_quantile", ...
    'quantile', quantile, ...
    'minimum_reserve_kgco2', minimum_reserve_kgco2, ...
    'sample_count', zeros(day_count, 1), ...
    'reserve_kwh', zeros(day_count, 1), ...
    'reserve_kgco2', zeros(day_count, 1), ...
    'applied_reserve_kgco2', zeros(day_count, 1), ...
    'realized_shortfall_kwh', zeros(day_count, 1), ...
    'planned_purchase_kwh', zeros(day_count, 1), ...
    'actual_purchase_kwh', zeros(day_count, 1), ...
    'purchase_exposure_kwh', zeros(day_count, 1));
end

function history = empty_production_pacing_history(day_count)
history = struct( ...
    'method', "constrained_commitment_reference_governor", ...
    'requested_target_kg', NaN(day_count, 1), ...
    'day_ahead_target_kg', NaN(day_count, 1), ...
    'realtime_target_kg', NaN(day_count, 1), ...
    'day_ahead_projected', false(day_count, 1), ...
    'realtime_projected', false(day_count, 1), ...
    'day_ahead_restored', false(day_count, 1), ...
    'expired_contract_kg', zeros(day_count, 1), ...
    'contract_commit_min_nh3_kg', zeros(day_count, 1), ...
    'contract_allowable_backlog_kg', Inf(day_count, 1), ...
    'contract_h2_commit_min_kg', NaN(day_count, 1), ...
    'h2_reserve_target_min_kg', NaN(day_count, 1), ...
    'h2_reserve_raw_deficit_kg', NaN(day_count, 1), ...
    'h2_reserve_deficit_kg', NaN(day_count, 1), ...
    'h2_reserve_applied_scale', NaN(day_count, 1), ...
    'h2_reserve_projected', false(day_count, 1), ...
    'h2_reserve_carbon_guard_kg', zeros(day_count, 1), ...
    'h2_reserve_gate_open', false(day_count, 1), ...
    'h2_reserve_gate_reason', strings(day_count, 1));
end

function history = empty_hb_recourse_history(day_count)
history = struct( ...
    'method', "strict_replay_then_lexicographic_downward_recourse", ...
    'fallback_invoked', false(day_count, 1), ...
    'target_nh3_kg', zeros(day_count, 1), ...
    'actual_nh3_kg', zeros(day_count, 1), ...
    'shortfall_nh3_kg', zeros(day_count, 1), ...
    'requested_carbon_reserve_kg', zeros(day_count, 1), ...
    'realized_carbon_margin_kg', zeros(day_count, 1), ...
    'target_ael_module_hours', zeros(day_count, 1), ...
    'actual_ael_module_hours', zeros(day_count, 1), ...
    'ael_shortfall_module_hours', zeros(day_count, 1));
end

function [reserve_kg, history] = carbon_reserve_for_day( ...
        history, day_index, params)
if day_index <= 2 || history.quantile == 0
    samples_kwh = zeros(0, 1);
else
    samples_kwh = history.purchase_exposure_kwh(2:day_index - 1);
end
sample_count = numel(samples_kwh);
if sample_count == 0
    reserve_kwh = 0;
else
    sorted_samples = sort(samples_kwh);
    rank_index = min(sample_count, ...
        ceil((sample_count + 1) * history.quantile));
    reserve_kwh = sorted_samples(rank_index);
end
reserve_kg = reserve_kwh * params.environment.grid_co2;
if day_index < numel(history.reserve_kgco2)
    reserve_kg = max(reserve_kg, history.minimum_reserve_kgco2);
else
    reserve_kg = 0;
end
reserve_kwh = reserve_kg / params.environment.grid_co2;
history.sample_count(day_index) = sample_count;
history.reserve_kwh(day_index) = reserve_kwh;
history.reserve_kgco2(day_index) = reserve_kg;
end

function guard_kg = h2_reserve_carbon_guard_kg( ...
        params, daily_contract_kg, h2_reserve, subprotocol)
% H2 reserve targets are capped by forecast renewable-surplus charging.
% The annual CO2 reachability constraint remains the carbon feasibility
% authority; this diagnostic field is kept so grid runs can prove that no
% hidden extra carbon reserve was applied.
guard_kg = 0;
end

function reserve_kg = minimum_absolute_carbon_reserve_kg( ...
        params, contract_enabled)
if contract_enabled
    reserve_kg = 0;
    return
end
reserve_hours = 72;
reserve_nh3_kg = params.HB.min_load * params.HB.nh3_output ...
    * reserve_hours;
reserve_h2_kg = reserve_nh3_kg * params.HB.lit_h2;
ael_energy_kwh = reserve_h2_kg * params.AEL.common.spec_energy ...
    / params.unit.h2_density;
hb_energy_kwh = params.HB.min_load * params.HB.nom_power * 1000 ...
    * reserve_hours;
reserve_kg = (ael_energy_kwh + hb_energy_kwh) ...
    * params.environment.grid_co2;
end

function inventory_kg = h2_handoff_inventory_kg(params)
limits = h2_storage_limits( ...
    params.h2_storage, params.unit.h2_density);
one_step_h2_use_kg = params.HB.min_load * params.HB.nh3_output ...
    * params.HB.lit_h2 * params.time.step;
inventory_kg = limits.min_mass + one_step_h2_use_kg;
end

function shortfall_kwh = renewable_shortfall_kwh( ...
        forecast_data, actual_data, commit_count, params)
forecast_kw = (forecast_data.pv_power_kw(1:commit_count) ...
    + forecast_data.pw_power_kw(1:commit_count)) ...
    * params.renewable.input_scale;
actual_kw = (actual_data.pv_power_kw + actual_data.pw_power_kw) ...
    * params.renewable.input_scale;
shortfall_kwh = sum(max(forecast_kw - actual_kw, 0)) ...
    * params.time.step;
end

function history = record_carbon_day(history, day_index, ...
        daily_emissions_kg, daily_nh3_kg, state, params, ...
        daily_contract_kg, contract_enabled, remaining_time_count)
debt_kg = state.co2_emitted_kg ...
    - params.environment.co2_limit * state.nh3_produced_kg;
history.daily_emissions_kg(day_index) = daily_emissions_kg;
history.daily_nh3_kg(day_index) = daily_nh3_kg;
history.cumulative_emissions_kg(day_index) = state.co2_emitted_kg;
history.cumulative_nh3_kg(day_index) = state.nh3_produced_kg;
history.cumulative_debt_kg(day_index) = debt_kg;
if contract_enabled
    remaining_reference_nh3_kg = remaining_contract_reference_nh3_kg( ...
        params, daily_contract_kg, remaining_time_count);
    history.remaining_reference_nh3_kg(day_index) = ...
        remaining_reference_nh3_kg;
    history.reachability_margin_kg(day_index) = ...
        params.environment.co2_limit * remaining_reference_nh3_kg ...
        - debt_kg;
else
    [~, available_budget_kg] = absolute_carbon_budget_schedule( ...
        params, daily_contract_kg, remaining_time_count, 0);
    history.remaining_reference_nh3_kg(day_index) = 0;
    history.reachability_margin_kg(day_index) = ...
        available_budget_kg - state.co2_emitted_kg;
end
history.completed_days = day_index;
end

function remaining_kg = remaining_contract_reference_nh3_kg( ...
        params, daily_contract_kg, remaining_time_count)
remaining_kg = remaining_time_count * params.time.step / 24 ...
    * daily_contract_kg;
end

function [annual_budget_kg, available_at_start_kg, ...
        accrual_per_step_kg] = absolute_carbon_budget_schedule( ...
        params, daily_contract_kg, remaining_time_count, horizon_time_count)
annual_budget_kg = params.environment.co2_limit * daily_contract_kg * 365;
total_hours = params.time.hour_year * params.time.step;
elapsed_hours = (params.time.hour_year - remaining_time_count ...
    - horizon_time_count) * params.time.step;
borrowing_hours = 14 * 24;
available_at_start_kg = min(annual_budget_kg, ...
    annual_budget_kg * (elapsed_hours + borrowing_hours) / total_hours);
accrual_per_step_kg = annual_budget_kg * params.time.step / total_hours;
end

function available_budget_kg = available_absolute_carbon_budget( ...
        carbon, step_count)
available_budget_kg = min(carbon.annual_emissions_budget_kg, ...
    carbon.budget_available_at_start_kg ...
    + step_count * carbon.budget_accrual_per_step_kg);
end

function summary = carbon_state_summary(state, params)
summary = struct( ...
    'accounting', "annual_cumulative_observed_budget", ...
    'emissions_kg', state.co2_emitted_kg, ...
    'nh3_kg', state.nh3_produced_kg, ...
    'debt_kg', state.co2_emitted_kg ...
        - params.environment.co2_limit * state.nh3_produced_kg);
end

function require_annual_carbon_feasibility(state, params)
if ~params.environment.co2_enabled
    return
end
summary = carbon_state_summary(state, params);
tolerance_kg = annual_carbon_tolerance_kg(state.nh3_produced_kg, params);
if summary.debt_kg > tolerance_kg
    error('rolling_dispatch:terminal_carbon_breach', ...
        ['Year-end carbon emissions exceed the annual intensity ', ...
         'budget by %.6f kgCO2.'], summary.debt_kg);
end
end

function require_annual_grid_feasibility(state, params)
summary = grid_state_summary(state, params);
if summary.sell_debt_kwh > summary.tolerance_kwh
    error('rolling_dispatch:terminal_sell_breach', ...
        'Year-end electricity sales exceed the annual limit by %.6f kWh.', ...
        summary.sell_debt_kwh);
end
if summary.curtail_debt_kwh > summary.tolerance_kwh
    error('rolling_dispatch:terminal_curtail_breach', ...
        'Year-end curtailment exceeds the annual limit by %.6f kWh.', ...
        summary.curtail_debt_kwh);
end
end

function summary = grid_state_summary(state, params)
summary = grid_budget_summary(state.sell_kwh, state.curtail_kwh, ...
    state.renewable_kwh, params);
end

function summary = grid_state_summary_from_result(result, params)
summary = grid_budget_summary(result.summary.sell_kwh, ...
    result.summary.curtail_kwh, result.summary.renewable_kwh, params);
end

function summary = grid_budget_summary( ...
        sell_kwh, curtail_kwh, renewable_kwh, params)
tolerance_kwh = max(1e-3, 1e-8 * max(1, renewable_kwh));
summary = struct( ...
    'accounting', "annual_cumulative_observed_budget", ...
    'sell_kwh', sell_kwh, ...
    'curtail_kwh', curtail_kwh, ...
    'renewable_kwh', renewable_kwh, ...
    'sell_debt_kwh', sell_kwh ...
        - params.grid.max_sell * renewable_kwh, ...
    'curtail_debt_kwh', curtail_kwh ...
        - params.grid.curtail_limit * renewable_kwh, ...
    'tolerance_kwh', tolerance_kwh);
end

function tolerance_kg = annual_carbon_tolerance_kg(nh3_kg, params)
tolerance_kg = max(1e-3, ...
    1e-8 * max(1, params.environment.co2_limit * nh3_kg));
end

function records = empty_solver_records(day_count)
records = struct();
fields = {'plan_objective', 'plan_exitflag', 'plan_relative_gap', ...
    'plan_seconds', 'recourse_objective', 'recourse_exitflag', ...
    'recourse_relative_gap', 'recourse_seconds'};
for field_index = 1:numel(fields)
    records.(fields{field_index}) = NaN(day_count, 1);
end
end

function records = record_solver(records, day_index, phase, ...
        fval, exitflag, output, elapsed)
records.(phase + "_objective")(day_index) = fval;
records.(phase + "_exitflag")(day_index) = double(exitflag);
records.(phase + "_seconds")(day_index) = elapsed;
if isfield(output, 'relativegap')
    records.(phase + "_relative_gap")(day_index) = output.relativegap;
end
end

function day_index = first_unfinished_day(records)
day_index = find(isnan(records.recourse_exitflag), 1, 'first');
if isempty(day_index)
    day_index = numel(records.recourse_exitflag);
end
end

function output = aggregate_solver_output(records)
output = struct( ...
    'message', 'All rolling planning and recourse solves converged.', ...
    'relativegap', max([records.plan_relative_gap; ...
        records.recourse_relative_gap], [], 'omitnan'), ...
    'constrviolation', 0, ...
    'solver', 'intlinprog');
end

function plan = slack_diagnosis_plan()
plan = [ ...
    "1. Keep contract, equipment, and realtime fixed-plan rules unchanged."; ...
    "2. Minimize hydrogen-bound and transformer-power slack first."; ...
    "3. Then minimize HB-plan and AEL-commitment deviation slack."; ...
    "4. Report the first failed day and each minimum slack quantity."; ...
    "5. Do not accept the dispatch until the user chooses a correction."];
end

function context = result_context(params, renewable_data)
context = struct();
context.T = renewable_data.time_count;
context.dt = params.time.step;
context.P_total = (renewable_data.pv_power_kw(:) + ...
    renewable_data.pw_power_kw(:)) * params.renewable.input_scale;
context.AEL_spec_energy = params.AEL.common.spec_energy;
context.H2_density = params.unit.h2_density;
context.NH3_rate = params.HB.nh3_output;
context.HB_power_kw = params.HB.nom_power * 1000;
context.C_curt = params.grid.curtail_penalty;
context.C_purchase = params.grid.buy_price;
context.C_sell = params.grid.sell_price;
context.ael_common = params.AEL.common;
context.N_AEL_initial = 0;
end

function run_info = initial_run_info(source_path, scheme, forecast_mode, ...
        protocol, data_year, day_count, output_path, save_output)
run_info = struct( ...
    'status', "running", ...
    'executed_at', string(datetime('now')), ...
    'model_variant', "v51_rolling_dispatch", ...
    'source_mat_path', string(source_path), ...
    'scheme', scheme, ...
    'forecast_mode', forecast_mode, ...
    'carbon_accounting', "annual_cumulative_reachability", ...
    'grid_accounting', "annual_cumulative_observed_budget", ...
    'protocol_version', protocol.ProtocolVersion, ...
    'protocol_seal', protocol.Seal, ...
    'planning_hours', protocol.RollingDispatch.PlanningHours, ...
    'commit_hours', protocol.RollingDispatch.CommitHours, ...
    'data_year', data_year, ...
    'day_count', day_count, ...
    'output_path', string(output_path));
if ~save_output
    run_info.output_path = "";
end
end

function year_value = source_year(run_info, renewable_data)
if isfield(run_info, 'data_year')
    year_value = run_info.data_year;
elseif isfield(renewable_data, 'time') && isdatetime(renewable_data.time)
    year_value = year(renewable_data.time(1));
else
    error('rolling_dispatch:missing_year', ...
        'Input must provide run_info.data_year or datetime values.');
end
end

function dt = renewable_data_time_step(renewable_data)
if isfield(renewable_data, 'time_step_h')
    dt = renewable_data.time_step_h;
elseif isfield(renewable_data, 'time') && ...
        isdatetime(renewable_data.time) && numel(renewable_data.time) > 1
    dt = hours(renewable_data.time(2) - renewable_data.time(1));
else
    dt = 1;
end
end

function ensure_directory(path_value)
if ~isfolder(path_value)
    mkdir(path_value);
end
end

function diagnosis = classify_failure(run_info, failure_context, params)
try
    diagnosis = classify_infeasibility(struct( ...
        'run_info', run_info, ...
        'failure_context', failure_context, ...
        'params', params));
catch exception
    diagnosis = struct( ...
        'status', "classification_failed", ...
        'method', "rule_based_v1", ...
        'failure_day', NaN, ...
        'failure_stage', "unknown", ...
        'categories', "classification_failed", ...
        'primary_category', "classification_failed", ...
        'error_id', string(exception.identifier), ...
        'error_message', string(exception.message));
end
end

function project_dir = project_root()
source_dir = fileparts(mfilename('fullpath'));
project_dir = fileparts(source_dir);
end

function add_project_paths(project_dir)
addpath(fullfile(project_dir, 'src'));
addpath(fullfile(project_dir, 'src', 'params'));
addpath(fullfile(project_dir, 'src', 'results'));
addpath(fullfile(project_dir, 'src', 'protocol'));
end

function value = option_value(options, name, default_value)
if isstruct(options) && isfield(options, name) && ~isempty(options.(name))
    value = options.(name);
else
    value = default_value;
end
end
