function [grid_table, run_info] = stage4_run_v51_h2_reserve_grid(config)
%STAGE4_RUN_V51_H2_RESERVE_GRID Run the frozen H2-reserve candidate grid.

if nargin < 1 || isempty(config)
    config = struct();
end

project_dir = project_root();
add_project_paths(project_dir);
subprotocol = protocol_v5('v5_1');
if ~protocol_v5('verify_v5_1', subprotocol)
    error('stage4_run_v51_h2_reserve_grid:bad_protocol', ...
        'Protocol v5.1 verification failed.');
end

source_mat_path = option_value(config, 'source_mat_path', ...
    fullfile(project_dir, 'runs', 'stage1', ...
    'zhou_s2_baseline_2022_latest.mat'));
baseline_mat_path = option_value(config, 'baseline_mat_path', ...
    fullfile(project_dir, 'runs', 'rolling', ...
    'v51_contract_plan_and_hb_smoothing_2022_latest.mat'));
output_dir = option_value(config, 'output_dir', ...
    fullfile(project_dir, 'runs', 'stage4', 'h2_reserve_grid'));
rolling_output_dir = option_value(config, 'rolling_output_dir', ...
    fullfile(output_dir, 'rolling'));
save_output = option_value(config, 'save_output', true);
dry_run = option_value(config, 'dry_run', false);
verbose = option_value(config, 'verbose', true);

source_year_value = source_year_from_mat(source_mat_path);
reserve_quantiles = option_value(config, 'reserve_quantiles', ...
    subprotocol.Calibration.CandidateGrid.ReserveQuantile);
lookahead_days = option_value(config, 'reserve_lookahead_days', ...
    subprotocol.Calibration.CandidateGrid.ReserveLookaheadDays);
reserve_quantiles = reserve_quantiles(:)';
lookahead_days = lookahead_days(:)';

run_info = struct( ...
    'stage', "stage4", ...
    'status', "running", ...
    'executed_at', string(datetime('now')), ...
    'protocol_version', subprotocol.ProtocolVersion, ...
    'protocol_seal', subprotocol.Seal, ...
    'source_mat_path', string(source_mat_path), ...
    'baseline_mat_path', string(baseline_mat_path), ...
    'data_year', source_year_value, ...
    'scheme', "contract_plan_and_hb_smoothing", ...
    'forecast_mode', "observed_oracle", ...
    'selection_rule', ...
        subprotocol.Calibration.SelectionRule, ...
    'lexicographic_order', ...
        subprotocol.Calibration.LexicographicOrder, ...
    'output_path', "");

rows = empty_grid_row();
rows(1) = [];
if option_value(config, 'include_baseline', true)
    rows(end + 1) = baseline_row(baseline_mat_path);
end

for quantile = reserve_quantiles
    for lookahead = lookahead_days
        candidate = empty_grid_row();
        candidate.case_id = string(sprintf('h2q%03d_l%d', ...
            round(100 * quantile), lookahead));
        candidate.h2_reserve_quantile = quantile;
        candidate.h2_reserve_lookahead_days = lookahead;
        candidate.is_baseline = false;
        if dry_run
            candidate.status = "planned";
            rows(end + 1) = candidate;
            continue
        end

        rolling_config = struct( ...
            'source_mat_path', source_mat_path, ...
            'scheme', "contract_plan_and_hb_smoothing", ...
            'forecast_mode', "observed_oracle", ...
            'h2_reserve_quantile', quantile, ...
            'h2_reserve_lookahead_days', lookahead, ...
            'output_dir', rolling_output_dir, ...
            'save_output', true, ...
            'verbose', verbose, ...
            'solver_display', option_value(config, ...
                'solver_display', 'none'), ...
            'max_time_seconds_per_solve', option_value(config, ...
                'max_time_seconds_per_solve', ...
                subprotocol.RollingDispatch.MaxTimeSecondsPerSolve), ...
            'relative_gap_tolerance', option_value(config, ...
                'relative_gap_tolerance', ...
                subprotocol.RollingDispatch.RelativeGapTolerance));
        try
            [result, candidate_info, metrics] = ...
                rolling_dispatch(rolling_config);
            candidate = completed_row(candidate, result, ...
                candidate_info, metrics);
        catch exception
            candidate.status = "failed";
            candidate.error_id = string(exception.identifier);
            candidate.error_message = string(exception.message);
        end
        rows(end + 1) = candidate;
    end
end

grid_table = struct2table(rows);
run_info.status = "completed";
run_info.selected_candidate = select_candidate(grid_table);

if save_output && ~dry_run
    ensure_directory(output_dir);
    output_path = fullfile(output_dir, sprintf( ...
        'v51_h2_reserve_grid_%d_latest.mat', source_year_value));
    run_info.output_path = string(output_path);
    save(output_path, 'grid_table', 'run_info', 'subprotocol');
end

if nargout == 0
    disp(grid_table);
    disp(run_info.selected_candidate);
end
end

function row = empty_grid_row()
row = struct( ...
    'case_id', "", ...
    'status', "", ...
    'is_baseline', false, ...
    'h2_reserve_quantile', NaN, ...
    'h2_reserve_lookahead_days', NaN, ...
    'h2_reserve_mean_applied_scale', NaN, ...
    'h2_reserve_min_applied_scale', NaN, ...
    'h2_reserve_projected_days', NaN, ...
    'NH3_t_y', NaN, ...
    'LCOA_USD_t', NaN, ...
    'net_profit_MUSD', NaN, ...
    'contract_shortfall_p95_kg', NaN, ...
    'MAR', NaN, ...
    'h2_soc_p05', NaN, ...
    'max_backlog_kg', NaN, ...
    'terminal_backlog_kg', NaN, ...
    'co2_kg_per_kg', NaN, ...
    'purchase_rate', NaN, ...
    'sell_rate', NaN, ...
    'curtail_rate', NaN, ...
    'AEL_startup_count', NaN, ...
    'strict_delivery_ok', false, ...
    'terminal_contract_ok', false, ...
    'annual_output_ok', false, ...
    'terminal_h2_ok', false, ...
    'annual_co2_ok', false, ...
    'annual_sell_ok', false, ...
    'annual_curtail_ok', false, ...
    'lcoa_cap_ok', false, ...
    'output_path', "", ...
    'error_id', "", ...
    'error_message', "");
end

function row = baseline_row(mat_path)
if ~isfile(mat_path)
    error('stage4_run_v51_h2_reserve_grid:missing_baseline', ...
        'Missing baseline rolling result: %s', mat_path);
end
loaded = load(mat_path, 'result', 'run_info', 'metrics');
row = empty_grid_row();
row.case_id = "baseline_h2q000_l0";
row.h2_reserve_quantile = 0;
row.h2_reserve_lookahead_days = 0;
row.is_baseline = true;
row = completed_row(row, loaded.result, loaded.run_info, loaded.metrics);
end

function row = completed_row(row, result, candidate_info, metrics)
row.status = string(candidate_info.status);
if isfield(candidate_info, 'production_pacing_history') && ...
        isfield(candidate_info.production_pacing_history, ...
        'h2_reserve_applied_scale')
    scales = candidate_info.production_pacing_history ...
        .h2_reserve_applied_scale;
    projected = candidate_info.production_pacing_history ...
        .h2_reserve_projected;
    row.h2_reserve_mean_applied_scale = mean(scales, 'omitnan');
    row.h2_reserve_min_applied_scale = min(scales, [], 'omitnan');
    row.h2_reserve_projected_days = nnz(projected);
end
row.NH3_t_y = result.summary.NH3_prod_t_y;
row.LCOA_USD_t = result.summary.lcoa;
row.net_profit_MUSD = result.summary.net_profit / 1e6;
row.contract_shortfall_p95_kg = ...
    metrics.Primary.contract_shortfall_p95;
row.MAR = metrics.Primary.mar;
row.h2_soc_p05 = metrics.Primary.h2_soc_p05;
row.max_backlog_kg = metrics.Contract.maximum_backlog_kg;
row.terminal_backlog_kg = metrics.Contract.terminal_backlog_kg;
row.co2_kg_per_kg = result.summary.co2_intensity;
row.purchase_rate = result.summary.purchase_rate;
row.sell_rate = result.summary.sell_rate;
row.curtail_rate = result.summary.curtail_rate;
row.AEL_startup_count = result.summary.AEL_startup_count;
row.strict_delivery_ok = metrics.Feasibility.strict_delivery_ok;
row.terminal_contract_ok = metrics.Feasibility.terminal_contract_ok;
row.annual_output_ok = metrics.Feasibility.annual_output_ok;
row.terminal_h2_ok = metrics.Feasibility.terminal_h2_ok;
row.annual_co2_ok = metrics.Feasibility.annual_co2_ok;
row.annual_sell_ok = metrics.Feasibility.annual_sell_ok;
row.annual_curtail_ok = metrics.Feasibility.annual_curtail_ok;
row.lcoa_cap_ok = metrics.Feasibility.lcoa_cap_ok;
row.output_path = string(candidate_info.output_path);
end

function selected = select_candidate(grid_table)
feasible = grid_table.status == "completed" ...
    & grid_table.strict_delivery_ok ...
    & grid_table.terminal_contract_ok ...
    & grid_table.annual_output_ok ...
    & grid_table.terminal_h2_ok ...
    & grid_table.annual_co2_ok ...
    & grid_table.annual_sell_ok ...
    & grid_table.annual_curtail_ok ...
    & grid_table.lcoa_cap_ok;
if ~any(feasible)
    selected = struct('status', "no_feasible_candidate");
    return
end
candidates = grid_table(feasible, :);
candidates.h2_soc_p05_sort = -candidates.h2_soc_p05;
candidates = sortrows(candidates, { ...
    'contract_shortfall_p95_kg', 'MAR', ...
    'h2_soc_p05_sort', 'LCOA_USD_t'});
selected = table2struct(candidates(1, :), 'ToScalar', true);
selected = rmfield(selected, 'h2_soc_p05_sort');
end

function year_value = source_year_from_mat(source_mat_path)
loaded = load(source_mat_path, 'run_info', 'renewable_data');
if isfield(loaded, 'run_info') && isfield(loaded.run_info, 'data_year')
    year_value = loaded.run_info.data_year;
elseif isfield(loaded, 'renewable_data') && ...
        isfield(loaded.renewable_data, 'time') && ...
        isdatetime(loaded.renewable_data.time)
    year_value = year(loaded.renewable_data.time(1));
else
    error('stage4_run_v51_h2_reserve_grid:missing_year', ...
        'Input MAT must provide run_info.data_year or datetime values.');
end
end

function add_project_paths(project_dir)
addpath(fullfile(project_dir, 'src'));
addpath(fullfile(project_dir, 'src', 'params'));
addpath(fullfile(project_dir, 'src', 'results'));
addpath(fullfile(project_dir, 'src', 'protocol'));
end

function project_dir = project_root()
src_dir = fileparts(mfilename('fullpath'));
project_dir = fileparts(src_dir);
end

function ensure_directory(path_value)
if ~isfolder(path_value)
    mkdir(path_value);
end
end

function value = option_value(config, name, default_value)
if isfield(config, name) && ~isempty(config.(name))
    value = config.(name);
else
    value = default_value;
end
end
