function [grid_table, run_info] = stage5_run_v51_joint_grid(config)
%STAGE5_RUN_V51_JOINT_GRID Run joint H2 reserve, pacing, and HB smoothing.

if nargin < 1 || isempty(config)
    config = struct();
end

project_dir = project_root();
add_project_paths(project_dir);
subprotocol = protocol_v5('v5_1');
if ~protocol_v5('verify_v5_1', subprotocol)
    error('stage5_run_v51_joint_grid:bad_protocol', ...
        'Protocol v5.1 verification failed.');
end

source_mat_path = option_value(config, 'source_mat_path', ...
    fullfile(project_dir, 'runs', 'stage1', ...
    'zhou_s2_baseline_2022_latest.mat'));
baseline_mat_path = option_value(config, 'baseline_mat_path', ...
    fullfile(project_dir, 'runs', 'rolling', ...
    'v51_contract_plan_and_hb_smoothing_2022_latest.mat'));
output_dir = option_value(config, 'output_dir', ...
    fullfile(project_dir, 'runs', 'stage5', 'joint_grid'));
rolling_output_dir = option_value(config, 'rolling_output_dir', ...
    fullfile(output_dir, 'rolling'));
save_output = option_value(config, 'save_output', true);
dry_run = option_value(config, 'dry_run', false);
verbose = option_value(config, 'verbose', false);
candidate_progress = option_value(config, 'candidate_progress', true);
if ~(islogical(candidate_progress) && isscalar(candidate_progress))
    error('stage5_run_v51_joint_grid:bad_progress', ...
        'candidate_progress must be a scalar logical.');
end
gate_mode = string(option_value(config, 'h2_reserve_gate_mode', ...
    "contract_carbon_state_gate"));
soft_reserve = option_value(config, 'h2_reserve_soft', true);
if ~(islogical(soft_reserve) && isscalar(soft_reserve))
    error('stage5_run_v51_joint_grid:bad_soft_reserve', ...
        'h2_reserve_soft must be a scalar logical.');
end
allow_infeasible_continuation = option_value(config, ...
    'allow_infeasible_continuation', true);
if ~(islogical(allow_infeasible_continuation) && ...
        isscalar(allow_infeasible_continuation))
    error('stage5_run_v51_joint_grid:bad_restoration', ...
        'allow_infeasible_continuation must be a scalar logical.');
end
restoration_slack_penalty_usd_per_kg = option_value(config, ...
    'restoration_slack_penalty_usd_per_kg', 1e6);
if ~(isnumeric(restoration_slack_penalty_usd_per_kg) && ...
        isscalar(restoration_slack_penalty_usd_per_kg) && ...
        isfinite(restoration_slack_penalty_usd_per_kg) && ...
        restoration_slack_penalty_usd_per_kg >= 0)
    error('stage5_run_v51_joint_grid:bad_restoration', ...
        ['restoration_slack_penalty_usd_per_kg must be a finite ', ...
         'nonnegative scalar.']);
end

source_year_value = source_year_from_mat(source_mat_path);
reserve_designs = create_reserve_designs( ...
    option_value(config, 'reserve_quantiles', ...
    [0, subprotocol.Calibration.CandidateGrid.ReserveQuantile]), ...
    option_value(config, 'reserve_lookahead_days', ...
    subprotocol.Calibration.CandidateGrid.ReserveLookaheadDays));
pacing_values = option_value(config, ...
    'contract_pacing_aggressiveness', [0, 0.25, 0.50]);
smoothing_values = option_value(config, ...
    'hb_smoothing_reduction_fraction', ...
    subprotocol.Calibration.CandidateGrid ...
    .HBSmoothingTargetReductionFraction);
pacing_values = pacing_values(:)';
smoothing_values = smoothing_values(:)';
total_candidate_count = numel(reserve_designs) * numel(pacing_values) ...
    * numel(smoothing_values);
candidate_limit = option_value(config, 'candidate_limit', Inf);
if ~(isnumeric(candidate_limit) && isscalar(candidate_limit) && ...
        (isfinite(candidate_limit) || isinf(candidate_limit)))
    error('stage5_run_v51_joint_grid:bad_candidate_limit', ...
        'candidate_limit must be a finite nonnegative scalar or Inf.');
end
if candidate_limit < 0 || ...
        (isfinite(candidate_limit) && candidate_limit ~= floor(candidate_limit))
    error('stage5_run_v51_joint_grid:bad_candidate_limit', ...
        'candidate_limit must be a nonnegative integer or Inf.');
end
planned_candidate_count = min(total_candidate_count, candidate_limit);

run_info = struct( ...
    'stage', "stage5", ...
    'status', "running", ...
    'executed_at', string(datetime('now')), ...
    'protocol_version', subprotocol.ProtocolVersion, ...
    'protocol_seal', subprotocol.Seal, ...
    'source_mat_path', string(source_mat_path), ...
    'baseline_mat_path', string(baseline_mat_path), ...
    'data_year', source_year_value, ...
    'scheme', "contract_plan_and_hb_smoothing", ...
    'forecast_mode', "observed_oracle", ...
    'h2_reserve_gate_mode', gate_mode, ...
    'h2_reserve_soft', soft_reserve, ...
    'allow_infeasible_continuation', allow_infeasible_continuation, ...
    'restoration_slack_penalty_usd_per_kg', ...
        restoration_slack_penalty_usd_per_kg, ...
    'planned_candidate_count', planned_candidate_count, ...
    'selection_rule', ...
        subprotocol.Calibration.SelectionRule, ...
    'lexicographic_order', ...
        subprotocol.Calibration.LexicographicOrder, ...
    'output_path', "");

rows = empty_grid_row();
rows(1) = [];
if option_value(config, 'include_baseline', true)
    rows(end + 1) = baseline_row(baseline_mat_path);
end

candidate_count = 0;
for reserve_index = 1:numel(reserve_designs)
    reserve = reserve_designs(reserve_index);
    for pacing = pacing_values
        for smoothing = smoothing_values
            if candidate_count >= candidate_limit
                break
            end
            candidate_count = candidate_count + 1;
            candidate = empty_grid_row();
            candidate.case_id = candidate_id( ...
                reserve.quantile, reserve.lookahead_days, ...
                pacing, smoothing);
            candidate.h2_reserve_quantile = reserve.quantile;
            candidate.h2_reserve_lookahead_days = ...
                reserve.lookahead_days;
            candidate.contract_pacing_aggressiveness = pacing;
            candidate.hb_smoothing_reduction_fraction = smoothing;
            candidate.h2_reserve_gate_mode = gate_mode;
            candidate.h2_reserve_soft = soft_reserve;
            candidate.is_baseline = false;
            if dry_run
                candidate.status = "planned";
                rows(end + 1) = candidate;
                continue
            end
            if candidate_progress
                fprintf('Stage5 candidate %d/%d: %s\n', ...
                    candidate_count, planned_candidate_count, ...
                    candidate.case_id);
            end
            candidate_timer = tic;

            rolling_config = struct( ...
                'source_mat_path', source_mat_path, ...
                'scheme', "contract_plan_and_hb_smoothing", ...
                'forecast_mode', "observed_oracle", ...
                'h2_reserve_quantile', reserve.quantile, ...
                'h2_reserve_lookahead_days', reserve.lookahead_days, ...
                'h2_reserve_soft', soft_reserve, ...
                'h2_reserve_gate_mode', gate_mode, ...
                'contract_pacing_aggressiveness', pacing, ...
                'hb_smoothing_reduction_fraction', smoothing, ...
                'allow_infeasible_continuation', ...
                    allow_infeasible_continuation, ...
                'restoration_slack_penalty_usd_per_kg', ...
                    restoration_slack_penalty_usd_per_kg, ...
                'output_dir', rolling_output_dir, ...
                'save_output', true, ...
                'verbose', verbose, ...
                'solver_display', option_value(config, ...
                'solver_display', 'none'), ...
                'max_time_seconds_per_solve', option_value(config, ...
                'max_time_seconds_per_solve', ...
                subprotocol.RollingDispatch.MaxTimeSecondsPerSolve), ...
                'relative_gap_tolerance', option_value(config, ...
                'relative_gap_tolerance', ...
                subprotocol.RollingDispatch.RelativeGapTolerance));
            try
                [result, candidate_info, metrics] = ...
                    rolling_dispatch(rolling_config);
                candidate = completed_row(candidate, result, ...
                    candidate_info, metrics);
            catch exception
                candidate.status = "failed";
                candidate.error_id = string(exception.identifier);
                candidate.error_message = string(exception.message);
            end
            if candidate_progress
                print_candidate_completion(candidate_count, ...
                    planned_candidate_count, candidate, ...
                    toc(candidate_timer));
            end
            rows(end + 1) = candidate;
            if save_output && ~dry_run
                save_stage5_checkpoint(output_dir, source_year_value, ...
                    rows, run_info, subprotocol, candidate_count);
            end
        end
        if candidate_count >= candidate_limit
            break
        end
    end
    if candidate_count >= candidate_limit
        break
    end
end

grid_table = struct2table(rows);
run_info.status = "completed";
run_info.candidate_count = candidate_count;
run_info.selected_candidate = select_candidate(grid_table);

if save_output && ~dry_run
    ensure_directory(output_dir);
    output_path = fullfile(output_dir, sprintf( ...
        'v51_joint_grid_%d_latest.mat', source_year_value));
    run_info.output_path = string(output_path);
    save(output_path, 'grid_table', 'run_info', 'subprotocol');
end

if nargout == 0
    disp(grid_table);
    disp(run_info.selected_candidate);
end
end

function save_stage5_checkpoint(output_dir, data_year, rows, ...
        run_info, subprotocol, candidate_count)
ensure_directory(output_dir);
grid_table = struct2table(rows);
checkpoint_info = run_info;
checkpoint_info.status = "running";
checkpoint_info.candidate_count = candidate_count;
checkpoint_info.completed_row_count = height(grid_table);
checkpoint_info.selected_candidate = select_candidate(grid_table);
checkpoint_info.output_path = string(fullfile(output_dir, sprintf( ...
    'v51_joint_grid_%d_latest.mat', data_year)));
checkpoint_path = fullfile(output_dir, sprintf( ...
    'v51_joint_grid_%d_checkpoint.mat', data_year));
save(checkpoint_path, 'grid_table', 'checkpoint_info', 'subprotocol');
end

function designs = create_reserve_designs(quantiles, lookahead_days)
quantiles = unique(quantiles(:)', 'stable');
lookahead_days = unique(lookahead_days(:)', 'stable');
designs = struct('quantile', {}, 'lookahead_days', {});
for quantile = quantiles
    if quantile == 0
        designs(end + 1) = struct( ...
            'quantile', 0, 'lookahead_days', 0);
        continue
    end
    for lookahead = lookahead_days
        designs(end + 1) = struct( ...
            'quantile', quantile, ...
            'lookahead_days', lookahead);
    end
end
end

function id = candidate_id(quantile, lookahead, pacing, smoothing)
id = string(sprintf('joint_h2q%03d_l%d_cp%03d_hb%03d', ...
    round(100 * quantile), lookahead, ...
    round(100 * pacing), round(100 * smoothing)));
end

function row = empty_grid_row()
row = struct( ...
    'case_id', "", ...
    'status', "", ...
    'is_baseline', false, ...
    'h2_reserve_quantile', NaN, ...
    'h2_reserve_lookahead_days', NaN, ...
    'h2_reserve_gate_mode', "", ...
    'h2_reserve_soft', false, ...
    'contract_pacing_aggressiveness', NaN, ...
    'hb_smoothing_reduction_fraction', NaN, ...
    'h2_reserve_mean_applied_scale', NaN, ...
    'h2_reserve_min_applied_scale', NaN, ...
    'h2_reserve_projected_days', NaN, ...
    'h2_reserve_gate_closed_days', NaN, ...
    'restoration_day_count', NaN, ...
    'expired_contract_kg', NaN, ...
    'completed_days', NaN, ...
    'expected_days', NaN, ...
    'NH3_t_y', NaN, ...
    'LCOA_USD_t', NaN, ...
    'net_profit_MUSD', NaN, ...
    'contract_shortfall_p95_kg', NaN, ...
    'MAR', NaN, ...
    'h2_soc_p05', NaN, ...
    'max_backlog_kg', NaN, ...
    'terminal_backlog_kg', NaN, ...
    'co2_kg_per_kg', NaN, ...
    'purchase_rate', NaN, ...
    'sell_rate', NaN, ...
    'curtail_rate', NaN, ...
    'AEL_startup_count', NaN, ...
    'strict_delivery_ok', false, ...
    'terminal_contract_ok', false, ...
    'annual_output_ok', false, ...
    'terminal_h2_ok', false, ...
    'annual_co2_ok', false, ...
    'annual_sell_ok', false, ...
    'annual_curtail_ok', false, ...
    'lcoa_cap_ok', false, ...
    'output_path', "", ...
    'error_id', "", ...
    'error_message', "");
end

function row = baseline_row(mat_path)
if ~isfile(mat_path)
    error('stage5_run_v51_joint_grid:missing_baseline', ...
        'Missing baseline rolling result: %s', mat_path);
end
loaded = load(mat_path, 'result', 'run_info', 'metrics');
row = empty_grid_row();
row.case_id = "baseline_joint_reference";
row.h2_reserve_quantile = 0;
row.h2_reserve_lookahead_days = 0;
row.h2_reserve_gate_mode = "off";
row.h2_reserve_soft = false;
row.contract_pacing_aggressiveness = 0;
row.hb_smoothing_reduction_fraction = 0;
row.is_baseline = true;
row = completed_row(row, loaded.result, loaded.run_info, loaded.metrics);
end

function row = completed_row(row, result, candidate_info, metrics)
row.status = string(candidate_info.status);
if isfield(candidate_info, 'day_count')
    row.completed_days = candidate_info.day_count;
    row.expected_days = candidate_info.day_count;
end
if isfield(candidate_info, 'production_pacing_history') && ...
        isfield(candidate_info.production_pacing_history, ...
        'h2_reserve_applied_scale')
    history = candidate_info.production_pacing_history;
    scales = history.h2_reserve_applied_scale;
    projected = history.h2_reserve_projected;
    row.h2_reserve_mean_applied_scale = mean(scales, 'omitnan');
    row.h2_reserve_min_applied_scale = min(scales, [], 'omitnan');
    row.h2_reserve_projected_days = nnz(projected);
    if isfield(history, 'h2_reserve_gate_open')
        row.h2_reserve_gate_closed_days = ...
            nnz(~history.h2_reserve_gate_open);
    end
    if isfield(history, 'day_ahead_restored')
        row.restoration_day_count = nnz(history.day_ahead_restored);
    end
    if isfield(history, 'expired_contract_kg')
        row.expired_contract_kg = ...
            sum(history.expired_contract_kg, 'omitnan');
    end
end
row.NH3_t_y = result.summary.NH3_prod_t_y;
row.LCOA_USD_t = result.summary.lcoa;
row.net_profit_MUSD = result.summary.net_profit / 1e6;
row.contract_shortfall_p95_kg = ...
    metrics.Primary.contract_shortfall_p95;
row.MAR = metrics.Primary.mar;
row.h2_soc_p05 = metrics.Primary.h2_soc_p05;
row.max_backlog_kg = metrics.Contract.maximum_backlog_kg;
row.terminal_backlog_kg = metrics.Contract.terminal_backlog_kg;
row.co2_kg_per_kg = result.summary.co2_intensity;
row.purchase_rate = result.summary.purchase_rate;
row.sell_rate = result.summary.sell_rate;
row.curtail_rate = result.summary.curtail_rate;
row.AEL_startup_count = result.summary.AEL_startup_count;
row.strict_delivery_ok = metrics.Feasibility.strict_delivery_ok;
row.terminal_contract_ok = metrics.Feasibility.terminal_contract_ok;
row.annual_output_ok = metrics.Feasibility.annual_output_ok;
row.terminal_h2_ok = metrics.Feasibility.terminal_h2_ok;
row.annual_co2_ok = metrics.Feasibility.annual_co2_ok;
row.annual_sell_ok = metrics.Feasibility.annual_sell_ok;
row.annual_curtail_ok = metrics.Feasibility.annual_curtail_ok;
row.lcoa_cap_ok = metrics.Feasibility.lcoa_cap_ok;
row.output_path = string(candidate_info.output_path);
end

function print_candidate_completion(index, total, row, elapsed_seconds)
if isfinite(row.completed_days) && isfinite(row.expected_days)
    days_text = sprintf('%d/%d', round(row.completed_days), ...
        round(row.expected_days));
else
    days_text = 'n/a';
end
fprintf(['Stage5 candidate %d/%d finished: %s status=%s ', ...
    'days=%s strict=%d terminal_contract=%d co2=%d terminal_h2=%d ', ...
    'restore_days=%g expired_kg=%.3f elapsed=%.1fs\n'], ...
    index, total, char(row.case_id), char(row.status), days_text, ...
    logical(row.strict_delivery_ok), logical(row.terminal_contract_ok), ...
    logical(row.annual_co2_ok), logical(row.terminal_h2_ok), ...
    row.restoration_day_count, row.expired_contract_kg, elapsed_seconds);
end

function selected = select_candidate(grid_table)
feasible = grid_table.status == "completed" ...
    & grid_table.strict_delivery_ok ...
    & grid_table.terminal_contract_ok ...
    & grid_table.annual_output_ok ...
    & grid_table.terminal_h2_ok ...
    & grid_table.annual_co2_ok ...
    & grid_table.annual_sell_ok ...
    & grid_table.annual_curtail_ok ...
    & grid_table.lcoa_cap_ok;
if ~any(feasible)
    selected = struct('status', "no_feasible_candidate");
    return
end
candidates = grid_table(feasible, :);
candidates.h2_soc_p05_sort = -candidates.h2_soc_p05;
candidates = sortrows(candidates, { ...
    'contract_shortfall_p95_kg', 'MAR', ...
    'h2_soc_p05_sort', 'LCOA_USD_t'});
selected = table2struct(candidates(1, :), 'ToScalar', true);
selected = rmfield(selected, 'h2_soc_p05_sort');
end

function year_value = source_year_from_mat(source_mat_path)
loaded = load(source_mat_path, 'run_info', 'renewable_data');
if isfield(loaded, 'run_info') && isfield(loaded.run_info, 'data_year')
    year_value = loaded.run_info.data_year;
elseif isfield(loaded, 'renewable_data') && ...
        isfield(loaded.renewable_data, 'time') && ...
        isdatetime(loaded.renewable_data.time)
    year_value = year(loaded.renewable_data.time(1));
else
    error('stage5_run_v51_joint_grid:missing_year', ...
        'Input MAT must provide run_info.data_year or datetime values.');
end
end

function add_project_paths(project_dir)
addpath(fullfile(project_dir, 'src'));
addpath(fullfile(project_dir, 'src', 'params'));
addpath(fullfile(project_dir, 'src', 'results'));
addpath(fullfile(project_dir, 'src', 'protocol'));
end

function project_dir = project_root()
src_dir = fileparts(mfilename('fullpath'));
project_dir = fileparts(src_dir);
end

function ensure_directory(path_value)
if ~isfolder(path_value)
    mkdir(path_value);
end
end

function value = option_value(config, name, default_value)
if isfield(config, name) && ~isempty(config.(name))
    value = config.(name);
else
    value = default_value;
end
end
